### ISSUE TITLE
Glossary - Candidates limit criteria

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#100]
Change Term and Definition:

From: 
Term: Candidates Limit Criteria
Definition: The objective and non-discriminatory criteria or rules that will be applied to limit the number of candidates meeting the selection criteria.

To: Candidate selection terms
Term: The objective and non-discriminatory conditions and stipulations that will limit the number of candidates in the selection phase of the procedure.

WG Decision 18/05/2018

**Comment by eprocurementontology** [comment]
WG approval 18/05/2015

Term: Candidate selection terms
Definition: The objective and non-discriminatory conditions and stipulations that will limit the number of candidates in the selection phase of the procedure.

Additional information/WG discussion points: In two-stage procedures.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
I would propose to remove "stipulations" (or at least replace it with "rule" or "requirement"). See #88 for the reasoning.

**Comment by muricna** [comment]
I would tend to agree

**Comment by muricna** [comment]
The term is not currently used in the ontology
