### ISSUE TITLE
Glossary - Central purchasing body

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#101]
Change  Definition (copy paste from directives 201/24/EU and 2014/25//EU

Term: A procuring entity that provides centralised purchasing activities and, possibly, ancillary purchasing activities for other procuring entities.

WG Decision 18/05/2018

**Comment by eprocurementontology** [comment]
WG approval 18/05/2018

Term: Central purchasing body
Definition: A procuring entity that provides centralised purchasing activities and, possibly, ancillary purchasing activities for other procuring entities.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
