### ISSUE TITLE
Glossary - Centralised purchasing activities

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#102]
New term integrated using definitions from Directives 2014/24/EU and 2014/25/EU as a source
The term was integrated to explain the definition of Central purchasing body which uses this domain specific term.

Definition: 1. Acquisiton of goods or services intended for one or more procuring entity; and/or  
2. Award of procurement procedures for works, goods or services intended for one or more procuring entity; and/or
3. Conclusion of framework agreements for works, goods or services intended for one or more procuring entity.

WG approval 18/05/2018

**Comment by eprocurementontology** [comment]
WG approval 18/05/2018

Term: Centralised Purchasing Activities
Definition: 1. Acquisiton of goods or services intended for one or more procuring entity; and/or  
2. Award of procurement procedures for works, goods or services intended for one or more procuring entity; and/or
3. Conclusion of framework agreements for works, goods or services intended for one or more procuring entity.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
