### ISSUE TITLE
GLOSSARY - Combination Lots --- Tender type

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#105]
New Term and definition

Replace

Term: Combination Lotrs
Definition: Description on how to bind lots when submitting a tender...........

By 

Term: Tender type
Definition: Tender  type : How lots can be combined, or   not, when submitting tenders in a public procurement procedure

WG approval:  25/05/2018

**Comment by muricna** [comment]
Currently TED uses the term Bid type.
We need to see how we are to name code lists and whether we will use old code lists and add new requirements or create a new for the ontology

**Comment by eprocurementontology** [comment]
WG approval 25/05/2018

Term: Tender Type
Definition: How lots can be combined, or not, when submitting tenders in a public procurement procedure.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
Is the "or not" consistent with the way other concepts are presented? I would find "How lots can be combined when submitting tenders in a public procurement procedure." more natural.

**Comment by muricna** [comment]
The or not is to cover both inclusive or exclusive combinations of lots.

**Comment by JachymHercher** [comment]
I think only inclusive combinations are "allowed" and necessary? In other words, what is not included as an allowed combination of lots is forbidden.

**Comment by muricna** [comment]
It could be that if you submit for Lot 1 you cannot submit for Lot 2 but you can submit for Lot 3 hence the inclusive and exclusive

**Comment by JachymHercher** [comment]
Ok, I get the business case. One can do that, in some contexts it's useful (e.g. one lot for building a house, second lot for checking that the house is well built). 

However, I think from a modelling point of view were mixing two (similar but different) things in one concept. 

1) Grouping lots for evaluation and award purposes, in the sense of 2014/24/EU Art. 46(3). This corresponds to BG-330 (Group Award) in eForms. This is about the submission of "grouped tenders", e.g. I submit a tender for lots 1,2,3 and a grouped tender for (1+2+3). 

2) Restricting the lots you can submit a bid tender for, in the sense of 2014/24/EU Art. 46(2) first sub-paragraph. This is about restricting for what you can submit individual tenders. I note that this information is not included in the current standard forms nor eForms.

I would suggest not modelling the second one, or modelling it something like this:

1. Term: Lot Group Award
Definition: Groups of lots for which tenders can be submitted as a whole. The procuring entity may then compare the tenders submitted for a group of lots with those for individual lots in this group and evaluate which option best fulfills the award criteria.

2. Term: Lot Group Limitations
Combinations of lots for which one tenderer cannot submit tenders. 

(Note: this is a very difficult topic and a very marginal one. I suggest leaving any discussions to the latest possible stage.)

**Comment by ec-mcs** [comment]
I would vote for Jachym's suggestion:
Definition: How lots can be combined when submitting tenders in a public procurement procedure.

The reason is that "How" can mean any kind of combination or even "no combination". 
I do not understand why the term is "Tender Type" when the description is about lots.
"Lot combination" would seem more logical for me.

**Comment by eprocurementontology** [comment]
Combination Lot has been removed as it is not needed in the eNotification phase
