### ISSUE TITLE
GLOSSARY - CPV

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#106]
Replace 

Definition: Common Procurement Vocabulary, which is a classification system for public procurement aimed at standardising the references used by buyers to describe procurement contracts.

By

Definition: The CPV establishes a single classification system for public procurement aimed at standardising the references used by procuring  entities to describe the purpose of procurement contracts and procurement projects.

May need to replace procurement projects by procurement procedure

WG group approval 25/05/2018

**Comment by muricna** [comment]
May need also need to replact procurement contracts by contracts.

Not sure that we use procurement contracts elsewhere

**Comment by eprocurementontology** [comment]
WG approval 25/05/2018

Term: Common Procurement Vocabulary (CPV)
Definition: The CPV establishes a single classification system for public procurement aimed at standardising the references used by procuring  entities to describe the purpose of procurement contracts and procurement projects.

Additional information/WG discussion points: May need to change procurment project to procurement procedure.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
Looking at the [contract.jpg](https://raw.githubusercontent.com/eprocurementontology/eprocurementontology/master/v2.0.0/03_Analysis%20and%20design/EA-Conceptual%20Model/img/Contract.jpg) data model, I don't see the CPV linked to procurement contracts. This is in line with what I'd expect: a project/lot has a CPV code, but a contract is only awarded for a specific lot. As such, I'd suggest removing "contract" from the definition of CPV.  

More generally, I'm not sure whether these types of relationships should be in a definition. I would suggest simply:

> A standardised classification of what can be bought.  


Can you reopen please?

**Comment by eprocurementontology** [comment]
Also with our definition of procurement project that needs to be revisited, the definition will have to be reviewed.

**Comment by idolum** [comment]
I agree with @JachymHercher As the maintainer of CPV itself state that CPV is intended to "[describe the subject of procurement contracts](https://simap.ted.europa.eu/cpv)", contract and not the contract itself.

The proposed definition

 > A standardised classification of what can be bought.

might be useful, but I am not sure, if it is to simple. And if other areas of the e-procurement domain are included in the e-procurement ontology, other classification systems will be relevant as well. Maybe it is better to coin the concept of classification system and consider CPV just as one instance of a classification system.

Just for information, the CWA 15294:2005 (Dictionary  of  terminology  for  product  classification  and  description), defines a classification system as "...a  classification  system  for  the  grouping  of  products  into  subject  fields."

**Comment by JachymHercher** [comment]
I agree - we should definitely define a general classification and have CPV as only one of the instances/codelist values. This is also the approach taken in eForms, which will allow using multiple classifications (see e.g. https://github.com/eForms/eForms/issues/16).

**Comment by eprocurementontology** [comment]
The cpv is not part of the glossary since it is a recommended controlled vocabulary for the attributes MainClassification and AdditionalClassification in the Purpose Class.  The controlled vocabulary can be found at: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/cpv
