### ISSUE TITLE
GLOSSARY - Community country origin 

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#107]
It was suggested to replace Community country origin by Provenance and to remove services and to discuss with JH.

WG Decision 25/05/2014

**Comment by muricna** [comment]
JH has explained that services still have to be covered - this is a necessary element for GPA.

After discussion it would seem that the Community is not necessary see: Annex XII (point 17) of 2014/25/EU 

We should stick to the terms in the directive

**Comment by eprocurementontology** [comment]
Item hasCountryOfOrigin

CountryOfOrigin
Definition: The source country of the product or service.

Additional Information:

The country of origin can be provided by  the buyer as a requirement or by the tenderer information of the item to be provided.

WG Approval 07/01/2020
