### ISSUE TITLE
GLOSSARY - Contract Modification

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#108]
New term

Term: Contract Modification
Definition: Modification of a contract/concession  during during its term.

Modification of the contract may entail the need for the launching of a new procurement procedure (eg  if the amended conditions would have had an influence on the outcome of the initial procedure)

WG Approval 18/05/2018

**Comment by muricna** [comment]
Although this term was added when going through the types of notices, it should be noted in terms of notices the modification notice (form 20) is treated as a contract award notice

**Comment by muricna** [comment]
Definition: Modification of a contract during its term.
WG approval 01/06/2018

**Comment by JachymHercher** [comment]
I'm not sure what "during its term" means or adds - I would argue you cannot modify a contract "after its term" (nor "before its term). I would suggest removing it.

**Comment by muricna** [comment]
During its term is how it is stated in the Standard form, I think it helps differentiate from corrigenda

**Comment by JachymHercher** [comment]
Yes, it's used that way in the directives as well. Nevertheless, I've checked with our lawyer involved in the negotiation of the directives and we weren't really able to find any meaning to the expression. (The best we have is that it emphasizes the fact that we're not talking about changing a draft contract before a signature, but that's really not a huge point...) Thus, I do think it should be dropped, it's just legal jargon. (The colleague also confirmed that when they discuss such issues, they just say "contract modifications".)

Concerning corrigenda vs. modifications, I don't think it's linked. Corrigenda correct notices; modifications are about changes to the actual real contract. They may look similar on TED, but they are very different animals.

**Comment by eprocurementontology** [comment]
WG approval 01/06/2018

Term: Contract modification
Definition: Modification of a contract during its term.

Additional information/WG discussion points: Contract modification notices are treated as Contract award notices

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
My comment above hasn't been reacted to - may I ask for a reply or reopening? Thanks.

**Comment by muricna** [comment]
I understand your point.
I would suggest further changing the definition so as to be coherent in not reusing words in the definition that exist in the terms unless they are terms in themselves in the glossary. Any suggestions welcome here or to be discussed in future glossary meeting when we address the conceptual model:

Suggestion:
Term: Contract modification
Definition: Change of terms of a contract.

**Comment by JachymHercher** [comment]
Building on your definition above, we could just call it "Change of contract".

**Comment by muricna** [comment]
To me change of contract sounds like we stop using one contract and use another

**Comment by ec-mcs** [comment]
How about "Update of contract"?

**Comment by muricna** [comment]
I still prefer "Change of terms of a contract".  There is an agreement "avenant" between the contractual parties and I do not think this is reflected in "Update of contract"

**Comment by JachymHercher** [comment]
Why I wanted to get rid of "terms" is because "terms" is something that you use in other contexts in the ontology, if I'm not mistaken. By saying "contract terms", you are implying that a contract has terms. However, while true colloquially, I don't think that's true in eNotification - in notices, just lots or procedures have terms, no? 

(BTW: I still stick with my older point that we shouldn't be looking for badly fitting synonyms, because it's not helping anything. We should simply call it "Modification of a contract.")

**Comment by muricna** [comment]
Maybe it is a question of prepositions again.  Maybe "Change of terms in the contract"

**Comment by JachymHercher** [comment]
I don't think so - I'm afraid of using the word "terms" in this context. (Perhaps it will be easier to sort this out once terms / tendering terms are defined.)

**Comment by muricna** [comment]
To be in line with eForms the term is kept as contract modification notice
