### ISSUE TITLE
Glossary - Contract Notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#109]
New term: Contract Notice
Definition: An announcement of the launch of a procurement procedure by a procuring entity.

WG approval 18/05/2018

**Comment by JachymHercher** [comment]
Here, we say "by a procuring entity" and don't say "public", in #90 the other way around. I would suggest doing it the same in both? (Probably by not using either of the words.) 

The definition of call for competition and contract notice seems identical. That should be avoided, no? Shouldn't a call for competition rather be called "A launch of the procurement procedure" (or something else totally, see #90) and then the notice would just refer to the cfc, e.g. "A public announcement of a call for competition"? 

(In that case, a PIN CFC could be a "A simplified and long-term public announcement of a call for competition.")

**Comment by eprocurementontology** [comment]
Align with EU Vocabularies:

Contract Notice
Definition: Announcement of a call for competition concerning contracts or concessions.

In EU Vocabularies this is the definition of the contract or concession notice - standard regime the ontology however separates the legal regime already within the Procedure class with the attribute hasLegalRegime: code
This is an epo code and we need to officially create this code.

**Comment by andreea-pasare** [comment]
In ePO 3.0.1 the definition for a Contract Notice is the following:

_An announcement of the launch of a procurement procedure by a procuring entity._
_(WG approval 18/05/2018)_
