### ISSUE TITLE
Analyzing e-procurement procedures 

### ISSUE THREAD

**Issue by jfsoro** [OP-TED/ePO#11]
|Element|Description|
|---|---|
| Title | Analyzing e-procurement procedures |
| Category | Transparency and monitoring |
| Description | The information on how contracting authorities use the procurement procedures permits to know whether they are used properly and to identify the possible shortcomings of the legal design.|
| Actors | Parliament, Authorities, Academia, Auditors- regulators, Contracting authorities |
| Final recipients | Contracting authorities, Economic  operators, Citizens |
| Preconditions | |
| Flow | The user do some request like following: <ol><li> Count of contracts and budget volume in percentage of contracts awarded by each of the procedures provided for in the legislation. </li><li>Count of contracts modifications and amount in percentage of these modifications in relation with the awarded/evaluated and modified budget, and which other conditions are modified compared to the evaluated/awarded conditions (for example completion date of the contract) </li><li>List of steps taken by a contract. </li><li> Types of award criteria used in relation with the contract type (works, supplies, etc.) or the contract object. </li></ol>|
| Comments | When the new Spanish law transposing Directive 2014/24/EU be approved, PPROC have to be adapted to the new set of procedures. Also will became compulsory the contract modification notice (nowadays is perceptive only in some autonomous communities).|

**Comment by gretamolnar** [comment]
I would like to add authorities too as actors to the 'Actors' element, and to add another point to the 'Flow' element: 2. Count of contracts modifications and amount in percentage of these modifications in relation with the awarded/evaluated and modified budget, and which other conditions are modified compared to the evaluated/awarded conditions (for example completion date of the contract)

**Comment by ocorcho** [comment]
Some examples of how this type of open data is being used in Zaragoza (not going yet into as much depth as the use case proposed by @jfsoro )

https://www.zaragoza.es/ciudad/gestionmunicipal/contratos/indicadores.htm (sorry, texts in Spanish). All the values that are generated are extracted from SPARQL queries into the SPARQL endpoint of Zaragoza.

**Comment by sembu-eproc** [comment]
Dear Oscar,

Many thanks for your contribution and for this "Use Case". I think it reflects perfectly the type of situations we'd like to approach in this ePO v2.0.0 development phase. Your  context of work with the municipalities is indeed a source of relevant user stories that we should take into account for sure and hope it will contribute and helpy you in your own developments. Thank you for mentioning this Issue #11 during the meeting in the chatbox.

**Comment by eprocurementontology** [comment]
Add to use case
