### ISSUE TITLE
GLOSSARY - Modification Notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#110]
New Term: Modification Notice
Definition: An announcement of the modification of a contract/concession  during during its term by a procuring entity.

WG approval: 18/05/2018

**Comment by JachymHercher** [comment]
As mentioned in #108, I think "during its term" should be removed. Also, "contract/concession" should be replaced by "contract".

**Comment by AchillesDougalis** [comment]
In the ePO 4.0.0,  epo-not:ContractModificationNotice exists with the following definition: "An announcement of the Modification Of a Contract/Concession during its term by a Procuring Entity."
