### ISSUE TITLE
Glossary - Value

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#111]
New Term: Value

Definition still to be determined  See also #55 

WG Decision25/05/2018

**Comment by andreea-pasare** [comment]
In ePO 3.0.1 we have the epo:MonetaryValue concept with the following definition:

_A number of monetary units specified using a given unit of currency.
WG approval 13/04/2021_

![image](https://user-images.githubusercontent.com/88081600/194836851-e3985ee7-4521-4041-8ee6-8592fc149495.png)
