### ISSUE TITLE
GLOSSARY - Contact

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#116]
Term: Contact
Definition: The person or department that provides the means for communication within an organisation.

WG approval 01/06/2018

**Comment by idolum** [comment]
Just a question: The definitions means that "Contact" is context-free, i.e., can be used everywhere where contact information is considered useful (contact of a Buyer, Seller or any other party)?

**Comment by muricna** [comment]
Yes

**Comment by eprocurementontology** [comment]
WG approval 01/06/2018

Term: Contact
Definition: The person or department that provides the means for communication within an organisation.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
