### ISSUE TITLE
GLOSSARY - Contract Nature - Procurement type

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#117]
Change of term and definition after a long discussion of how best describe the works, supplies and services,  whilst respecting the ISO norm in not reusing the terms in the definitions.

New term - Procurement type
Definition - The nature of what is acquired.

Working group decision 01/06/2018

**Comment by eprocurementontology** [comment]
The ontology has aligned with EU Vocabularies and uses Contract Nature
