### ISSUE TITLE
GLOSSARY - Contract publication date - Estimated publication date

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#118]
It was decided that a generic term that could be reused in other parts of the ontology should be used:

New term: Estimated publication date
Definition: The foreseen date that a record will be made publically available

WG Decision 01/06/2018

**Comment by eprocurementontology** [comment]
WG approval 01/06/2018

Term: Estimated Publication Date
Definition: The foreseen date that a record will be made publically available.

Additional information/WG discussion points: Splitting into date and estimated date to genralise would be too much.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
In other places (e.g. #103, #119) you make a distinction between record and document. Shouldn't this definition also refer to both?

**Comment by muricna** [comment]
This term was being applied to notices which are records, however it could be worth considering whether we should expand this definition.

**Comment by muricna** [comment]
Estimated Publication Date is part of the process and is therefore not part of the ontology that currently has the scope of covering data.
