### ISSUE TITLE
GLOSSARY - Record

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#119]
It was decided that after the last two meetings we need to really describe the difference between record and document ie the fact that the original version of something cannot be deleted.

Enric is to come up with something .

Provisisonally

Term: Record
Definition: A document that is finalised and cannot be altered. 

WG decision 01/06/2018

**Comment by timgdavies** [comment]
It may be worth noting in OCDS we use 'Record' to refer to the collection of all published data about a contracting process. We set this against a 'release' of data, which we say should, ideally, be immutable (representing data as it was known at a particular point in time).

**Comment by muricna** [comment]
Record is neither a class nor a property of the ontology so it is considered out of scope.
