### ISSUE TITLE
GLOSSARY - Criterion Property

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#122]
#### Current:

* Term: Criterion Property

* Definition: (None)

#### New:

* Term: Criterion Property

* Definition: A Criterion Property defines the requirement and the question that needs to be answered. 

#### Reason:
We hadn't any definition for this until now!

**Comment by muricna** [comment]
WG approval 8/6/2018

**Comment by eprocurementontology** [comment]
WG approval 22/6/2018

Term: Criterion Property
Definition: Specific information needed to measure a criterion.

Additional information/WG discussion points: 
This is a question that usually goes hand in hand with a specific requirement.  For example which follows on from the example given for criterion: 
Question: Amount?
Requirement: The text explaining what the procuring enitit is interested in measuring ie minimum turnover.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
