### ISSUE TITLE
GLOSSARY - Criterion Requirement

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#123]
### New term!

* Term: Criterion Requirement

* Definition: a concrete condition that allows an entity to do something or to be suitable for something.

Additional information:

Examples, a specific type of experience, a threshold for which a value needs to be provided, a qualification, a quality, etc.

In the context of procurement criteria, a requirement can be seen as a constraint issued by the Procuring Entity that the Tenderer needs to comply with or the Tender needs to adjust to; e.g. an economic threshold for which the Tenderer  needs to provide in a Turnover for the last three fiscal years.

WG approval: 20180608

**Comment by muricna** [comment]
I have removed Criterion from the term as it is not in the heading of the issue and I think we agreed to generalise if not please change.

**Comment by paulakeen** [comment]
We said that we need Criterion in front of Requirement, because in other phases of the eProcurement value chain we may fing Requirements that are not related to criteria. Similarly this will happen with Criterion Question.

I add it to the title of the issue, if you don't mind.

**Comment by muricna** [comment]
Term: Criterion Requirement
Definition: A concrete condition that an entity needs to comply with in order to be allowed to do something.

Reason previous term too generic
We need to cover multiple domains not just procurement because this is an update of the ISA core criterion vocabulary and should be sent as a change request when finalised to ISA it would also be useful for eCertis

WG Approval 15/06/2018

**Comment by paulakeen** [comment]
The discussion on how to define Criterion Property Response revealed that we needed to look at how the Conceptual Data Model was designed, which led to reanalysing the underlying concepts and how they should be termed and represented for a better understanding.

(15-06-2018)

Please see the resulting conceptual diagram here:
![criterion_20180615_afterglossarydiscussion](https://user-images.githubusercontent.com/16134316/41461926-76f29d12-7091-11e8-9c6f-47bd8ddf9205.png)

**Comment by paulakeen** [comment]
Further discusssion on this topic has led to this other Diagram:

![criterion_20180615_afterglossarydiscussion3](https://user-images.githubusercontent.com/16134316/41463496-fcfe692c-7096-11e8-8d43-b4e9b321c6d1.png)

**Comment by JachymHercher** [comment]
Hello, a few questions:

1. What does the Fulfilled Indicator attribute mean when the criterion is an award criterion? 
2. Does the CM above cover the information that "Bid ABC received 30 points for criterion X"? Would that be in the Criterion Property Datum box? 
3. What is CRITERION.AWARD.MIXED?

**Comment by paulakeen** [comment]
My opinion on Jachym's questions:

0. Bear in mind that this is the generic Core Criterion vocabulary, which is business-agnostic (i.e. it is not the "eProcurement Criterion Vocabulary");

1. The fulfilled Indicator should be removed. It was introduced in the ESPD data model to keep whether all the responses or a reasonable amount of responses fulfill what is being described in the Criterion. But this is not very sensible because:

- This happens at the evaluation and award time, not at the eNotification or eSubmission time; and
- There's no need to keep the "result" of the exclusion or selection evaluation as these data can be "calculated" based on the confrontation of what was (required + asked) against what has been actually responded and proved (by means of evidences); and (b) at least in the case of the award criteria, no answer is expected, it's just about the statement of the criterion by the authority.

2. The model could hold the datum "Bid ABC received 30 points for criterion X" as one Criterion Property Datum associated to a Criterion Property, but this would imply trying to reuse entities that were designed to express a different knowledge: the sentence "Bid ABC received 30 points for criterion X" would resulf from the evaluation, not from a requirement or a question (the definition of the concept "Criterion" would fall short/fail). Your suggestion is however good food-for-thought as we didn't took this need into account while modelling the ePO and, even if the scope is eNotification and eAccess, now could be the right moment of how to model it (I guess it would be a new Class related to both the Evaluation Result and the Criterion classes).

3. I don't now, and we do not like it. We took it from the current TED XML Code List. We guess it is the combination of the two first codes of the list, but it's just our speculation.

I hope this helps

**Comment by paulakeen** [comment]
After reflection I think that what Natalie was proposing of merging the Response into one class is quite sensible. Please see this other proposal, which simplifies the model and would cater for all the needs of the ontology (and therefore of the ESPD, too). See my reasoning beneath the figure:

![criterion_20180615_afterglossarydiscussion4](https://user-images.githubusercontent.com/16134316/41472504-ebccf482-70b6-11e8-8ea9-4fcdfe7915f6.png)

**Reasoning**

1. The need of having a "Response" and a collection of 1 or more values in separated classes (that is the actual response) emerged from a specific requirement by some Member States that, while modelling the ESPD Response suggested that embedding the whole ESPD Request criteria inside the ESPD Response document was not truly (nor legally) necessary (although it is currently a [business requirement](https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#vii-1-business-requirements-specification) expressed in the ESPD specification documentation; expressed also the [ESPDint Bis document](http://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.0#BIS41-ESPDV2.0-ESPDResponsetransaction(Trdm092)) requirements).

In a world of linked data (and once-only-principle-enabled), what these Member States suggested makes perfect sense: the ESPD Response may refer to an official, and electronically signed if the need is, ESPD Request where the criteria are perfectly described and universally+uniquelly identified.

The data model proposed in the figure above would cater for both scenarios, the one embedding the criteria or the one referring to criteria that live in another e-Domain (e.g. e-Certis, the Web of the Data, or a publicly available system owned by the Procuring Entity, a Pre-Qualification System, a Service Provider, etc.).

In respect of the previous versions it would improve these other aspects:

1. It aligns to the definitions of the ePO Glossary;
2. The semantics rely on the properties, not on the classes, which is a design good practice: 

(i) a Criterion Property may express a specific requirement consisting in the provision of one or more data. For example:
- Criterion Property Description (behaving as a requirement): "For the Fiscal Year 2017, the minimum amount (i.e. the economic value) provided in case of yearly general turnover must be greater than: "
- Criterion Property Datum: 1,000,000 €;  (an amount, which includes the economic value and the currency)

ii) a Criterion Property can be used to ask a specific question that needs to be answered with a datum. For example:

Criterion Property Description (behaving as a question); "Which was your turnover (Fiscal Year) 2017?"
-Criterion Property Datun: 2,534,613,21 € (an amount provided by the Economic Operator in the ESPD Response. Notice that it fulfills the requirement expressed above, in point (i)).

3. The means to distinguish whether a Criterion Property is a specific requirement or a question is the use of the property:
- If the eOP triple is ":CriterionProperty :expressesRequirement :CriterionPropertyDatum" then it is a requirement;
- Otherwise the triple would read ":CriterionProperty :asksForData :CriterionPropertyData". In this situation the "CriterionPropertyData" contains the value or tex that is the response to the question.

4. One value or text in an individual (instance) of the CriterionPropertyData class points to one, and only one individual of the class CriterionProperty: Given a CriterionPropertyData, the functional properties "refinesRequirement" and "respondsQuestion" make possible the reach a specific CriterionProperty that can be located anywhere, e.g. in an ESPD Request kept in a national database, in Service Provider Repository, etc., This way the 2 possibilities mentioned above, the embedding of the criteria or its referencing to a remote location, become possible.

**Comment by ec-mcs** [comment]
With the ESPD we tried as much as possible to have structured data. Something like "Which was your turnover (Fiscal Year) 2017?" is not really structured but requires someone to read it manually. Is this intended in the ontology?
https://github.com/ESPD/ESPD-EDM/wiki/1.-General-Turnover

If the response and the requirement is one class would this mean:
Property question (like "turnover 2017") -> Property answer ("3 MEUR")
So one property question would have one property answer?

How would this be possible?
Question property "Number of references": 5
Question property "In the area of": "Building bridges"
Answer properties "Description", "Total amount", "Activity of the supplier", "Specific amount", "Contact references (multiple)"

**Comment by paulakeen** [comment]
The ePOP copies and slightly improves the ESPD Criterion data model. The ePO proposal does not merges the requirement and the answer but merges the Response to its value(s). 

The model is slightly simpler and is fully compliant with the ESPD needs. I can provide examples in Turtle (TTL).

**Comment by timgdavies** [comment]
This may not be an issue for the context in which the discussion here is taking place (apologies for missing the call), but I wanted to note that we hit some challenges in OCDS in trying to use EPSD / CCCEV based modelling for **both** eligibility criteria and the particular factors that would be evaluated as part of bid evaluation in cases of Most Economically Advantageous Tender (driven by requests from the Open Procurement API team to have [a modelling to map their feature concept onto](http://api-docs.openprocurement.org/en/latest/meat.html)).

As I noticed the Criterion Taxonomy in the diagram has entries both for **eligibility** and **award criteria** I wanted to check that @JachymHercher's [note of caution when we sought to use CCCEV modelling for award-related criteria](https://github.com/open-contracting/standard/issues/223#issuecomment-292988204) does not also apply here?

**Comment by eprocurementontology** [comment]
DECISION WG 22/06/2018

This is no longer required because it is defined in the ded of the ontology as a predicate.
