### ISSUE TITLE
GLOSSARY - Criterion Question

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#124]
### New Term!

* Term: Criterion Question

* Definition: Wording that seeks information through a response.

Additional Information: 
Examples of questions could be: supply your turnover for the past three fiscal years. Responses for this question could be: 

1,567,123€ in 2016-2017,
1,000,000€ in 2015-2016, and
923,991€ in 2014-2015.

#### Reason:
Need to clarify what a Criterion Property is. See definition for Criterion Property.

WG approval: 20180608

**Comment by muricna** [comment]
This term no longer exists in the ontology it concerns the espd which is to be tackled in the future
