### ISSUE TITLE
GLOSSARY - Criterion Value

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#128]
#### Current: Criterion Value

* Term:

* Definition:

#### New:

* Term: **Criterion Response Value**

* Definition:

**Comment by muricna** [comment]
This term no longer exists.  There is now 

1.  SelectionCriterion WeightValue and AwardCriterion WeightValue.
2. SelectionCriterion WeightValueType and AwardCriterion WeightValueType.
