### ISSUE TITLE
Few small problems with the Wiki

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#133]
Few small comments on https://github.com/eprocurementontology/eprocurementontology/wiki:
- In the Glossary tab in the top right, the link to the ePO Glossary (spread-sheet) ( https://github.com/eprocurementontology/eprocurementontology/blob/master/v2.0.0/02_IR_DED/eProcurement_glossary_v150.xlsx) doesn't work. 
- In the Conceptual Model tab on the right, it is not clear what version of the CM is available in "CM - Images" and "CM - XMI file". 
- At https://github.com/eprocurementontology/eprocurementontology/tree/master/v2.0.0/03_Analysis%20and%20design/EA-Conceptual%20Model/img. 
    - I would suggest renaming "Legend.png" to something like "_Legend" or "1_Legend" so that it is first in the list of files and it is clear that it is a different type of information than the other images.
    - Please consider providing more information in the "Legend.png" (or perhaps exchange it for a paragraph of text?). Maybe it could be easily explained what is the difference between "elemenet associations", "inverse axioms", "dependencies". Or perhaps you could include a link to a more detailed website explaning this?

**Comment by eprocurementontology** [comment]
Dear Jachym, thank you for your comments. 

All of them have been taken into account and have already been implemented. You can check them in:

- the [wiki](https://github.com/eprocurementontology/eprocurementontology/wiki) page;
- the [Glossary](https://github.com/eprocurementontology/eprocurementontology/blob/master/v2.0.0/02_IR_DED/eProcurement_glossary.xlsx) page, and
- the [CM](https://github.com/eprocurementontology/eprocurementontology/wiki/Conceptual-Model) page and "[img](https://github.com/eprocurementontology/eprocurementontology/tree/master/v2.0.0/03_Analysis%20and%20design/EA-Conceptual%20Model/img)" folder.

Kind regards.

**Comment by JachymHercher** [comment]
I'm not sure the last one was really taken into account - the legend still says "inverse axiom" etc. without explaining what it means. This is linked to  #142.

**Comment by paulakeen** [comment]
The reviewed version 2.0.1 will not use this notation anymore, as agreed by the WG. Instead we'll use arcs with two arrows so the notion of "inverse" is made conspicuous although will be also explained in the new version of the technical documentation, due asap.
