### ISSUE TITLE
Glossary Term eCatalogue Indicator

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#135]
This term should probably appear in the Contract Terms of the Procurement terms Model

**Comment by jseguraf** [comment]
This eCatalogue Indicator does not exist in the Model. A discussion is needed in order to know where we should add it.

**Comment by paulakeen** [comment]
The eCatalogue indicator is no longer necessary because in the Procurement Terms diagram, class Submission Terms, there is a property named "has eCatalogue Permissions" used to indicate whether the eCatalogue is "allowed", "not-allowed" or "required".
