### ISSUE TITLE
Conceptual model : Exclusion criterion

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#136]
The class exclusion ground should be renamed exclsuion criterion to reflect the glossary meeting of 01/08/2018

**Comment by JachymHercher** [comment]
This is a nice illustration of a general point: to what extent do we want to stick with the legal terminology even though it doesn't seem to us, non-lawyers, sensible. Given that lawyers are also pedantic with words and, sometimes, choose them carefully... :) 

In this case, given how established "Exclusion Grounds" are (e.g. in the name of the article itself, 2014/24/EU Art. 57), I would tend to think we should stick with the legal term... 

(Also, perhaps there is some "deeper" reasoning behind "grounds" vs. "criterion". For example, maybe criteria can be set by buyers, while grounds must be set by legislation?)

**Comment by muricna** [comment]
The reason for using criterion is to resuse the same model for all that reusses the Core Criterion and Core Evidence Vocabulary (CCCEV)

**Comment by JachymHercher** [comment]
I understand. However, I don't think it addresses the shortcomings mentioned above:
- Inconsistency with the legal terminology.
- Actual differences between "criterion" and "grounds". For example, in the CM, you can say that "contracting entity sets the selection criteria" but you cannot say that "contracting entity sets the exclusion grounds".

**Comment by muricna** [comment]
Ok
The model as captured in the last meeting has exclusion ground, I would suggest correcting this to exclusion grounds.
Unless anyone has any objections.
