### ISSUE TITLE
Glossary - Lot

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#139]
Following-up today's discussion at the webinar.

Current definition: 

> One of the parts of a procurement project that is being subdivided to allow the buyer to award different lots to different economic operators under different contracts.

Assuming that a procurement procedure is defined as mentioned in https://github.com/eprocurementontology/eprocurementontology/issues/113#issuecomment-393926100), 
>(A series of activities aiming to conclude one or more public contracts.)

I would suggest a definition of:

>A series of activities aiming to conclude all or some public contracts within a procurement procedure.

**Comment by eprocurementontology** [comment]
The problem I see here is that a lot can also be part of a contract
 ie Contract XYZ lot 1 Contract XYZ lot 2
But I am not sure how to glue all this together

**Comment by JachymHercher** [comment]
I wouldn't say lot can be part of a contract, I'd say they are two separate entities with a many to many relationship. I.e. a contract can "stem from" / "be based on" / "concern" ("be for" / "be for items described within") one or more lots; a lot "results in" one or more contracts...

**Comment by eprocurementontology** [comment]
Term: Lot 
Definition:  An   organisational part of a procurement procedure specification allowing the   award of one or more contracts. 
WG approval   07/09/2018 

It was noted that lots can be  divided  on a quantitative basis,   qualitative basis or  for strategic objectives.

**Comment by eprocurementontology** [comment]
The definition does not cover when a lot is part of a contract.

**Comment by JachymHercher** [comment]
See https://github.com/eprocurementontology/eprocurementontology/issues/139#issuecomment-419364082...

**Comment by paulakeen** [comment]
I also see the need for an n-ary relationship between Lot and Contract, and we do not have it in the ePO....we should revisit this subject in the ePO WG.
