### ISSUE TITLE
Comments on the "Specifications of the process and methodology" document (in particular use of "relationships" and "properties")

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#14]
I have read the document d02.01_specification_of_the_process_and_methodology_v0.12_1. Thank you very much for making the overview available. Please find some comments in the Word document uploaded at the end of this post. I apologize for not opening a separate GitHub issue for each comment, but it would take too long. Also, I think most of the comments do not perhaps need to have their own thread for discussion. (If you think otherwise, I would kindly ask the administrators to open the necessary issues based on the comments.) 

Just to highlight the most important comment: I'm new to this area so perhaps I misunderstood a basic feature of the methodology, but I'm not really sure how _relationships_ and _properties_ are being used. They are named as if they should be general (which is, I think, correct), e.g. _hasVAT_, _publishes_. However, the definitions (and domains and ranges) limit the use to only one specific situation. For example, _hasVAT_ is defined as "This property specifies an amount of Value Added Tax charged on an invoice.", which excludes it's use for values of notices, lots, contracts, etc.; _publishes_ is defined as "This property links a contracting authority to a call for tender that it makes available", which excludes publications by contracting entities, review bodies, other types of buyers, etc. and other types of documents, such as corrections, contract awards, modifications, etc.  I would expect the definitions of relationships and properties to be context independent, so that they can be used to describe relationships between many different classes? 

Other comments include comments on terminology (esp. consistency in its use), examples, other existing projects, etc. 

[d02.01_specification_of_the_process_and_methodology_v0.12_1_jh.docx](https://github.com/eprocurementontology/eprocurementontology/files/952041/d02.01_specification_of_the_process_and_methodology_v0.12_1_jh.docx)

**Comment by brechtwyns** [comment]
The comments are taken into account for the next version of the document (updated titles, reworded sections, changed cardinalities in the document, etc.).

- The definitions of classes and properties were updated, ranges and domains are modified where needed.
- For now, we have kept the definitions from the directives where available, but a github issue was created to discuss the sources of definitions: https://github.com/eprocurementontology/eprocurementontology/issues/21
- A github issue was created to discuss whether a relationship is needed between "Contract Award Notice" and "Economic Operator": https://github.com/eprocurementontology/eprocurementontology/issues/20

Regarding the "non-working" links: these are URIs. Not all URIs are resolvable, meaning they do not lead to a web page describing the resource. For the specific instance that you indicated (data.europa.eu/eproc/ontology#CallForTender): this is a URI for the e-procurement ontology that we are developing. As it does not yet exist, the URIs are also not yet created.
