### ISSUE TITLE
Glossary - Procurement

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#140]
Suggested:

Term: Procurement
Definition: Concepts and properties that are common to Lots and Procurement Procedures.

Following our conceptual meeting of 05/09/2018.  This is the suggested term for an abstract class that was previously procurement project.  It was decided that procurement project was not abstract but that a project could overarch several procedures/lots.  This will discussed further on 07/09/2018 any comments on github to these initial ideas would stimulate discussions.

**Comment by muricna** [comment]
In the meeting of 5/09/2018 it was suggested to  add a Usage note" to the ePO Glossary referring to Article 1, Paragraph 2 of the Directive 2014/24/EU.

**Comment by eprocurementontology** [comment]
Term: Procurement
Definition: Concepts and properties that are common to Lots and Procurement Procedures.

WG   07/09/2018 definition agreement. 
Term could be   reviewed in later versions or when abstract classes are more clearly defined.
--

**Comment by guascce** [comment]
Just checking the definition of the Financial rules of EC
a) “procurement” means the acquisition by means of a contract of works, supplies or services and the acquisition or rental of land, existing buildings or other immovable property, by one or more contracting authorities from economic operators chosen by those contracting authorities;
We need not to forget how to make our definition connected to reality.

**Comment by muricna** [comment]
Procurement is not part of the glossary which is automatically created from the classes and properties of the ontology.
