### ISSUE TITLE
Diagram comprehension

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#142]
Following the meeting of 5/09/2018 a clarification of how the conceptual model is to be read needs to be made.  This would mean explaining what inheritence and associations actually mean and how they are reprensented.  That what is inherited is the concepts and not the data that will occupy the concept in a given place.

**Comment by paulakeen** [comment]
This will tackled in the reviewed version of the technical documentation, due asap.

**Comment by AchillesDougalis** [comment]
All this information can now be found [here](https://docs.ted.europa.eu/epo-home/uml2owl_2020.html).
