### ISSUE TITLE
Relation procurement - purpose

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#146]
A relationship between procurement and purpose needs to inserted it was lost when we renamed procurement project procurement

**Comment by jseguraf** [comment]
The "Project Procurement" is indirectly related to purpose since a "Project Procurement" access to the market through a "Procedure" which has an "Overall Purpose".

![image](https://user-images.githubusercontent.com/33545990/59913445-7126b980-9418-11e9-95ca-addf3ffd1df0.png)

**Comment by muricna** [comment]
My understanding is that a project procurement has an overall purpose that can then be covered by several procedures therefore I am not sure that the purpose of the project procurement can be reached via a procedure.  For example in the case of a project procurement for an airport, there could be one procedure for procuring aeroplanes and another for restaurant services.  If the purpose of the restaurant service procedure is taken into consideration you may loose the purpose of the project procurement which is the airport.  There needs to be an overall global purpose what is more at the begining of the project procurement no procedure exists.

**Comment by paulakeen** [comment]
I do agree. Our current definition of "Procurement Project" is "A set of linked procurement activities". I propose though to improve it with additional information to explain the circumstance @muricna points at.

**Comment by muricna** [comment]
At this point there is no use case for having a relationship between the Purpose and ProjectProcurement, the issue can be reopened if there is a use case.
