### ISSUE TITLE
GLOSSARY - Process

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#148]
#### Term:

Process

#### Definition:

"A series of actions or steps taken in order to achieve a particular end."

#### Reason:

1. Jáchym Harcher commented the following: Is this concept supposed to be linked to any process which can happen in procurement, i.e. for example a procurement procedure, submitting a tender, opening a tender, evaluating a tender, counting the number of tenders, filling a notice, etc. or are we trying to describe something a bit more specific?

2. During one discussion about the definition of Procurement Procedure, some participants mentioned the need of clearly disntinguish between process and procedure.

**Comment by muricna** [comment]
The ontology is showing relationships between data and the term is not used in the ontology, therefore there is no need for the term in the glossary.
