### ISSUE TITLE
Rename the attribute NUTS in the class epo:Address

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#152]
In the current ePO Conceptual Data Model, the Class epo:Address (a subclass of org:Site) adds an attribute named NUTS (of type Code). 

An [issue in eForms](https://github.com/eForms/eForms/issues/50) also refers to the fact that NUTS is used as the Business Term. For that issue, @paulakeen  proposes the following:

"If NUTS is compulsory because of the Directives then use it, but name the BT "Country Subdivision", thus in the future you may change the code list whithout changing the label nor its semantics."

**Comment by jseguraf** [comment]
All the attributes NUTS has been renamed by "Country Subdivision Code".
