### ISSUE TITLE
Multi-stage procedures at evaluation time

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#153]
We need to analyse in depth the situation when a procedure is multi-staged when analysing the eEvaluation phase.

Please check the work done in eForms and the discussions held while designing the eNotification and eAccess phases (e.g. recall the discussions around the BT-120 on the "Non negotiation necessary" concept.

(@Jachym, @Cecile, @Natalie, and the rest of the WG)

(This refers to multiple-stage procedures (included two-stage procedures, at least). Open Procedures can be seen as one-stage procedures. In multiple-stage procedure the first stage (or round) is used for the selection of the candidates, whilst the rest of stages is about submitting tenders and warning (or not) about the right of the CA to award without further negotiations. See Article 29(4) of Directive 2014/24/EU).

**Comment by AchillesDougalis** [comment]
See work already done in ePO _core under "framework agreement", and Dynamic Purchase System diagram, when implementing module eEvaluation.
