### ISSUE TITLE
Groups of lots

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#159]
The law allows submitting tenders for "groups of lots" (see e.g. eForms' Group Award (BG-330)). 

This implies that it should be possible to:
- Submit tenders per lot and per "group of lots"
- Associate a set of criteria (definitely award, but probably also selection) with a lot and with a "group of lots"

**Comment by paulakeen** [comment]
Thank you for the input....this tells us that our procurement criterion model could nee also a readjustment. We need to re-analyse it.

**Comment by muricna** [comment]
Can you please provide the reference in the law?

**Comment by JachymHercher** [comment]
Art. 46(3) and Rec. 79 of Directive 2014/24/EU (Rec. 78 is vaguely related)

**Comment by JachymHercher** [comment]
Based on today's discussion: does the ontology's modeling of grouping/combining lots cater for the following use cases? 

1) Single price submitted for the entire group of lots.

This use case can be illustrated by an example given by GROW lawyers during the transposition of the Directives:

> Two homogeneous lots, qualitative aspects "frozen" in the technical specification, award criterion price only: tenderer A offers 100.000 under lot 1, 120.000 for lot 2; tenderer B offers 110 000 for lot 1, 100 000 for lot 2 and adds that the overall price if awarded both lots will be a total of 180.000. The contracting authority will therefore have the following options: 1) award the contract for lot 1 to A, and the one for lot 2 to B (overall price: 100 000 + 100 000= 200 000) or 2) award one single contract for both lots to B, total price 180 000. Most advantageous option: 2)

2) "Comparative assessment" between tenders per lot and tenders per group of lots.

This provision is rarely used, so it's not quite clear whether we know all the ways a "comparative assessment" can be done. However, one way definitely is to calculate award criteria points for lots individually, award criteria points for groups of lots, and then compare them. In such a case, it is necessary to describe the award criteria for a group of lots.
