### ISSUE TITLE
BT-754 (Accessibility); Data Type; Proposal of a code list

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#163]
In ePO we see BT-754 as one criterion, and as a matter of fact in the eForms BT-754"Description" column they are described as such. 

As they are not selection criteria, nor exclusion or award, we tend to treat these as "other participation criteria" or even very specifically "criterion" of type "accessibility" that contains one of the following requirements and, optionally, a free text field for the motivation for its inclusion and exclusion:

1. Either "Accessibility criteria for persons with disabilities are included", or
2. "Accessibility criteria for persons with disabilities are not included because the procurement is not intended for use by natural persons."

in eForms, these two options cum the free text for the motivation would be mapped to BT-754 using a code list like this one:

1. Accessibility criteria for persons with   disabilities are included.
2. Accessibility criteria for persons with   disabilities are not included because the procurement is not intended for use   by natural persons.
3. Accessibility criteria for persons with   disabilities are not included with the following justification.

and the text used in case of selecting code 3 would go in BT-755

This code list needs further discussion, though.

**Comment by JachymHercher** [comment]
Watch out: accessibility is not a participation criterion. It is not about the company ("only company X can participate") but about the matter (/purpose) of the contract, i.e. something that would typically be specified in the procurement documents ("the house must be wheelchair accessible").

**Comment by muricna** [comment]
Accessibility has been associated with the specifications.

WG Decision 11/04/2019
