### ISSUE TITLE
Codelist; economic-operator-size; No single code for SME?

### ISSUE THREAD

**Issue by jpmckinney** [OP-TED/ePO#164]
The codelist has micro, small, medium, large, which makes sense from a theoretical perspective. However, in practice, what matters in many policies is whether a business is an SME; as such, in practice, many systems track whether a business is an SME without distinguishing between whether it is a small SME or a medium SME. Such systems can't use the current codelist, which is more granular.

Therefore, I recommend adding an 'sme' code, which aligns with the level of granularity that most policies care about.

We might consider removing the 'small' and 'medium' codes, unless we have evidence that existing systems or policies make this distinction.

**Comment by JachymHercher** [comment]
Several submissions at https://ec.europa.eu/info/law/better-regulation/initiatives/ares-2019-797630_en make the same point. 

For eForms, I would agree with @jpmckinney, i.e. the codelist should become a taxonomy along the lines of:

- Micro, small, or medium
    - Micro
    - Small
    - Medium
- Large

That way, in each system, they can choose which level of detail they are interested in (e.g. depending on the interconnections with other national databases).

**Comment by paulakeen** [comment]
Thank you for the input, we'll take this into consideration while discussing the code lists in ePO.
