### ISSUE TITLE
Award criterion is not associated to anything in the lots diagram

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#166]
Please check earlier versions, update and correct

**Comment by eprocurementontology** [comment]
Award criterion is not associated to anything because Procurement Criterion is associated to Lot and this class inherits from "Award Criterion". Therefore, Award Criterion is indirectly connected to Lot.

**Comment by muricna** [comment]
In the Procurement criterion diagram the "Award Criterion" is used to award "the lot".  The lot is not directly associated to the procurement criterion as described above. I think the Lot diagram needs to show the award criterion.

**Comment by jseguraf** [comment]
The model has been updated accordingly.
