### ISSUE TITLE
Class lot - attribute applies to lot

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#168]
In the class lot there is a text "applies to lot" please check where this comes from:

<img width="168" alt="Capture" src="https://user-images.githubusercontent.com/26460487/54981736-5d022600-4fa9-11e9-9bf2-e6a956958842.PNG">

**Comment by paulakeen** [comment]
It comes from CriterionProperty. The explanation is that, inside a Criterion, the Contracting Authority can establish requirements that apply to one or more Lots.

![image](https://user-images.githubusercontent.com/16134316/55062795-f51a1100-5076-11e9-916e-6bed94f8cfe7.png)

**Comment by eprocurementontology** [comment]
It was fixed during the update of the EA file.
