### ISSUE TITLE
Glossary - Candidate short list

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#174]
The class "Candidate short list" needs to be looked into.
WG discussion 08/01/2019

**Comment by muricna** [comment]
Candidate short list is not included in version 2.0.1 as it is not needed in the current standard forms.  It was introduced in version 2.0.2 but we need to see if it needs to be treated differently in the reification maybe the winner needs to be given a rank.

**Comment by andreea-pasare** [comment]
The role epo:Candidate has been included to the future ePO release with the following definition:

_The role of an agent that has sought an invitation or has been invited to take part in a restricted procedure, in a competitive procedure with negotiation, in a negotiated procedure without prior publication, in a competitive dialogue or in an innovation partnership._
