### ISSUE TITLE
Classes absent from ePO Overview

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#176]
The following classes are absent from the model "ePO Overview" and need to be included:

1) award criterion evaluation dimension
2) award terms
3) contract template
4) corrigendum notice
5) draft CV
6) eAccess terms
7) evaluation detail
8) evaluator
9) framework agreement procedure terms
10) framework agreement terms
11) green procurement
112) innovative procurement
13) mark
14) official language
15) opening terms
16) reserved procurement requirement
17) security clearance terms
18) social procurement
19) strategic procurement
20) submission terms
21) tender evaluation
22) unofficial language

WG discussion
08/01/2019

**Comment by jseguraf** [comment]
The overview has been modified and updated. Moreover, some old classes have been removed.
