### ISSUE TITLE
ESPD documents & criteria

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#177]
There will need to be an aggregation between the ESPD documents and the selection and exclusion criteria. "The ESPD could be linked to datum: ES to look into ESPD request, response and criteria for next Tuesday 15/01/2019."

WG discussion 08/01/2019

**Comment by AchillesDougalis** [comment]
The ESPD request has been dealt with in ePO 4.0.0 rc1 and the ESPD response is currently being treated.
