### ISSUE TITLE
Predicates: Contract-Procedure and Procedure-Contract

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#182]
There is a bidirectional predicate between "Contract" and "Procedure" (is concluded by/concludes) and a unidirectional predicate from "Procedure" to "Contract" (envisages).

WG discussion 09/01/2018

**Comment by JachymHercher** [comment]
I would suggest replacing "envisages" with "leads to". 

First, I'm doubtful "envisages" is grammatically correct (looking at https://dictionary.cambridge.org/dictionary/english/envisage, https://www.merriam-webster.com/dictionary/envisage, etc. I don't think a thing can "envisage" another thing, I think you need a mind to be able to envisage). Second, even if possible, I think "envisage" is too general.

**Comment by JachymHercher** [comment]
Please do not forget to re-open this issue.

**Comment by muricna** [comment]
I have reopened this for discussion.

Envisage was chosen over leads as not all procedures lead to a contract.  Maybe a compromise between the two words needs to be found "enables"?

**Comment by JachymHercher** [comment]
Not all procedures leading to a contract is a question of cardinality rather than predicate, no?

**Comment by jseguraf** [comment]
The "envisages" predicate has been replaced by "leads To".
