### ISSUE TITLE
Class - create class "CV template"

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#184]
Create class "CV template" in the "Documents" module.

WG discussion 09/01/2018

**Comment by eprocurementontology** [comment]
A "Draft CV" class was created within the "Documents" diagram. Therefore, this issue can be closed.

**Comment by JachymHercher** [comment]
What is the definition of this term? I thought "CV template" was a template provided by the buyer which would then be used (/filled in) by the company. "Draft CV" sounds like something else than a template...

**Comment by muricna** [comment]
This class has been removed as it is not needed in eNotification and will be reinstigated if necessary when a use case arises.
