### ISSUE TITLE
Remove link between eAuction and Framework agreement

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#188]
During a discussion on the differences between "Framework agreement", "eAuction" and "Dynamic Purchase System", we decided that "eAuction" does not require a link to "Framework agreement" as they are indirectly linked via "Procedure" and "Contract".
Please remove the link. 

WG decision 09/01/2018

**Comment by muricna** [comment]
The summary of the meeting of 5 March seems to overturn this decision.  It is to be verified as to whether the link between DPS and eAuction with FA is possible without the predicates.

**Comment by jseguraf** [comment]
The "Framework Agreement" is linked to eAuction through the predicate "uses eAuction". Moreover, the "DPS" is also linked to eAuction through the "uses eAuction" predicate.

**Comment by JachymHercher** [comment]
This seems a bit strange. 
1) A procedure/lot which does not involve DPS nor framework agreement could also use an eAuction. Is there a "uses eAuction" predicate in such cases? 
2) If any type of procedure/lot can "use eAuction", isn't it simpler modelling to just have one predicate between procedure/lot and eAuction rather than many separate ones?

**Comment by JachymHercher** [comment]
May I ask you to reopen this issue please?

**Comment by jseguraf** [comment]
The issue is open again.

**Comment by muricna** [comment]
Since DPS, Framework Agreement Technique and eAuction are all techniques more than one technique can be used in a lot or a procedure therefore no direct link is required between the techniques themselves.  The link FrameworkTechnique uses eAuction should be removed.

**Comment by andreea-pasare** [comment]
Below is a diagram depicting how Technique Usage concepts are modeled in ePO 3.0.1:

![image](https://user-images.githubusercontent.com/88081600/195006467-59621b17-3eda-45d7-97df-d9d67fd088f1.png)
