### ISSUE TITLE
DPS Specific Requirements

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#193]
When analysing the Awarding phase we need to heed attention to the fact that DPS has specific requirements that are dictated by the Contract (and that may not have been notified in the Contract Notice). These requirements would affect the delivery terms, for example.

TO BE DISCUSSED AND RE-ANALYSED. This is also being analysed by NO's Lawyers.

**Comment by andreea-pasare** [comment]
The Contract Term for a MiniCompetition in the context of a DPS are not published. If a use-case for providing this information is requested, the ePO model can be evolved.
