### ISSUE TITLE
Evaluation Method Type Code

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#194]
The enumeration seems superfluous...criterion that do not hold a value greater than zero in the Weight attribute should by default be PASS/FAIL.

Consider consulting this with ESPD WG.

**Comment by muricna** [comment]
The code list was removed from the ESPD see presentation of  [ESPD-EDM Open User Community of 03/03/2021](https://github.com/ESPD/ESPD-EDM/blob/wgm-reports/ESPD_OUC_Meetings_20210303_v1.0.pdf) and is therefore not required in the ontology
