### ISSUE TITLE
DPS scope enumeration

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#196]
Check if it can be used within all notices or wether it needs to be at lower notice level. Also to be checked wether it is legal to not list the buyers.

**Comment by JachymHercher** [comment]
Concerning "legal not to list the buyers", please see point 5 of https://github.com/eForms/eForms/issues/251#issuecomment-473323815

> Yes, it is possible, but only for CPBs. (This already exists in the current forms in field IV.1.3) of e.g. SF2 and is based on Art. 37(1) subparagraph 2 of Directive 2014/24/EU:
> "Where a dynamic purchasing system which is operated by a central purchasing body may be used by other contracting authorities, this shall be mentioned in the call for competition setting up that dynamic purchasing system."

**Comment by muricna** [comment]
The cardinality is 0..1 therefore application profiles for specific notices can be more restrictive.
