### ISSUE TITLE
Winning Tender Identifier

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#199]
In the meeting summary from 25/04/2019, there is the following:

BT-3201 | Winning Tender Identifier | An identifier of a winning tender or, in cases   such as design contests, some framework agreements and innovation   partnerships, of other results. The information in the winning tender section   refers to this winning tender. | The award decision has to link to the tender as   just linking to the tenderer is not enough in case of multiple tenders being   submitted by one tenderer.  An identifier is therefore added to Tender   which contains documents which have individual document identifiers.    The award decision must still link to the tenderer for ranking and multiple   submissions reasons etc.   The award decision class is not to be confused with an award decision   document that could describe several award decisions.
-- | -- | -- | --

Concerning "The award decision must still link to the tenderer for ranking and multiple submissions reasons etc.", why is that the case? For ranking purposes, it is enough to give a rank to a tender and the tender is linked to a tenderer, no? I'm not sure what "submission reasons etc." are.

**Comment by muricna** [comment]
#200
