### ISSUE TITLE
Relationship between Economic Operator and Contract Award Notice

### ISSUE THREAD

**Issue by brechtwyns** [OP-TED/ePO#20]
Question to the working group: should the model foresee a relationship between Economic Operator and Contract Award Notice?

From JH: "Isn't the "number of times a contract notice has been read" a very important indicator for knowing where is the problem with attracting bidders? ("People do not know we are running tenders!" vs. "People know we are buying, they read the notice, but then decide not to apply, because our selection criteria are too strict!"

**Comment by makxdekkers** [comment]
I am not sure that the information on how many times a contract notice has been read fits into the model. It seems to be more of a statistics function on the site that hosts the notices. A link between Economic Operator and notice assumes that the access can be traced back to a particular Economic Operator.

**Comment by JachymHercher** [comment]
@makxdekkers I agree on the statistics being out of scope. My point is rather that if we have a relationship "buyer" ""publishes"" "notice", we should also have the inverse relationship of "economic operator" ""opens"" "notice".

(For the statistic, a user of the ontology could then, perhaps, use it to specify that he is counting the number of times that "opens" of a specific type of notice happens.)

**Comment by makxdekkers** [comment]
@JachymHercher: In the latest model, the relationship is "Contract Award Notice 'is published by' Contracting Entity". The inverse of that relationship would be "Contracting Entity 'publishes' Contract Award Notice". The fact that an Economic Operator 'opens' Contract Award Notice is a process transaction not a property of the data. 
An Economic Operator can extract the information using a search (e.g. a SPARQL query): show me all Contract Award Notices that award a Tender submitted by Economic Operator (X).

**Comment by muricna** [comment]
I think rather than Contracting entity the term is Buyer

**Comment by muricna** [comment]
Ok looking at the latest version of the conceptual model I see the Procuring Entity has been split from the Buyer - not sure how everyone will feel about this.  However under buyer there should still be Contracting enitity.  If using both terms procuring entity and buyer then a link will be needed between the two (buyer and procuring entity)

**Comment by JachymHercher** [comment]
@makxdekkers 
> The fact that an Economic Operator 'opens' Contract Award Notice is a process transaction not a property of the data

This is a very interesting point and I would be grateful for a deeper clarification. My thinking is: 1) someone opening a contract notice is part of the eNotification phase of procurement; 2) this information can be stored as data (about the use of a website on public procurement); 3) this information can be used to answer a policy relevant question from public procurement (see the first post). Thus, I would think it should be covered in the ontology. 

If it shouldn't be covered, then this should be clear from the scope section of the ontology document. I think it currently isn't?

**Comment by brechtwyns** [comment]
The discussion on whether process transactions (event oriented view) should be included in the ontology, can be continued under issue https://github.com/eprocurementontology/eprocurementontology/issues/43.
