### ISSUE TITLE
Winning Tender Value

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#200]
In the meeting summary from 25/04/2019, there is the following:

BT-720 | Winning Tender Value | The value of the winning tender or another   result; including options and renewals. In case of the modification notice,   the value of the modification. | The tender applies to lots or groups of lots and   the lots and groups of lots  have a procurement value.  The   contract also has a procurement value the two must coincide in case of   modifications in the contract.   The ontology have understood this to refer to the lot, however it is not   clear as the Business Term is tender - this needs to be checked also what   does the value of the winning tender or another result mean?
-- | -- | -- | --

- Concerning "The contract also has a procurement value", in eForms, Contract does not have a value. Instead, Contract has links to Tender. This seems to be a good way of modeling all the different relationships there can be. 
- Other results could be for example projects (in case of design contests) or non-winning tenders for which the company still gets some money (e.g. in the case of innovation partnerships and perhaps competitive dialogues, there could be money - sometimes called "prize money" - for getting your tender through multiple rounds of elimination and improvement).

**Comment by muricna** [comment]
Have I understood correctly:
  In the case above where the winning tender value is requested.  If an economic operator submits a tender for several lots or group of lots the value to be given under BT-720  would reflect the value for a given lot or group of lots that is being reported upon, not necessarily all the lots submitted together.  idem for design contests etc.    

I am not sure how non-winning tenders would be covered by this BT and in this case would the value be given for the sum of the value of the tenders?  If it is individual that would seem to me that the non-winning tenders need to be published, is this the case?

**Comment by JachymHercher** [comment]
@muricna The way this is modeled in eForms, a tender can only be submitted for a single lot or a single group of lots. I'm not sure if I get the question - does this answer it? 

In the ontology, there shouldn't be a "winning tender" but rather a "tender". Tender should have an attribute rank (same as eForms BT-171 Winner Rank) and when the "rank" = 1, then we know that the particular instance of tender is a winning tender. The value is then the value offered in the tender, i.e. it would be modelled the same as for the winning tender.

**Comment by muricna** [comment]
The first question is answered.

The rank is modelled in the tender for order for example in a cascade.  Not to differentiate between winning and non-winning tender.  I still do not undertand the case you mention at the begining of non-winning tender values

**Comment by JachymHercher** [comment]
Concerning the second question, the rank can be used more broadly than the way it is used in eForms. For example, if you are choosing a tender based on lowest price and have three tenders with a value of 100 K, 110K, 120K; then after evaluation, they will be ranked as first, second, third, respectively. This rank can be given regardless of whether the procedure is a framework with a cascade or not. 

For eForms, only the cascade (design contest etc.) use case is relevant, because information about unsuccessful tenders is currently not published. However, for the ontology, it would make sense to also model this for all unsuccessful tenders. As a side note, we are aware that several MS publish unsuccessful tenders (at least CZ, SK, HU, PT, I think...), so this is likely to be one of the first updates in a future version of eForms...

(Note: not all tenders will have a rank, e.g. if they don't pass exclusion/selection criteria).

**Comment by muricna** [comment]
Thank you this is clearer now

**Comment by paulakeen** [comment]
We were addressing @JachymHercher 's suggestion of having the Tender ranked in the WG. The solution we came about was the following (which in our understanding would solve the latest request by Jachym):

![image](https://user-images.githubusercontent.com/16134316/61059575-83818b00-a3f9-11e9-8bdc-cde8a523de44.png)

If no further suggestions are issued about this topic we'll close this issue, as well as issue #199, reported by @muricna above.

**Comment by JachymHercher** [comment]
Thank you for posting. A few comments:

1) "Is Abnormally Low" + justifications should be properties of a Tender, not the Evaluation Report - it's a judgment to make per tender, depending on its value.
2) I don't understand why Tender Evaluation Rank (TER) is 1..* with Tender. Each tender has exactly one RankingInFirstStage and FinalRanking, so the relationship should be 1..1, no? If that is the case, TER as a class could be removed and the properties could go within Tender. 
4) Ranks are per lot, so shouldn't Tender be replaced by TenderLot? (Or is this linked to the previous point?)
3) The names of TER properties could be harmonized, e.g. to RankingFirstStage; RankingFinalStage?

**Comment by JachymHercher** [comment]
(May I ask you to reopen the issue, please? Just not to forget about it.)

**Comment by eprocurementontology** [comment]
Since the ontology can be used for different models the cardinalities have been opened up 0..1.  In  case an application profile is made for specific notices then a further restriction can be applied.
