### ISSUE TITLE
Main-Activy: To be splie into authority-activity and entity-activity

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#201]
The code list should be split as 👍 
authority activity
[authority-activity.xlsx](https://github.com/eprocurementontology/eprocurementontology/files/3191694/authority-activity.xlsx)
[entity-activity.xlsx](https://github.com/eprocurementontology/eprocurementontology/files/3191696/entity-activity.xlsx)

:

hc-am | Housing and   community amenities
soc-pro | Social protection
rcr | Recreation, culture   and religion
def | Defence
env | Environmental   protection
econ | Economic affairs
heal | Health
edu | Education
gen-pub | General public   services
pub-os | Public order and   safety

and 

entity-activity:

Production,   transport or distribution of gas or heat
--
Airport-related activities
Extraction of gas or oil
Port-related activities
Exploration or extraction of   coal or other solid fuels
Electricity-related   activities
Postal services
Railway services
Urban railway, tramway,   trolleybus or bus services
Water-related activities

**Comment by jseguraf** [comment]
The model has been updated accordingly.
