### ISSUE TITLE
Lot discussion

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#206]
The last 13th July we had a new session to discuss about Lot. After the discussion the following modelling decisions made were: 

Please note that all the decisions have been modelled within the Tender diagram.

- The classes financial Value, Value and Tender Lot have been added.

- The diagrams has been reorganized starting by the root element, the Economic Operator.

- A note has been added within the diagram in order to review the relationship from Tender and Economic Operator in another moment.

- All the Tender Documents have been included within the diagram.

- The Cardinality from Tender Document and Tender Lot has been changed to 0..1 due ESPD Response could refers to Tender Lot.  In addition, the predicates of the relationship have been changed

- GPA usage attribute has been moved from Procedure class according to the eForms approach

**Comment by muricna** [comment]
The Working group should check which attributes should be in Tender and which in Tender Lot.  The diagrams showing the Tender and Tender Lot: Tender and Evaluation result need to be harmonised.

**Comment by eprocurementontology** [comment]
In future versions of the ontology it is proposed to remove TenderLot since a tender should be presented per lot and not procedure.
