### ISSUE TITLE
Comparative assessment

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#209]
It should be clarified whether contracting authorities should conduct  a comparative assessment of Group lots  by first determining which tenders best fulfil the award criteria laid down for each individual lot and then comparing it with the tenders submitted by a particular tenderer for a specific combination of lots, taken as a whole.

WG meeting of 06/06/2019

**Comment by paulakeen** [comment]
We need to go deeper in the analysis of what is meant and intended with this "comparison". In any case this would be part of an ad-hoc evaluation process. Let's discuss it asap.

**Comment by eprocurementontology** [comment]
This element is not required for eNotification and is therefore closed.  It can be reopened if needed by other phases.
