### ISSUE TITLE
Defining classes and properties: source

### ISSUE THREAD

**Issue by brechtwyns** [OP-TED/ePO#21]
What should be the primary source of definitions?

The methodology states: "In the e-procurement ontology, definitions should to the extent possible come from legislation, such as the e-procurement and e-invoicing directives . If legislation does not provide suitable definitions, definitions from established business vocabularies such as UBL or XBRL should be used."

Comment from JH: "Definitions may vary above and below threshold. We need to try to make definitions, for example, **more general than in the directives**, so that they can be applied also for below-threshold!"

**Comment by makxdekkers** [comment]
The WG needs to discuss this. On one hand, an opinion has been expressed that the definitions should as much as possible be based on the definitions in the Directives; on the other hand, it has been proposed that definitions should be more general than in the Directives. An intermediate position could be to make the definitions broadly applicable, but refer to definitions in Directives that are included in the broader definition.

**Comment by muricna** [comment]
I agree
