### ISSUE TITLE
Submission Terms and procedure

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#211]
To be  checked why we do not have a relation between Submission Terms and Procedure

WG 06/06/2019

**Comment by paulakeen** [comment]
The potential reason was, we think, that the link is done through the Lot. We could have it also linked to the  Procedure directly for the case when the Submission Terms are the same for all the Lots. 

However this could introduce the possibility of inconsistency unless a strong rule is established and never forgot (of the type either "use one or the other but not both").

We are going to revisit the good practices about pattern design on this topic and will come back with more feed-back on this.

**Comment by eprocurementontology** [comment]
To avoid complicated business rules SubmissionTerm will remain at Lot level.
