### ISSUE TITLE
PIN in DPS

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#212]
According to the Directive 2014/24/EU art.34.2.a "the minimum time limit for receipt of requests to participate shall be 30 days from the date on which the contract notice or, where a prior information notice is used as a means of calling for competition…", therefore the use of the PIN are relevant in a DPS. However, in the model there is not link between DPS and PIN.

**Comment by paulakeen** [comment]
Yes, we haven't covered the modelling of the documents yet, but thank you for the remark.We'll add a special note in the EAP file so we do not forget.

**Comment by eprocurementontology** [comment]
The PIN is connected to the procedure.  DPS is a technique that maybe used by a lot, which is part of a procedure.  Therefore no direct association is required.
