### ISSUE TITLE
Placeholders DPS

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#213]
According to the Directive 2014/24/EU the following properties are missing in the model: 

- Minimum time limit for receipt of requests to participate in a DPS (art. 34.2. a)

- Deadline for CA to  finalise the assessment of request to participate in a DPS (art. 34. 5. first subparagraph)

- Prolonged deadline in individual cases to  finalise the assessment of request to participate in a DPS (art. 34. 5. first subparagraph)

- Is related to the individual EO - how do we handle this?

- Extended evaluation period (art. 34. 5. second subparagraph)

- Shall be indicated in the procurement documents, i.e. in the call for competition - Related to the procurement documents?

- the minimum time limit for receipt of tenders (art. 34.2. b)

- Date of "admitted or not" to the DPS

- Do we need a place holder for this date, or does it fit in an existing?

**Comment by paulakeen** [comment]
We see practially all these "bullets" as properties of the class Dynamic Purchase System, i.e. "links" between DPS and Period.

1. We have added a property "request For Participation Deadline" between the class DPS and Period,
2. "Deadline for CA to finalise the assessment of request to participate in a DPS" would already be covered in the model by the property "participation Evaluation Period"
3. The "Prolonged deadline in individual cases [..]", we do not see the need of creating a property for this, as this is "carved in stone" in the Directive (see Article 34.5 first paragraph).
4. The information related to the EO would not be part of the eNotification and eAccess but of the evaluation, and in any case we don't see the rationale of having this in the Technique, but in any case in the shortlist.
5. Extended evaluation period would already be covered by the property "participation Evaluation Period".
6. The procurement documents referred to in the Directive would be the PIN CFC and the CN.
7. The "minimum time limit for receipt of tenders" is already covered by the property "Receipt DeadLine" attribute of the class "Submission Terms".
8. Date of "admitted or no to" to the DPS, this would be part of the eValuation analysis. **PLEASE DO NOT FORGET TO DO THIS ANALYISIS.**

**Comment by JachymHercher** [comment]
Concerning 1, DPS are always part of a restricted procedures. In the ePO, isn't the property "request For Participation Deadline" already covered by a different element elsewhere, possibly linked to the procedure/lot? 

In eForms, in any restricted procedure, regardless of DPS, this date would be placed in BT-1311 (Deadline Receipt Requests).

**Comment by paulakeen** [comment]
OK, you're right, this we have it as "Receipt Experessions Deadline" in the class Procedure Terms. So we decide to remove it and add a note in the "Additional Information" for the definition of that attribute.

WG Approval 9/7/2019

**Comment by JachymHercher** [comment]
"Receipt Expressions Deadline" sounds rather like BT-630 (Deadline Receipt Expressions), which is something else than BT-1311 (Deadline Receipt Requests). The former is used as the "first step" in procedures where a PIN was used to launch the call for competition; the latter is used in restricted procedures. 

In the ePO, isn't there also something closer to the BT-1311?

**Comment by paulakeen** [comment]
We were just discussing this very same topic because felt uncomfortable with the fact that Expression of Interest and Request for Participation was so "polysemic". 

We think the way eForms has it is the right now, and no we misterously enough we hadn't the property in the ePO (possibly because of that unjustified polysemia). So we have decided it to add it to the class "Procedure Terms".

Let's not close the issue, as we should revisit this topic.
