### ISSUE TITLE
TheyBuyForYou has created an RDF ontology for OCDS

### ISSUE THREAD

**Issue by jpmckinney** [OP-TED/ePO#215]
Working group members had mentioned earlier that the unavailability of an ontology or UML diagram for OCDS made it more difficult to review or re-use parts of it.

@TBFY has (independently of the Open Contracting Partnership) created an RDF ontology and UML diagram for OCDS: https://github.com/TBFY/ocds-ontology

This issue is just as FYI to working group members, in case it is useful.

**Comment by muricna** [comment]
Thank you this is intersting.  Unfortunately I have had to send an issue to TBFY as the link to the uml diagram is broken.
