### ISSUE TITLE
BT-748 What is this business term used for?

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#219]
We do not understand the rationale for having this business term.

**Comment by SellittoGiampaolo** [comment]
Business Term? I understood it was yst a Code --> Yes or No, to distinguish whether the Selection criterion applies or not (the EG are mandatory)

**Comment by JachymHercher** [comment]
A general eForms approach is distinguishing "No" and "missing". In other words, if something is not the case, then it has to be declared explicitly. BT-748 declares whether a selection criteria is or isn't used. 

If an eForms standard form is used (without extending it with an ESPD), then this fields would be used for the three "high level" selection criteria families requested by the Directives' Annexes: "Suitability to pursue the professional activity", "Economic and financial standing" and "Technical and professional ability". 

The "Not yet known" option can be used in prior information notices.
