### ISSUE TITLE
eForms BT-733 Justification when Order or Importance instead of weight

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#221]
While mapping the eForms BT-733 into the ePO conceptual data model, we observed that the Justification is optional for all the documents. Reading Recital 90 of the Directive (last paragraph) it would seem necessary to justify why this weighting method is chosen. 

**Question: Wouldn't the justification be compulsory (CM) when the weighting type is "order of importance"?**

We have provided a definition for this concept different from the one in  eForms. It reads as follows:

"Explanation about why the actual weighting model is chosen. 

Additional information: 
In eNotification: This property is specifically used to describe why the order of importance is used over another weighting model.
In ESPD: This is used to explain other complex models of weighting for transparency reasons. "

**Comment by JachymHercher** [comment]
The justification is not mandatory in eForms, because Rec 90 does not create an obligation to include the justification in a notice. The justification could simply be in the procurement documents or another internal document of the buyer.
