### ISSUE TITLE
BT-736 and BT-113 Maximum Number or Candidates for a Framework Agreement

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#222]
Can anyone from the eForms WG help us (a) can you help us understand what this number refers to and how is it used in the case of FA? We understand this is CM in CN General because it is mentioned at the end of the Annex listing the information that must go in the CN, at the end of paragraph (a), which goes as follows: 
 
"In the case of a framework agreement, indication of the planned duration of the framework agreement, stating, where appropriate, the reasons for any duration exceeding four years; as far as possible, indication of value or order of magnitude and frequency of contracts to be awarded, number and, where appropriate, proposed maximum number of economic operators to participate."

**Questions:** 
1. Some members of our WG think this may refer to the maximum number of members of a Consortium. 
2. Other think this refers to the maximum number of EOs that can tender for a FA. 
3. If 2, would that be equivalent to the maximum number of EOs that are acceptable for the procedure where the FA is used? 
4. If 2, coud this number vary per Lot or Group of Lots?
5. What does the text "where appropriate" in the Directive refers to? (any example of when this is appropriate?)

**Comment by JachymHercher** [comment]
"Economic operators (EO) to participate in the framework agreement (FA)" is equivalent to "EO party to the FA", as used e.g. in Art. 33 of Directive 2014/24/EU. It might have been better to use the latter expression, but we stuck to the wording in the Annex. 

This means: 
1. No. A consortium is a single economic operator, so regardless of the number of the members of a consortium, it would be counted as a single participant in a FA. 
2. Here the answer might be "yes", but I'm not sure whether "tender for FA" was intended to mean "party to a FA" :-). (In case of a FA with reopening of competition, all the EO that are party to a FA could submit their tenders.)
3. See above.
4. Lots yes. Concerning groups of lots, I think that's a very theoretical option and I can't really imagine what it would look like, but let's say "yes" as well. 
5. "For framework agreements longer than four years" (you must give the justification).

**Comment by ColinMaudry** [comment]
Thank you Jachym. Does it mean that a procuring entity can limit the number of tenderers in a FA arbitrarily, without using criteria and selection rounds?

**Comment by JachymHercher** [comment]
Sorry, my original answer to question 4 was wrong, I've corrected it. 

To answer your question, I'd rather say that a procuring entity can limit the number of tenderers "arbitrarily", but the limited number still needs to be selected using selection and award criteria. You can have a framework agreement where there's only one participant (and no reopening of competition), you can have a framework agremeent with multiple participants, all's good as long as you select him/them fairly. 

(BTW: @paulakeen, in the name of this subject BT-736 should be BT-778, right?)

**Comment by paulakeen** [comment]
Understood, and the  ePO WG considers that the Ontology Conceptual Data Model caters currently for everything commented above. 

We close the issue, but if not comfortable feel free to ask for its reopening.
