### ISSUE TITLE
Usage of the Procedure and Lot in the Planning stage (REGULATION (EU) 2019/1780)

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#226]
eForms issue (https://github.com/eForms/eForms/issues/328):

During the latest WGM of ePO, we were mapping the PINs of the Planning stage against to the ePO concepts. For the mapping we used the new regulation. However, some questions and doubts came up from a first analysis of the Planning stage:

According to the Purpose definition: “Information about the purpose. This information must be given for the whole procurement procedure and, if they exist, also per lot. In case of a prior information notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure”, should purpose not foresee planned procurement as well as procurement and lots?

Are lots already know at the planning stage if not then why are there optional fields in the planning stage? For example:

![image](https://user-images.githubusercontent.com/33545990/68936790-86233100-079b-11ea-9138-739b4576a979.png)

**Comment by GPsellitto** [comment]
Usually at Planning stage the division in lots is not known, as the Contracting Authority is defining WHAT they need to buy in the next three years, not  HOW to buy.
In the case the PIN is used only for shortening the publication period, it is likely that we are in a later phase, when the Contracting Authority has already defined how to buy and possibly a strategy, there comprised the shortening of publication period

**Comment by muricna** [comment]
Thank you Giampaolo for this clear description

Natalie Muric

[cid:image002.png@01D59BD0.C0DFC150]

Publications Office of the European Union
Directorate C – Access to and reuse of public information
C.3 – TED and EU public procurement
2, rue Mercier • L-2985 Luxembourg
Tel. +352 292944008 • Fax +352 292944604
natalie.muric@publications.europa.eu<mailto:natalie.muric@publications.europa.eu>
https://op.europa.eu<https://op.europa.eu/>

Facebook<https://www.facebook.com/EULawandPublications> - @EU Publications<https://twitter.com/EUPublications> - @EUR-Lex<http://twitter.com/EURLex>
@CORDIS_EU<http://twitter.com/CORDIS_EU> - @EUTenders<http://twitter.com/EUTenders>
@EULawDataPubs<http://twitter.com/EULawDataPubs> - @EU_opendata<http://twitter.com/EU_opendata>

**Comment by muricna** [comment]
Issue duplicated and to be followed under: https://github.com/eForms/eForms/issues/328
