### ISSUE TITLE
Strategic Procurement Defintion

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#227]
Proposed definiton:

Condition that aims to reduce the environmental impacts of the procurement, fulfil social objectives and/or buy an innovative work, supply or service.

Additional Information: 
The conditions must be achieved via either  technical specifications, selection criteria, award criteria and contract terms.

**Comment by muricna** [comment]
Well-designed public procurement systems also contribute to achieving pressing policy goals such as environmental protection, innovation, job creation and the development of small and medium enterprises.
Could be condensed:
Public procurement that contributes to to achieving pressing policy goals such as environmental protection, innovation, job creation and the development of small and medium enterprises.
Could be further split the such becoming additional information.
The text comes from: https://www.oecd.org/gov/public-procurement/recommendation/
](url)

**Comment by GPsellitto** [comment]
great 
I like this definition

**Comment by eprocurementontology** [comment]
Final definition:

Public procurement that contributes to achieving pressing policy goals.

Additional Information:
Specific strategic goals could be, for example, environmental protection, innovation, job creation and the development of small and medium enterprises.

Based on https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0411 (see paragraph on "background information".

WG Approval 10/03/2020
