### ISSUE TITLE
Document Metadata

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#234]
Date: 04/02/2020 and 06/02/2020

Everis presented its proposal about how to represent the IFLA LRM model in ePO and how it impacts the Documents diagram. The model presented (see below) was based on Enrico Francesconi’s presentation during the last F2F meeting on 10/10/2019 (for more information see the report of the F2F meeting):

![image](https://user-images.githubusercontent.com/33545990/75544571-926a8b80-5a24-11ea-9a37-fafa7f788f41.png)

Everis explained had analysed the IFLA LRM and the IFLA FRBR models. After the comparison of both IFLA models everis concluded that the LRM is more useful for ePO since it has very good definitions and includes interesting elements that can be reused. 

Everis  highlighted the fact that the proposed model uses the three main entities of the IFLA model: Work, Expression, Manifestation and Item, and also takes into account two different vocabularies: DCAT and ADMS. 

Everis explained that ADMS and DCAT models are very useful for the description of DataSets. Everis used the occasion to introduce to the WG the ADMS – Asset Description Metadata Schema (https://joinup.ec.europa.eu/release/adms-ap-joinup-version/20) and DCAT vocabulary – Data Catalog Vocabulary (https://www.w3.org/TR/vocab-dcat-2/) which have been considered as inputs for the representation of Document in ePO. 

The ADMS is a specification created by a W3C working group and it is used for the description of reusable solutions (e.g. data models). DCAT is a vocabulary used to facilitate the interoperability between data catalogues. DCAT enables the description of datasets and data services in a catalogue. Everis indicates that ADMS is being evolved as well as DCAT. 

Everis explained that ADMS Vocabulary is derived from and reuses the DCAT Vocabulary. Everis indicated that if the ePO Documents are considered to be Datasets, there is the need to use DCAT for the representation of documents. In addition, ePO should take also into consideration what OP did for other projects like CELLAR where the IFLA model was used. 
Everis indicates that the ADMS is currently evolving under SEMIC (https://joinup.ec.europa.eu/solution/asset-description-metadata-schema-adms). Regarding the DCAT Vocabulary, W3C produced a new version which is a recommendation (https://www.w3.org/TR/vocab-dcat-2/).
After the explanation context, everis indicated that its proposal reusese the IFLA LRM model and extends it with the necessary classes. The idea is also to reuse the ADMS and DCAT. Everis presented to the WG a proposal model which reuses the 3 candidates, IFLA, ADMS, and DCAT:  

![image](https://user-images.githubusercontent.com/33545990/75544615-a4e4c500-5a24-11ea-9297-7800c346e93a.png)

The WG discussed the proposal and the main reactions were: 
-	The document concept cannot be aligned to models that are under evolution (ADMS and DCAT-AP). 
-	The Document model could reuse the new class dcat:Resource. 

After the discussion and reflection the WG agreed to work on the Document concept and not define assets for the time being. All properties that are considered to be part of the asset should for the time being be represented in the Document.  The discussion will be rediscussed when DCAT and ADMS are matured.

**Comment by eprocurementontology** [comment]
The discussion on DCAT is out of scope of the ontology for the time being because it concerns the datasets produced from the ontology.  The ontology could consider making recommendations.

The metadata of the documents is found in the Document class and this is considered sufficient for the time being.
