### ISSUE TITLE
Procurement Criteria

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#236]
The WG came up with 2 solutions on how to model the different criteria:

1)	to have each criterion (Selection Criterion, Award Criterion and Exclusion Criterion) linked to each taxonomy of subcriterion. For example: Selection Criterion has the following subcriterion as a code list: Suitability, Economic and financila standing, Technical and professional ability, other. 

2)	to have criterion represented as subclasses instead of having taxonomies. For example: Selection Criterion has the following subcriterion as subclasses: Suitability, Economic and financila standing, Technical and professional ability, other. 

**WG comments/discussion:** it makes no difference whether to have or not classes instead of enumerations.  It makes sense that each class adds something special which makes it different, but this is not the case.
**WG decision:** the model will be kept using the code list and the subcriterion will not be represented as classes.

**Comment by muricna** [comment]
Becareful v.2.0.1 does not have a criterion class.  The frozen branch 2.0.2 has a criterion class that should correspond in some way to the criterion in cccev we then need to find how we fit all the requirements and evidences with the procurement criterion.

**Comment by andreea-pasare** [comment]
In ePO 3.0.1, the criterion was aligned with CCCEV. Below is a diagram that depicts how Criterion is modeled:

![image](https://user-images.githubusercontent.com/88081600/195011087-d8d6f0b4-162e-4909-901b-db3f71145f7b.png)
