### ISSUE TITLE
mapping of BT-16 organisation part  name

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#238]
In cell BC for CN you can find:
"
CN isA Notice, 
Notice isA Document, 
**Document notifies(subproperty of Document refersTo) PlannedProcurementPart,
PlannedProcurementPart isPlannedBy Buyer,** 
Buyer isA Role, 
Role isRoleOf Agent, 
Buyer playsRoleOf FormalOrganization, 
FormalOrganization isA org:FormalOrganization, 
org:FormalOrganization isA org:Organization, 
org:Organization org:hasUnit org:OrganizationalUnit, 
org:OrganizationalUnit cagv:hasName Name, 
Name isA Text"
This seems to be a copy paste from the PIN . It should consider the CN case.
"Document anounces (subproperty of Document refersTo) Procedure,
Procedure isResponsibilityOf Buyer, "
I also doubt we can find the organisational unit from the predicate hasUnit because an Organisation has many units. Agent should point at the precise unit directly.

**Comment by andreea-pasare** [comment]
In ePO 3.0.1, BT-16 organisation part name is mapped to the literal attribute epo:hasOrganisationUnit (from org:Organization concept) with the following definition:

_The name of a subpart of an organisation._

_Additional Information:
E.g. the relevant department of a large organisation._

![image](https://user-images.githubusercontent.com/88081600/195012266-ae5490eb-65ac-49d8-b0ef-6ece76a5e73d.png)
