### ISSUE TITLE
Class "Lot" under "Call For Tender"

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#24]
Claude Schmit proposed the creation of a new class "Lot".
The notion of class "lot" is important and often implicit. It does not appear under "call for tender", it's a 1..n cardinality and many classes will fall under each "lot" like "tender" and "contract". Also one "lot" can have several "contracts" (cascade).

**Comment by JachymHercher** [comment]
(Don't overlook: when the same contractor won several lots, then one "contract" can have several "lots" . I.e. the lot-contract relationship can be many to many.)

**Comment by makxdekkers** [comment]
In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017) there is a comment in the definition of the Call For Tender: "The relationship between Call For Tender and Lots needs to be further detailed".
If a Contract can refer to more than one Lot, and multiple Contracts can refer to one Lot, then the relationship between Contract and Lot indeed needs to be n..n. 
This is an issue that needs to be further discussed by the Working Group.

**Comment by eprocurementontology** [comment]
After discussion contracts refer to 1..n lots
