### ISSUE TITLE
hasSize predicate between epo:Business and at-voc:economic-operator-size is wrongly named 

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#241]
micro, small and medium sme types are defined by commission recommendation https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32003H0361&from=EN.

In article 7 of the same recommendation, enterprise size-class is defined. 

There is a mix of concepts between the size and the sme type that involved more than staff head counts

**Comment by jpmckinney** [comment]
Noting that the precise definitions (outside the EU) change from jurisdiction to jurisdiction, and some jurisdictions distinguish between micro-enterprises and self-employed individuals, whereas others collapse them into the same class.

**Comment by JachymHercher** [comment]
(@jpmckinney In the EU change across the EU as well - the EU's is just a "recommendation" so some countries (e.g. Germany) have their own. BTW: a new recommendation is in the making.)

**Comment by cecileguasch** [comment]
@JachymHercher Thanks for the info. Can you share information about the recommendation in the making? Already available in the Decide Planning tool? 

@jpmckinney , Indeed. In Article 7 of the same recommendation the distinction between self employed and micro is made within the concept of Size. I wonder how the concept of Size and SME type are co-existing in real life. My guess is that they are mixed as they have been here.

**Comment by JachymHercher** [comment]
The information is at https://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition_en. The box on the right of the page refers to an impact assessment, consultation strategy and an open consultation which finished a couple of years ago. It definitely won't be a quick process.

**Comment by eprocurementontology** [comment]
The predicate should be changed from hasSize to hasEnterpriseCategory

**Comment by andreea-pasare** [comment]
In ePO 3.0.1, this predicate was changed to epo:hasBusinessSize:

![image](https://user-images.githubusercontent.com/88081600/195013556-bda207b5-6b03-4fd7-8edc-70ce71b68857.png)
