### ISSUE TITLE
TendersReceivedPerLot

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#242]
The eprocurement analytics provided the information that only admissible tenders should be counted.

Change the definition to : 
Total amount of admissible tenders

Add in the additional information 
 Competing tenders from the same tenderer must be counted
Adnormally low tenders as well.

**Comment by muricna** [comment]
This relates to BT-760 in the eforms where it is clearly stated "All tenders must be counted, regardless of whether they are admissible or inadmissible. "  If this is changed in the ontology there will be no mapping to the eForms.  If you want to add another Statistical information for "Total Admissible tenders" please let us know, but please be aware there will be no mapping from eForms

**Comment by cecileguasch** [comment]
It is not desirable that teh eprocurement ontology would not be aligned with the eForms.
 Unadmissible tenders could hide collusion. So I think it is wrong to have them counted in case the aim is to monitor for competition.
Then I would like to open this question in the eForms subgroup.

**Comment by JachymHercher** [comment]
Hello, the approach of eForms is to collect separate information about all the different types of submittted tenders. This is done by having BG-712 (Received Submissions) repeatable for different values of the BT-760 (Received Submissions Type) codelist. The BT-760 codelist looks something like what is written in https://github.com/eForms/eForms/issues/312#issue-440639113 and if I'm not mistaken, @cecileguasch 's need should be met by submitting values with the code "Tenders verified and inadmissible".

**Comment by cecileguasch** [comment]
thanks @JachymHercher .
So the case is solved. We will use ReceivedTenderLots - InadmissibleTenderLots. In case unverifiedTenderLots the approximation will be that they are all admissible.

**Comment by JachymHercher** [comment]
Why / in which case would you want to / need to approximate unverified as admissible?
