### ISSUE TITLE
NUTS for public organisations

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#243]
The EXEP eProcurement analytics sub group requires the NUTS information for Public organisations. For now only registered organisations HasLocation Location. So the NUTS codes are not available for Public organisations.

**Comment by giorgialodi** [comment]
Cecile, this message makes me think a bit. I thought that also the Public Organization can be a registered organization. In Italy all public organizations are registered in a public registry with a formal name. So I checked the diagram and I was thinking whether we can simplify that a bit @muricna  For instance we may say that there are organizations that are public and private and probably a mix of them. And all this information about legal name, id and spatial coverage can be attached to the organization abstract class.  If we do not simplify we definitely need to attach all these properties to abstract classes (formal organization or organization). It is indeed true that an organization has a spatial coverage, has a name e probably an ID (in any type of reference system).

**Comment by giorgialodi** [comment]
@cecileguasch , I think that with the changes we applied recently in the organisation part, this can be easily solved with a property "spatial "connecting organisation to location.

**Comment by muricna** [comment]
Are the inheritances in the wrong direction in the model?

**Comment by giorgialodi** [comment]
Hi Natalie, @muricna no I do not thiink so. We simply need to verify that in the last modification we discussed for Organisations (Business, PublicOrganisation, OrganisationGroup)  we define a property "hasLocation" or "spatial" (as it is named in DublinCore) from Organisation to Location :) and it should be sufficient for Cecile's requirements.

**Comment by giorgialodi** [comment]
BTW: probably there was also a "hasLocation" property for PublicOrganisation in the old model, at least it seems to me to see it in the old diagrams.  With the simplification we introduced recently, we can simplify this part about location too.
