### ISSUE TITLE
predicate "notifies" only used between PIN and procedure

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#244]
PIN **notifies** Procedure .
But CN and CAN are related to procedure with a generic predicate 'related to'.
CN is Document Document **relatedTo** procedure.
The proposal is to generalise the notifies predicate in the following way: Notice **notifies** procedure.
PIN is Notice, CN is Notice, CAN is Notice.

**Comment by giorgialodi** [comment]
Cecile @cecileguasch, you are proposing to have "notifies" as subproperty of relatedTo that should only be applied when the type of Document is in general a Notice,  correct? If so, I agree with this proposal, including all types of Notice, not only PIN.

**Comment by cecileguasch** [comment]
yes Giorgia, you understood what I was trying to express.

**Comment by muricna** [comment]
I see in the mapping we have:

CN isA Notice,
Notice isA Document, Document announces (subproperty of relatesTo) Procedure,
Procedure specifies Lot,
SubmissionTerms appliesTo Lot,
SubmissionTerms haseSubmissionPermission

I do not understand how this is modelled.  But it is probably equivalent to what you are saying.  To be discussed

**Comment by muricna** [comment]
@paulakeen in the mappings I have: 
epo:Organisation epo:hasLocation epo:Location,
epo:Location epo:hasPostalAddress epo:Address,
epo:Address epo:hasCountrySubentityCode Code;

Is the model on line not up-to-date?

**Comment by cecileguasch** [comment]
latest decision is to name the predicate Notice Announces Procedure

**Comment by muricna** [comment]
How does this work for CAN? A CAN does not notify a procedure it notifies the award or non-award

**Comment by cecileguasch** [comment]
We used: CAN summarises Procedure
