### ISSUE TITLE
Question: EAuctionUsage property

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#246]
In the diagram we say that the Lot uses a Technique that can be an EAuctionTechnique. According to this sentence it seems to me that if we say that the Lot uses EAuctionTechnique is because we are sure it is known it uses it. However, in the class EAuctionTechnique there is the property EAuctionUsage whose values are those of the related controlled vocabulary usage. The items of usage are used, not used, not yet known.

Do you think it could happen to have  real data where a Lot uses an EAuctionTechnique and then for the EAuctionUsage the data says that the usage of that technique is "Not Used"? If the Lot uses that technique how come I can say that is not used, or not yet known? 

We already faced this for another class of the ontology but in this case it sounds to me very strange  according to the properties linking the Lot to the Technique :)

**Comment by eprocurementontology** [comment]
This element has been inserted for eForms in the absence of implementations of the ontology we need to indicate whether the Tecnhnique is used or not.  In the case the ontology is implemented and it is present then "not used" or "not yet used" should not be an option

**Comment by giorgialodi** [comment]
ok, always difficult to think in these terms but alright. The property is not mandatory so we will avoid its usage in the mapping. Thanks!
