### ISSUE TITLE
ProcedureType and Type

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#248]
In the UML diagram that can be navigated online through HTML for version 2.0.2 in the Procedure I see two properties: Type and ProcedureType and the property hasProcedureType. In the UML diagram that can be navigated online through HTML for version 2.0.1 in the Procedure I see only ProcedureType and the property hasProcedureType points to a green box for the procurement procedure type controlled vocabulary which is empty (while in the diagram of version 2.0.2 the green box is valorized with the elements of the controlled vocabulary).

I think it has been decided to use ProcedureType only in the Procedure as in version 2.0.1 and. So we need to delete Type in the class Procedure in version 2.0.2 and to include the element of the controlled vocabulary in the green box for version 2.0.1 :)

**Comment by paulakeen** [comment]
Yes, some modifications in 2.0.1 need to be yet to be applied onto the 2.0.2 version. We'll take care of that ASAP. Thank you for remarking.

**Comment by giorgialodi** [comment]
Yep; I included here this issue so that you can easily keep track of these situations. If I will see analogous cases I will tell you!

**Comment by paulakeen** [comment]
the attribute 'type' has been removed from the Procedure class, and the predicate linking procedureType to the code list with the classification of procedures reworded to epo:hasProcedureType.
