### ISSUE TITLE
Questions on Amount and Currency

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#250]
I was looking at the common classes to be also used  in the BDTI pilot. In particular, I am trying to understand how to correctly map an Amount.

I have two questions about this:
1) in the OWL ontology you use http://www.unece.org/cefact# --> does it really exist as an OWL ontology? If so, where can I find the OWL source code? I found a word document but it seems that the URL points to a specific web site.
2) if I remember correctly in the BDTI pilot we need to test also the use of controlled vocabularies. One of this should be the currency one (am I right @cecileguasch?). How can I use it in the current modelling of the Amount? Amount has three attributes: an AmountValue (xsd:decimal), a CurrencyID that is of type xsd:normalizedString and CurrencyCodeListVersionID that is of type xsd:normalizedString.
Where to use the EU controlled vocabulary on the currency then?

**Comment by paulakeen** [comment]
The URL http://www.unece.org/cefact# does not exist as an ontology. The CCT specification has never been modelled in RDF, just as XML.

**Comment by giorgialodi** [comment]
aaah, so does it make sense to use it directly in our ontology then (BTW: we also say in the isDefinedBy property that it is defined in the name space of epo which is not true)?

**Comment by paulakeen** [comment]
CCTS types are all addressed differently now since the reconfiguration of the transformation tool, which now maps to the epo namespace and uses richer types of data. See the mapping xml configuration file in the transformation tool.
