### ISSUE TITLE
Question on number of economic operators invited

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#251]
With the mapping activities on ANAC's data for the BDTI pilot, we encountered "the number of economic operators that have been invited". However, we cannot map it in any property of the ontology. @muricna @paulakeen is there such a property that I am not able to find it? Or this data has not been modelled yet?

**Comment by muricna** [comment]
I have asked for this attribute to be added to the statistical information - I take it should be at lot level?

**Comment by giorgialodi** [comment]
I would say yes per lot but I think @SellittoGiampaolo  can better answer then me :)

**Comment by SellittoGiampaolo** [comment]
Yes, this information is requested to the Contracting Authority per lot.

**Comment by paulakeen** [comment]
We said that, in the ideal world, this number could be calculated based on the invitations sent. But in the real, actual, world this cannot yet be modelled, and therefore it had to go to the big-class about statistical information (as @muricna says).

**Comment by paulakeen** [comment]
We have added an attribute NumberOfTenderersInvited to the class StatisticalInformation in, both, v2.0.1 and v.2.0.2.
