### ISSUE TITLE
inverse property between Procedure and Notice

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#252]
Probably I've already highlighted that in other occasions, but in the mapping with real data, it seems quite convenient to define an inverse property for the current available property notifies (between Notice and Procedure). It can be named isNotifiedThrough (or isNotifiedWith or something like that) that has domain Procedure and range Notice. 

What do you think about this @muricna @paulakeen?

**Comment by paulakeen** [comment]
Everything that is contrasting the model against real data is for sure not a waste of time. Your proposal about the inverse property makes sense.

**Comment by muricna** [comment]
The change request has been made

**Comment by giorgialodi** [comment]
@muricna that's great! Will the change also appear in the OWL file for versione 2.0.1?

**Comment by muricna** [comment]
The change should also appear in the OWL

**Comment by muricna** [comment]
The change has been made
