### ISSUE TITLE
SubmissionTerm and Lot

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#253]
There is a difference between the version 2.0.1 and version 2.0.2 for the SubmissionTerm and Lot relationships. 
In version 2.0.2 Lot hasSubmissionTerm and SubmissionTerm isSubmissionTermOf Lot (one is the inverse of the other). This is perfect, and looking at real data is what we really need.

Unfortunately, in version 2.0.1 this is different. SubmissionTerm isAppliedBy (property used for many other relationships) Lot and there is no inverse property. This can be a limitation (even if it is still possible to map real data in any case). In the OWL files of version 2.0.1 that we are using for the BDTI pilot, there is this latter solution that reflects the UML diagram of version 2.0.1. 

Do you think it is possible to harmonize the two versions and reflect this also in the OWL files we have to use at the time being?

**Comment by muricna** [comment]
I have requested the change, will keep you informed

**Comment by giorgialodi** [comment]
That's great @muricna! Thanks a lot!

**Comment by jseguraf** [comment]
The v2.0.1 of the ontology uses the object property [SubmissionTerm] - isAppliedBy -[Lot] and [Lot] - applies - [SubmissionTerm].

**Comment by giorgialodi** [comment]
We should uniform it in version 2.0.2 if "applies" and "isAppliedBy" is more appropriate as name of the object property and its inverse.

**Comment by jseguraf** [comment]
The v2.0.2 has benn also updated as in v2.0.1: [SubmissionTerm] - isAppliedBy -[Lot] and [Lot] - applies - [SubmissionTerm].

https://eprocurementontology.github.io/v2.0.2/index.html

**Comment by eprocurementontology** [comment]
This has been fixed in version 2.0.1 in the next version where the properties and ranges have been reviewed the property will be: Lot isSubjectToTerm SubmissionTerm  and the inverse SubmissionTerm setsContextFor Lot
