### ISSUE TITLE
Numeric Class

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#254]
Many properties that can be simply data type properties (e.g., hasReceivedTenderLots) and thus can use directly some built-in datatypes are defined as object properties whose range is Numeric that is a class that has a property format hat can be the union of Numeric or Indicator.

BTW: in the OWL restrictions file the property hasReceivedTenderLots is both a datatype property  (with range xsd:decimal) and an object property with range Numeric as defined above.

I think we are unnecessarily complicating things here. Why do not we define that all the properties that are connected with final values (strings, numbers, dates ecc.) are simply data type properties and use directly the built-in data types we have already? 

So hasReceivedTenderLots is simply a data type property (and NOT an object property) whose range is  xsd:int (?, is there the possibility that this property is a decimal?).

**Comment by paulakeen** [comment]
The WG modified the configuration, so now the transformation tool can cope with different richer types of numerals.
