### ISSUE TITLE
SHACL shape file creates cardinality 1:1 for any attribute.

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#255]
The assumption that each attribute is mandatory is wrong. the default is that attributes are mostly optional and only some are mandatory. This should be documented in the UML file.

**Comment by paulakeen** [comment]
At some point the WG decided not to represent the cardinalities of the class attributes (so not to overcomplicate innecessarily the diagrams, e.g. the cardinalities specified in eForms are different from the ones needed in the Procurement Value Chain).

However, given the fact that the OWL file is being generated from the UML XMI exportation, the absence of cardinality is interpreted by the tool used to draft the UML is 1..1). 

Conclusion, at some point, the whole ePO UML will have to be modified to re-introduce the cardinalities of the attributes. This is an mid-term Action Point. 

For the BDTI purposes, the pilot developers will modify manually their validation artefacts so they adapt the ePO OWL exportation to their needs.
