### ISSUE TITLE
Consistency of eProcurement ontology and eForms requirements

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#256]
elaborating from the previous [issue](https://github.com/eprocurementontology/eprocurementontology/issues/255), the question of whether teh eprocurement ontology should deviate from the eForms arises.

**Comment by paulakeen** [comment]
The ontology should be broader, more flexible in terms of restrictions (less restrictive), so any possible situation in eProcurement, and not only the eNotification from the EU perspective, could be dealt with.

The technical solution is commented in Issue #255 , which consists in specifying the cardinalities of each class attribute.
