### ISSUE TITLE
Glossary: Comparison to other glossaries and definitions

### ISSUE THREAD

**Issue by jpmckinney** [OP-TED/ePO#257]
If I remember correctly, the preparation of the ePO glossary involved comparisons to the definitions of procurement terms published by other organizations (possibly include definitions from the UNCITRAL Model Law, WTO GPA, MAPS, EBRD, etc.).

Was a table or crosswalk comparing definitions prepared? If so, can it be published or shared?

**Comment by muricna** [comment]
Unfortunately, no such table was drawn up.  The definitions were discussed and compared with other organisation definitions in WG meetings this granularity of the meetings was not recorded.  It is indeed something to think about in the future.
