### ISSUE TITLE
Identifier class

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#258]
Going back to the Identifier class, at the time being in the OWL files the Identifier class is defined with the following URI http://www.unece.org/cefact#Identifier that however does not exist in a OWL world. 
This URL http://www.unece.org/cefact# is a web page.
I remember that in the last call it was said that it is taken from ADMS that uses UN/CEFACT for the Identifier. This is not completely true. 
I explain myself better :) The ADMS specifications says that the class Identifier **is based on the UN/CEFACT Identifier complex type** but if you look at the RDF/XML serialization of ADMS, the Identifier class is defined in the namespace of Adms. 
```

<rdfs:Class rdf:about="http://www.w3.org/ns/adms#Identifier">
<rdfs:label xml:lang="en">Identifier</rdfs:label>
<rdfs:comment xml:lang="en" rdf:parseType="Literal">
This class is based on the UN/CEFACT Identifier complex type defined in See Section 5.8 of Core Components Data Type Catalogue Version 3.1 (http://www.unece.org/fileadmin/DAM/cefact/codesfortrade/CCTS/CCTS-DTCatalogueVersion3p1.pdf) In RDF this is expressed using the following properties: - the content string should be provided using skos:notation, datatyped with the identifier scheme (inclduing the version number if appropriate); - use dcterms:creator to link to a class describing the agency that manages the identifier scheme or adms:schemaAgency to provide the name as a literal. Although not part of the ADMS conceptual model, it may be useful to provide further properties to the Identifier class such as dcterms:created to provide the date on which the identifier was issued.
</rdfs:comment>
<rdfs:isDefinedBy rdf:resource="http://www.w3.org/TR/vocab-adms/"/>
<dcterms:identifier>adms:Identifier</dcterms:identifier>
</rdfs:Class>
```
From my point of view we should follow the same approach. We can say that the modelling of the Identifier class **is based on** UN/CEFACT but then define the Identifier in the namespace of epo, then aligned with (subClassOf) the one from ADMS for instance.

**Comment by paulakeen** [comment]
I agree with your proposal, but could we review together if we reuse all the ccts attributes of the CCTS Identifier?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: giorgialodi <notifications@github.com>
Enviado: Wednesday, November 11, 2020 7:35:19 PM
Para: eprocurementontology/eprocurementontology <eprocurementontology@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [eprocurementontology/eprocurementontology] Identifier class (#258)


everis Security Awareness - This is an incoming mail from an EXTERNAL DOMAIN. Please verify sender before you open attachments or access links.

Going back to the Identifier class, at the time being in the OWL files the Identifier class is defined with the following URI http://www.unece.org/cefact#Identifier that however does not exist in a OWL world.
This URL http://www.unece.org/cefact# is a web page.
I remember that in the last call it was said that it is taken from ADMS that uses UN/CEFACT for the Identifier. This is not completely true.
I explain myself better :) The ADMS specifications says that the class Identifier is based on the UN/CEFACT Identifier complex type but if you look at the RDF/XML serialization of ADMS, the Identifier class is defined in the namespace of Adms.


<rdfs:Class rdf:about="http://www.w3.org/ns/adms#Identifier">
<rdfs:label xml:lang="en">Identifier</rdfs:label>
<rdfs:comment xml:lang="en" rdf:parseType="Literal">
This class is based on the UN/CEFACT Identifier complex type defined in See Section 5.8 of Core Components Data Type Catalogue Version 3.1 (http://www.unece.org/fileadmin/DAM/cefact/codesfortrade/CCTS/CCTS-DTCatalogueVersion3p1.pdf) In RDF this is expressed using the following properties: - the content string should be provided using skos:notation, datatyped with the identifier scheme (inclduing the version number if appropriate); - use dcterms:creator to link to a class describing the agency that manages the identifier scheme or adms:schemaAgency to provide the name as a literal. Although not part of the ADMS conceptual model, it may be useful to provide further properties to the Identifier class such as dcterms:created to provide the date on which the identifier was issued.
</rdfs:comment>
<rdfs:isDefinedBy rdf:resource="http://www.w3.org/TR/vocab-adms/"/>
<dcterms:identifier>adms:Identifier</dcterms:identifier>
</rdfs:Class>


From my point of view we should follow the same approach. We can say that the modelling of the Identifier class is based on UN/CEFACT but then define the Identifier in the namespace of epo, then aligned with (subClassOf) the one from ADMS for instance.

**Comment by giorgialodi** [comment]
I would define all the properties derived from the definition of Identifier of ccts in the namespace of our ontology and I would align them to the properties used for Identifier in adms (mainly skos properties).

**Comment by paulakeen** [comment]
Agreed, then.

**Comment by giorgialodi** [comment]
Thanks :) will you close the issue when this is applied?

**Comment by muricna** [comment]
There is a discussion to be had as to how and where this will be applied ie in which version.

**Comment by paulakeen** [comment]
The WG decided not to use the CCTS namespace, bour ePO's one. The documentation, however will explain that the Identifier class is based on the UN/CEFACT CCT specification.
