### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#259]
This page https://eprocurementontology.github.io//Mappings%20HTML%20version/index.htm brings to a 404 error (html version of the diagrams for version 2.0.1)

**Comment by jseguraf** [comment]
Many thanks to report the error. The problem has been solved and now the html version is available: https://eprocurementontology.github.io/CDM_Report/HTML/index.htm

**Comment by muricna** [comment]
The error is still to be corrected

**Comment by jseguraf** [comment]
Sorry I put the wrong url. The new url is https://eprocurementontology.github.io/v2.0.1/HTML/index.htm. As you can see now is more intuitive to know that this is the html version of v2.0.1

**Comment by giorgialodi** [comment]
The first link no longer exists and so it will always produce 404. It has been replaced by the second link mentioned by @jseguraf, correct? In any case, now the html version of epo 2.0.1 is available and it works; I will close the issue.
