### ISSUE TITLE
The related classes of "order" and "delivery note" are missing

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#26]
Claude Schmit said that the related classes of "order" and "delivery note" are missing.

**Comment by makxdekkers** [comment]
These two new proposed classes need to be discussed by the Working Group. It needs to be determined what the definitions of these classes are and how these classes are related to the other classes in the model.

**Comment by eprocurementontology** [comment]
To be covered when we cover eOrdering and eDelivery unless needed in the model before hand.

**Comment by muricna** [comment]
Please look at the eOrdering and eFulfilment modules that are under development.
