### ISSUE TITLE
Properties with multiple (many) domains and multiple (many) ranges

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#261]
The current UML v2.0.2 still drags this problem of poorly named properties, e.g. "has", which causes the generation of an object property linking many domains AND many ranges. This should be corrected when possible in the UML.

**Comment by eprocurementontology** [comment]
The work has been carried out by the WG however it is still to be implemented in the UML and OWL files

**Comment by andreea-pasare** [comment]
This seems not to be an issue in ePO anymore, since we moved from using general properties (e.g. "has") to using more specialized ones.
