### ISSUE TITLE
clarification for award decision and subcontract

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#264]
Could you please clarify which are the relationships between award decision and subcontract? There are many and very general and from my point of view do not make any sense to have so many generic properties between the two concepts.

In the eAward diagram available via html of version 2.0.2 (I am using this because the html version of the diagrams for 2.0.1 is no longer available for issue #259 ) I can see at least these three properties:

- has  inverse of refersToAwardResult
- isReferredToIn from Subcontract to AwardDecision
- isReferredToIn inverse of acceptsProposalOf

In the OWL restriction file of version 2.0.1 that we should use in the BDTI pilot it is not clear which are the restrictions that apply. 

Which one should I use? has between AwardDecision and Subcontract?
In addition, I remember that the usage controlled vocabulary was utilized at least in version 2.0.2 (not in version 2.0.1) in order to define whether subcontracting was used or not. Am I right? I no longer see it.

In a ANAC's dataset we have a flag (true or false) in order to indicate whether a subcontracting is used or not. How can I model this with the properties above for Award Decision and Subcontract?
BTW: the Subcontract is a Contract? Because in the definition seems like this but it is not declared as subClassOf Contract in the model.

**Comment by paulakeen** [comment]
Resolved via establishing the links "epo:Lot epo:isRelatedTo epo:TenderLot, epo:TenderLot epo:proposes epo:Subcontract". 

Any relationship between AwardDecision and Subcontract need to be reviewed at a later time and removed if unnecessary to avoid confusions.

**Comment by andreea-pasare** [comment]
ePO 3.0.1 does not have a Subcontract concept. 
According to WG meeting from 15/02/2022, Subcontract class is deleted because current forms and eForms do not require it, but it can be reintroduced if a use case is provided at a later stage.
