### ISSUE TITLE
Location-realted issues

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#266]
We need to review where and how Location and Address are used. There seems to be a non-unique/harmonised way of treating locations and addresses.

**Comment by muricna** [comment]
After discussion the WG suggests to use the Core Location Vocabulary: 
1.Location only when mentioning areas ie Country or country subentities 
2. Address when mapping addresses so the attribute full address can be used

Therefore the model should be revisited so to reflect the core location Vocabulary in the classes Location and Address and their corresponding predicates which should include predicates to Organisation
The WG also suggests to take into consideration the Geometry class from the Core Location Vocabulary which could be useful when addresses are not avialable ie the position of an Oil rig that is involved in procurement.

**Comment by giorgialodi** [comment]
In the revision of the Consip mapping I am realizing that the properties for LocationCoordinate (that is linked to Address) do not make a lot of sense modelled according to version 2.0.1. We have attributes that distinguish between degrees and minutes but their value is Measure that is composed by a decimal and a unit of measure (that can probably be degree or minute). And honestly I've never seen lat and long expressed in minutes in real data so far. 

Don't you think we can simply this part also in version 2.0.1?

**Comment by giorgialodi** [comment]
Regarding this issue, last summer I tried to design in UML a possible schema for the location part of the epo ontology, stimulated by the BDTI pilot. It was a mix of Core Location Vocabulary and INSPIRE Address specifications. Here there is an example of possible Location modelling considering CLV and INSPIRE.
<img width="1007" alt="GeoModelling" src="https://user-images.githubusercontent.com/24624577/102321700-53d79a80-3f7e-11eb-9f57-66510712b2ae.png">

Just for the discussion :)

**Comment by VladimirAlexiev** [comment]
- `epo:Geometry`: why not reuse GeoSPARQL for geometries? (`asWKT, asGML` and the corresponding datatypes). The above only covers point geometries, and furthermore in a completely non-standard way, so repositories with geospatial support won't index `epo:Geometry`
- spelling mistake: `situatted`
- epo:Identifier should be aligned with adms:Identifier
- epo:Identifier mixes props of an individual identifier and an Identifier Scheme, please move the latter to their own class (we did that in euBusinessGraph).
- merge `Location` and `AddressComponent`: why can't the former have a hierarchy, and the latter have geometries?
- `anyURI` is a XSD datatype, not a prop name. If you want to use such prop, call it `uri` and use a real URL (object prop without range), not a literal

**Comment by costezki** [comment]
Location and Address usage are aligned to Core Location now.
