### ISSUE TITLE
Country Identification class

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#268]
In version 2.0.2 the class country identification has been removed, simplifying a lot the model. We know from issue #266  that we need to fix a few stuff for Locations and Addresses; however, do you think it is possible to align the diagram of version 2.0.1 to the diagram of version 2.0.2, also removing in 2.0.1 the country identification class? This will also remove the class in the OWL files for 2.0.1.

The countrycode will point to the controlled vocabulary country and we do not need the class country identification, that is BTW mandatory for the address in version 2.0.1.

Thanks a lot in advance.

**Comment by paulakeen** [comment]
The class CountryIdentification has been removed from v2.0.1 (in v2.0.2 it had already been removed).
