### ISSUE TITLE
Testing Reifications: remove epo:isResponsibilityOf between Procedure and Buyer

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#269]
In the diagrams of the EAP file where the WG is testing reifications, the bi-directional property betwen Procedure and Buyer (isResponsibilityOf/ResponsibleFor) should be removed, since roles are now connected only to the reification ProcurementSituation, and what matters actually is knowing who is the Agent playing the Role of Buyer. A solution for this situation needs to be proposed too.
 
![Captura de pantalla 2020-11-24 a las 13 44 40](https://user-images.githubusercontent.com/16134316/100096445-500f9700-2e5c-11eb-9296-093c7f1a76c0.png)

**Comment by muricna** [comment]
This is only in the reification model we are currently discussing.  This must not be done in the v2.0.1 and V2.0.2.

**Comment by paulakeen** [comment]
Although the reifications could make believe that this property is unncessary, there circumstances where it is necessary to link the procedure to the Agent that plays the role of Buyer. Therefore, the WG has decided to have a birectional predicate between Agent and Procedure "epo:hasBuyerResponsibilityFor/epo:isBuyerResponsibilityOf".

Versions 2.0.1 and 2.0.2 remain unchanged, as far as the property "epo:isReposibleFor/isResponsibilityOf" between Buyer and Procedure is concerned.
