### ISSUE TITLE
Groups of "Contracting Authority" should be expressed

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#27]
Claude Schmit raised the issue that several groups of "contracting authority" should be expressed : "joint call for tender", "in the name of" (or "on behalf of") and "central purchasing body".

**Comment by JachymHercher** [comment]
I'm not sure what "in the name of" (or "on behalf of") exactly means. In the old procurement directives, "on behalf of" was used as an umbrella term for "occasional joint procurement" and "central purchasing body". 

("on behalf of" should also not be confused with the relationship between buyer and procuringEntity, as discussed in #6).

**Comment by makxdekkers** [comment]
In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017), a distinction is made between the Procuring Entity and the Buyer. 
If the situation can occur that the Call For Tender is published by more than one organisation, there may need to be a 1..n relationship between Call For Tender and Procuring Entity, or a particular type of Procuring Entity might be a grouping of organisations.
This issue needs to be further discussed in the Working Group.

**Comment by muricna** [comment]
What is more there can be more than one buyer - joint procurement

**Comment by makxdekkers** [comment]
For all the "Agent" entities in the model both single organisations and groups of organisations should be allowed. Both FOAF http://xmlns.com/foaf/spec/
and the Organization Ontology https://www.w3.org/TR/vocab-org/ have mechanism to describe groups with members.

**Comment by ocorcho** [comment]
I would prefer using the Organization Ontology for this purpose. This is a personal preference over FOAF.
