### ISSUE TITLE
Wrong cardinalities in UML model 

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#271]
This issue to register all cardinality issues encountered in the UML model:

1. procedure isSummarisedBy 1 and only 1  CAN only is wrong 

procedure may not yet be summarized by a CAN and several CAN may exist (in case of Corrigendum ) or Lots that are awarded at different moments in time?

2. hasOptionsPermission cardinality 1 seems irrelevant

**Comment by jseguraf** [comment]
- procedure isSummarisedBy 1 and only 1 CAN only is wrong: The WG decided to change the cardinality 0..*
- hasOptionsPermission cardinality 1 seems irrelevant: The WG decided to change the cardinalities to 0..1

**Comment by eprocurementontology** [comment]
Only the second one of the two changes appears to have been made.

**Comment by muricna** [comment]
The first one was only corrected in one direction

**Comment by andreea-pasare** [comment]
The latest version of ePO, 3.0.1, contains the following relations:

- 1 Notice refersTo only 1 Procedure. 
- hasOptionsPermission was renamed to hasVariantPermission, with a 0..1 cardinality
