### ISSUE TITLE
Version 2.0.1 (probably other versions too) - typo in a property name

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#273]
The property between award decision or lot and contract named "isReferedByA" should be renamed in "isReferredByA" (double r).

**Comment by jseguraf** [comment]
The property has been corrected, you can see a new update of the v2.0.1: https://eprocurementontology.github.io/v2.0.1/HTML/index.html

Here you also have the BDTI hmtl version: https://eprocurementontology.github.io/BDTI/index.html

**Comment by muricna** [comment]
I cannot find this property I only find RefersTo

**Comment by giorgialodi** [comment]
@muricna if you go to Contract diagram and look at the Contract class you can see it. In any case, as @jseguraf the property seems correct now. So we can close the issue

**Comment by muricna** [comment]
Sorry I was looking at Lot instead of Contract
The correction still needs to be made in v.2.0.2

**Comment by giorgialodi** [comment]
Ok so we need to keep it open :)

**Comment by eprocurementontology** [comment]
2.0.2 does not need to be corrected as it will not be released and 2.0.1 is our baseline now.
