### ISSUE TITLE
Description of the property hasMaximumNumberOfAwardedTenderers

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#274]
The description of the property says

Maximum number of tenderers who may be awarded a contract within the framework agreement.
Additional Information: the number is a positive integer.

However, the type of the property is epo:Quantity that can have a value and a unit. The value of the quantity is a decimal (because it is epo:Numeric).

Proposed resolution: either we remove the additional information part of the description or we use epo:Integer as type of the property

**Comment by jseguraf** [comment]
Agreed with the WG to change from epo:Quantity to epo:Numeric

**Comment by eprocurementontology** [comment]
Implemented in 2.0.2 but not in 2.0.1 to be applied in next version

**Comment by andreea-pasare** [comment]
In the latest ePO release, 3.1.0, this attribute is named epo:hasMaximumParticipantsNumber, type xsd:integer as depicted below:
![image](https://user-images.githubusercontent.com/88081600/221532020-21f35dd6-9dcf-4c8d-a6ad-c17433bae32f.png)
