### ISSUE TITLE
Range type of the defined OWL restrictions

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#276]
In the OWL restrictions file, when restrictions are defined, only cardinality constraints are provided, no specific range type is defined in the restriction itself. I am referring to [this specific issue](https://github.com/meaningfy-ws/model2owl/issues/70). 

The action here is to check with an automatic reasoner if this causes problems, if it infers what infers Protégé when the type of the range of the restrictions is not specified. 
If so, then this has to be changed in the OWL restrictions file (acting on the transformation scripts from UML to OWL). 
If it does not create any problem, the above reported issue in the other repository will be closed.

**Comment by eprocurementontology** [comment]
This is covered by [model2Owl issue 89](https://github.com/OP-TED/model2owl/issues/89) and[model2OWL issue 91](https://github.com/OP-TED/model2owl/issues/91)
