### ISSUE TITLE
Mapping between ePO and eForms?

### ISSUE THREAD

**Issue by ColinMaudry** [OP-TED/ePO#277]
Hello,

With the OCP we're conducting a comparison of terms and semantics across reference glossaries/standards/formats.

Since ePO was meant to be a resource for the development of eForms, we would like to know if some sort of mapping has been done between ePO terms and eForms BTs/BGs.

More generally, we're interested in any mapping you may have done with another standard.

Thanks!
cc @jpmckinney @jachymhercher

**Comment by muricna** [comment]
Please see: 
https://github.com/eprocurementontology/eprocurementontology/blob/v2.0.2/v2.0.2/03-Analysis%20and%20design/eForms2ePO/Ontology_eForms_Mapping_New%20Regulation.xlsx
which is a draft and not final
