### ISSUE TITLE
hasFulfillsRequirement property name

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#283]
The name of the property does not make sense. It should be fulfillsRequirement only, without "has". I think this issue derives from the general conventions for the automatic transformation in OWL from UML.

The property is used in the GreenProcurement class, subclass of StrategicProcurement

**Comment by guascce** [comment]
this could be solved by making an exception not adding the 'has' verb when the predicate links to skos concept  In the naming convention, the name of the property in the class needs to contain a verb.

**Comment by andreea-pasare** [comment]
In ePO 3.0.1, the predicate hasFulfillsRequirement is renamed into epo:fulfillsRequirement.
