### ISSUE TITLE
Stick to class naming convention

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#288]
#281 shows class names that don't start with uppercase.
Please stick to the naming convention!

Why:
1. A good naming convention for props is to name them by the target class. That's used in various w3c ontologies, and in AKSW ontologies.
  - Because the class naming convention is not applied, I had to use a modified prop name:
    `ecat:eCatalogue epo:catalogueLine epo-ecat:eCatalogueLine`
  - If you stick to the class naming convention then I can use a systematic prop name:
    `ecat:ECatalogue epo:eCatalogueLine epo-ecat:ECatalogueLine`
2. It's the way to tell that something is a class by just looking at the name

**Comment by guascce** [comment]
We agree with you. These classes were defined in a discussion with TC440 members not yet applying our naming conventions and sticking to the TC440 glossary. The TC440 community agrees to align with the ePO naming conventions so when these classes become incorporated, they will be named following the ePO naming conventions.
