### ISSUE TITLE
Many types of notices, "Contract Award Notice" is not a standalone class

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#29]
Claude Schmit said that there are many types of notices, "contract award notice" is not a standalone class : probably we need a class "notice" with sub classes "award", "contract", "prior", …

**Comment by makxdekkers** [comment]
If there is a set of properties that apply to all those ‘notices’, there could be a superclass for it. However, it needs to be determined what the role of such a superclass is in the model. 
This needs to be further discussed by the Working Group.

**Comment by JachymHercher** [comment]
There are definitely some properties shared by all these notices. Mainly, they all get published. Secondarily, they will all likely share some information (e.g. buyer, publisher).

**Comment by noeclai** [comment]
And they all share the description of the procurement and CPV code (then linked to 'Product or service or Work' class and indirectly also to 'Classification' and 'Specification' classes. Then I agree with Claude 's proposal.
