### ISSUE TITLE
produce ttl

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#291]
RDF XML is the least readable of the RDF serializations.
In the final rendition you should make the ePO available in html (generated with eg LODE), JSONLD, Turtle, RDF XML. With content negotiation.

But for now could you please produce Turtle, which is easiest to read? It's very useful for quick checks, eg are all namespaces reasonable.

There is a variety of tools to convert rdf->ttl; I use RIOT but there's also the https://rdf-translator.appspot.com/ service.

Bonus if you can sort prefixes (by line); and sort terms (by "paragraph", i.e. turtle block).

**Comment by guascce** [comment]
We will try to address your request in the next version of the UML2OWL code.

**Comment by VladimirAlexiev** [comment]
Duplicated as #392.
@guascce why not use an external tool like jena `riot` rather than enriching the UML2OWL  generator?

**Comment by dbd311** [comment]
Hi, we use rdfpipe to convert to turtle.
This will be available in the next release.
