### ISSUE TITLE
Glossary? No, "UML model" and "data dictionary"

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#292]
The [wiki](https://github.com/eprocurementontology/eprocurementontology/wiki/) starts with links to two very useful resources:

>**Glossary**
> [ePO Glossary](https://github.com/eprocurementontology/eprocurementontology/wiki/eProcurement-Glossary-v2.0.2)
>- Access to the HTML version of the ePO model
>- Download here the ePO Glossary

But neither of these is a glossary (which is a list of terms or abbreviations), they are a lot more detailed resources.
So I nearly missed them! I suggest to rename them as follows:

>**Model**
> ePO Data Model:
>- UML Model (HTML version)
>- Data Dictionary (Excel)

Thanks!

**Comment by guascce** [comment]
There is an ongoing revision of the wiki. We will take your comment into account.

**Comment by AchillesDougalis** [comment]
Although by following the provided links this issue appears to be solved, we would suggest the [eProcurement Ontology Documentation page](https://docs.ted.europa.eu/EPO/latest/index.html)  to anyone seeking information related to the ePO glossary, or the conceptual models.
