### ISSUE TITLE
reg2015-owl-core mixes up label and namespace, (re)defines terms

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#293]
Checking https://github.com/eprocurementontology/eprocurementontology/tree/v2.0.1/v2.0.1/02-Analysis%20and%20design/OWL 

reg2015-owl-core (converted to ttl):

- `<http://data.europa.eu/a4g/extension/ontology> a owl:Ontology` but cannot you have multiple extensions of ePO? Shouldn't the namespace be `a4g/reg2015` instead of `a4g/extension` ("extension" is a generic word)
- `@prefix epo:   <http://data.europa.eu/a4g/extension/ontology#>` is wrong because that's the prefix of the main ontology
  - same for `vann:preferredNamespacePrefix  "epo"`
- `rdfs:label "eProcurement core ontology"@en ;` is wrong
- I think you should add `epo:` to `owl:imports` because if reg2015 extends the ePO ontology, it should import it
- `<http://data.europa.eu/a4g/ontology#AwardCriterion> a owl:Class`: reg2015 has no business defining terms from ePO (this is called "namespace hijacking". It can refer to them (eg as `subClassOf`) but should not (re) define them

**Comment by eprocurementontology** [comment]
We will look into this in a future update.

**Comment by andreea-pasare** [comment]
We no longer use Reg2015. The model ePO 3.0.1 is unified to cover standard form use cases and eForms use cases.
