### ISSUE TITLE
dash or underscore in file name?

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#294]
Generated ontology files use inconsistent delimiter: `ePO-owl-core, ePO_restrictions, ePO_shacl_shapes`. 
Please pick one and use it consistently.

**Comment by guascce** [comment]
Thank you for spotting this. We will streamline the the file naming convention the next release.

**Comment by andreea-pasare** [comment]
In the latest version of ePO, 3.0.1, only underscore delimiters are used for the owl output files. The files can be found at the following location, under owl_ontology and shacl_shapes folders:
`https://github.com/OP-TED/ePO/tree/v3.0.1/implementation/ePO`
