### ISSUE TITLE
Contracting Authority class

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#3]
The directive 23 relates to Contracting authorities and Contracting entities.  There needs to be a definition that cites contracting authorities and Contracting entities.  Suggestions have been made to use the term by "buyer" or "Contracting body".  However it is not necessarily as simple as that as a contracting authority is not equal to a contracting entity as although they are both buyers they buy different things.

**Comment by makxdekkers** [comment]
We need to agree on a term on a sufficiently general level so that the definition can include all kinds of contracting bodies that engage in procurement. 'Contracting body' could maybe serve that purpose. 'Buyer' might be too general?

**Comment by rantati7** [comment]
In eForms consultation the term "Buyer" was used for simplification,

**Comment by muricna** [comment]
Yes this is true.  We need to discuss the granularity we need to go to for example the main activity of a contracting authority is not equal to that of a contracting entity.  I notice in the document e-Government Core vocabularies handbook (https://joinup.ec.europa.eu/community/semic/news/e-government-core-vocabularies-handbook-has-been-update) the term buyer is used but so is customer.  Also in the meeting Makx you suggested that terms like similar to etc  could also be used.

**Comment by makxdekkers** [comment]
If 'Buyer' is a sufficiently neutral term, we could use that as the label for the class. The definition can refer to  various other terms that are similar.

**Comment by gretamolnar** [comment]
I agree with Makx, we should use 'Buyer' or 'Contracting Body' as a label for the class instead of Contracting Authority or Contracting Entity. I don't think 'Buyer' is too general, for simplification it might be the most usable term.

**Comment by JachymHercher** [comment]
I agree with buyer (or perhaps "public buyer"). 

(Just for the record, please note that there are buyers in public procurement which are not contracting authorities nor contracting entities, e.g. buyers awarding a contract subsidized by a contracting authority in line with 2014/24/EU Art. 13.)

**Comment by makxdekkers** [comment]
The latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017) has the class Buyer with subclasses Contracting Authority, Public Undertaking and Other Contracting Entity (as per Directive 2014/23/EU, art. 7.1).

**Comment by JachymHercher** [comment]
Few comments on this:
- The buyer type mentioned in my comment above is missing. ("Buyer awarding a contract subsidized by a contracting authority" For more information, see 2014/24/EU Art. 13.) 
- I don't think we should use "Other Contracting Entity" so broadly. I would suggest we strive to explicitly name at least all the concepts from the procurement directives, and leave "other" for unforeseen cases, if at all. This means adding a "Buyer operating on the basis of a special or exclusive right". (For more information, see 2014/25/EU Art. 4 (3), 2014/23/EU Art. 5(10-11) ). 
- Both "public undertakings" and "buyers operating on the basis of a special right" can, legally, be bodies governed by public law and thus also contracting authorities at the same time. For this reason, the description of both of these concepts should specify 'except bodies governed by public law'. 
- I'm not sure if international organisations fall into any of the existing categories, it depends on how they are defined. It might be worth creating a special category for them.

**Comment by muricna** [comment]
See also my comment to issue #20

**Comment by muricna** [comment]
The buyer should not relate only to 2014/23/EC it needs to be related to all 3 directives.  What is more this needs to be done in a way that we do not to close the door for procurement below the threshold.

The term Contracting entity seems to be missing. If the definition of buyer is equal to that of Contracting entity this would mean that the contracting authority is a  subclass of contracting entity and in fact that should have equivalent status.

**Comment by JachymHercher** [comment]
@muricna I don't think Contracting Entities are really of an equivalent status to Contracting Authorities. The definition of a contracting entity is that it is a specific type of Contracting Authority; a Public Undertaking; or operates on the basis of a special or exclusive right. Thus, I would put Contracting Entity separately. 

(It could perhaps be a separate class linked to the terms above. It's main, or perhaps only, property is that a contracting entity does not have to follow the general procurement directives).

**Comment by muricna** [comment]
I agree with you what I meant was perhaps parallel rather than equivalent if I explained myself more clearly.  I find it difficult to describe the buyer as a contracting enitity and contracting authority a subclass of this.
What I was proposing was Class Buyer with subclasses contracting authority and contracting entity if not more to cover certain scenarios

**Comment by JachymHercher** [comment]
Essentially, I don't like either option. I agree that contracting authority as a subclass of contracting entity is incorrect. However, I wouldn't put the two next to each other either - contracting authorities can be a subclass of contracting entities. 

Perhaps we should have "contracting entity" as a separate class and use relationships of "can be" and "is a type of "  to link it to types of buyers? This means triplets like "contracting authority" 'can be' a "contracting entity" and "public undertaking" 'is a type of' 'contracting entity'? I have no idea if this is a useful way of modeling things though.

**Comment by eprocurementontology** [comment]
Following the meeting of 19-21 February it was decided: 

The model of the buyer needs to be further broken down to show the   contracting authorities, contracting entities and other.
--


This needs to be worked on taking into consideration the buyer legal type BT-11 in the eForms and the attached drafts.
![Buyer legal entities](https://user-images.githubusercontent.com/26460487/56910299-892e2c80-6aaa-11e9-8fd6-8a1c5de6452a.PNG)
[Legal entity types.pptx](https://github.com/eprocurementontology/eprocurementontology/files/3128222/Legal.entity.types.pptx)

**Comment by jseguraf** [comment]
The model has been updated accordingly.
