### ISSUE TITLE
Difference between "Procurement Criterion" and "Tendering Terms" (UBL)

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#30]
Claude Schmit asked about the difference between "procurement criterion" and "tendering terms (UBL)" ? Are the first computable metadata and the second textual description about what is requested in the "call for tender" ?

**Comment by makxdekkers** [comment]
There is no direct correspondence between the Procurement Criterion here and UBL. The UBL Tendering Terms combine ‘computable’ conditions (e.g. for Quantities, Codes and Indicators) and textual descriptions. Procurement Criterion may also include both types of criteria.
The UBL definitions could be taken into account when further detailing the Procurement Criteria.
