### ISSUE TITLE
latest version and tracker?

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#303]
@giorgialodi replied to several of the issues I posted that they are under discussion or in progress.

To avoid posting issues that are already being discussed, should I be looking at a newer version than release 2.0.1, and is there another tracker where I should be checking?

**Comment by giorgialodi** [comment]
In OWL, there is currently only version 2.0.1 and some extensions for some pilots. This version has some issues we are aware of as working group. That's why we are currently working to a new version where also roles, organisations and context is treated in a different way.

**Comment by VladimirAlexiev** [comment]
@giorgialodi I guess that UML model and issues from discussion are not available outside of the WG?

**Comment by giorgialodi** [comment]
@VladimirAlexiev ni :) Obviously in the WG there are discussions that are also raised from some practice of the people of the WG, however, the WG is open to anyone and other issues are already reported in this repo (e.g., location, general properties that bring to semantic inconsistences,  hasFulfillsRequirement prop, Value class issue, and others if you look at the list of issues). 
The new version is still not available online ( I mean the OWL is still to be produced) and only the WG knows it (e.g., the WG knows the changes that have been applied to props like "has", "isReferredByA", etc.). In any case, In the wiki of this repo you can find the minutes of all our meetings with the decisions that we take during every meeting. Therefore, there is knowledge there as well on the on-going work.

**Comment by giorgialodi** [comment]
For example, here https://github.com/eprocurementontology/eprocurementontology/wiki/Meeting-Minutes you can find at the top the discussion on Value, etc.

**Comment by eprocurementontology** [comment]
As mentioned in previous issues we are working on a new version that we hope to publish by the end of the year.  This version will take into consideration updates to definitions and predicates as noted in the minutes.  The reification will also be addressed and working of this can be consulted at: https://github.com/eprocurementontology/eprocurementontology/tree/v2.0.2/v2.0.2/05-Implementation/test/roles-as-classes

**Comment by VladimirAlexiev** [comment]
The above link is no more, but detailed meeting minutes are at
https://docs.ted.europa.eu/epo-wgm/index.html

Thanks!
