### ISSUE TITLE
Role-ContactPoint props, discrepancy between ontology and conceputual model

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#305]
- The conceptual model https://eprocurementontology.github.io/v2.0.2/index.html?goto=1:43 shows
`Role->has->ContactPoint`
- The ontology release 2.0.1 shows two props whose names don't make much sense:
```ttl
epo:hasContactPersonRole
        rdfs:domain    epo:ContactPoint ;
        rdfs:range     epo:Role ;
        owl:inverseOf  epo:isPersonOfContact .
```

- ContactPoint has no relation to Person and indeed there may be nothing personal in the contact details
- What is "PersonOfContact"? That's not at all the same as "ContactPerson"

Such confusions would be avoided if the simple prop naming convention (mirroring fo the range) is adopted:
- `Role->contactPoint->ContactPoint`
- `ContactPoint->role->Role`

**Comment by eprocurementontology** [comment]
Your concern is justified and will be taken into consideration in the reification as per [github issue 306](https://github.com/eprocurementontology/eprocurementontology/issues/306).
Specific attention will need to be paid to the relationships between Channel and ContactPoint

**Comment by andreea-pasare** [comment]
In the latest ePO version 3.0.1, we are using the relation `hasContactPointInRole` between `AgentInRole` and `ContactPoint`, as depicted  in the following diagram:
![image](https://user-images.githubusercontent.com/88081600/195369306-7acebe7e-3942-4cab-88ae-4ff1472166e3.png)

Also, in the RDF files of ePO version 3.0.1 we are using the same name for this property: `https://github.com/OP-TED/ePO/blob/v3.0.1/implementation/ePO/` under `owl_ontology` and `shacl_shapes` folders.

**Comment by VladimirAlexiev** [comment]
This makes sense!

But what are the other relations of `AgentInRole`? I guess they are omitted from the diagram, but exist in the overall model?

**Comment by andreea-pasare** [comment]
Yes, you can see below the "role relations" diagram from our development branch:
![image](https://user-images.githubusercontent.com/88081600/200338414-f7b208e0-8244-416b-ba8f-cd945a4d7dfa.png)

Note: In ePO version 3.0.1 we had `epo:PrimaryRole` and `epo:SecondaryRole` as subclasses for `epo:AgentInRole`. For the future release it is proposed to have as subclasses for epo:AgentInRole the following: `epo:OfferingParty`, `epo:AquiringParty` and `epo:AuxiliaryParty`.

**Comment by VladimirAlexiev** [comment]
thanks @andreea-pasare , now all makes sense!
