### ISSUE TITLE
Link of Role to Procedure?

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#306]
The name `Role` suggests, and examining it in the conceptual model https://eprocurementontology.github.io/v2.0.2/index.html?goto=1:43 confirms, that it must be relative to some tendering procedure.
Eg its subclass `EconomicOperator` has а key field `hasEORoleType` and its values `SOLE contractor` vs `Lead Entity` are relative (the same legal entity can have different role types in different Procedures).

But I have the following concerns:
- The link of `Role` to `Procedure` is too low in the subclasses of `Role` and is specific to the subclass, eg
  - `Buyer->isResponsibleFor->Procedure` 
  - `Tenderer->submits->Tender->includes->TenderLot->relatesTo->Lot->isSpecifiedIn->Procedure`
  - This leaves questions of identity, eg can the same legal entity submit two different lots of the same Procedure while using two different Roles?
- Some fields like `hasEconomicOpratorSize` are independent of particular Procedures (although are dependent on time), so is it right to have them in a subclass of `Role`?

**Comment by eprocurementontology** [comment]
Your concerns are justified and will be addressed when we adopt reification in the next version.  Our initial workings on reification are depicted below:  
![image](https://user-images.githubusercontent.com/26460487/126332123-4d2efbee-2068-47e3-bbca-3d92182c7ed7.png)
The workings can be consulted at : https://github.com/eprocurementontology/eprocurementontology/blob/v2.0.2/v2.0.2/05-Implementation/test/roles-as-classes/ePO-CM-roles-as-classes.eap

**Comment by VladimirAlexiev** [comment]
hasContext points to Procedure, Tender, Contract etc?

**Comment by giorgialodi** [comment]
This is the general pattern and it can point to different contexts according to the different procurement situations. The idea here is that to avoid the mix of semantic concepts between roles (that are not agents) and agents and to create the conditions to say that in a specific procurement situation (in a specific context and during a certain period) agents play some roles

**Comment by costezki** [comment]
As of 3.0.1 we have two relations from epo:Procedure to epo:Buyer  now:
* epo:involvesBuyer
* epo:isResponsabilityOfBuyer

![image](https://user-images.githubusercontent.com/13567133/205345037-3c82761c-b107-4a60-b854-f700d11dedd5.png)

**Comment by VladimirAlexiev** [comment]
@costezki can you point to the relevant diagrams once 3.0.1 is published? 
I want to recheck all bullets that I raised.

**Comment by andreea-pasare** [comment]
@VladimirAlexiev, the diagrams for ePO 3.0.1 are available at the following link: https://docs.ted.europa.eu/EPO/3.0.1/ePO-core-Conceptual-Model-v3.0.1.html.
