### ISSUE TITLE
Subcontractor vs hasSubcontracted

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#307]
The conceptual diagram https://eprocurementontology.github.io/v2.0.2/index.html?goto=1:43 shows
- `Subcontractor<EconomicOperator<Role` (here "<" means "subClassOf")
- `Contractor<Winner<Tenderer<EconomicOperator<Role`
- link `Contractor->hasSubcontracted->Agent`

I would expect `hasSubcontracted` to relate somehow to `Subcontractor`.
This relates to #306 because it mixes up procedure-relative agents (`Role` etc) with absolute Agents

The ontology release 2.0.1 doesn't define class `epo:Subcontractor` nor prop `hasSubcontracted`, and has just this:

```ttl
epo:proposesSubcontractor
        rdfs:domain  epo:Subcontract ;
        rdfs:range   epo:Subcontractor .
```

**Comment by eprocurementontology** [comment]
In version 2.0.1 (latest released version) there is no relation between Subcontractor and Contractor
In version 2.0.2 (working model not to be released as an OWL resource) a relation between Subcontractor and Contractor was created via the Agent.
In the next version to be published as an OWL resource we intend to introduce reification that will represent the role of an agent in a specific context and this relationship between Subcontractor and Contractor will be taken into account.

**Comment by costezki** [comment]
The role hierarchy has been reworked. 
Now the Contractor and Subcontractor roles are siblings. 

![image](https://user-images.githubusercontent.com/13567133/205343715-36e619d2-5450-4f8a-867f-54aaf49ec7d1.png)
