### ISSUE TITLE
Add headings to Minutes

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#308]
https://github.com/eprocurementontology/eprocurementontology/wiki/Meeting-Minutes is very useful but you can't point to specific sections. 

Please change eg
```
-----
Please find below the minutes from 10 June 2021
```

To proper h1 sections eg
`# 10 June 2021`

Then optionally add h2 headings to important topics within the dated h2 sections.

**Comment by guascce** [comment]
We will consider your suggestion in the ongoing Wiki maintenance

**Comment by andreea-pasare** [comment]
Proper headings have been added to the working group meetings minutes. The new format can be reviewed [here](https://docs.ted.europa.eu/epo-wgm/wgm-2022.html).

**Comment by VladimirAlexiev** [comment]
Thanks, this is very useful!
And the overall index for all the sub-WGs and the face2face presentations is also very useful:
https://docs.ted.europa.eu/epo-wgm/index.html
