### ISSUE TITLE
(re-)organize & unify the repository documentation

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#309]
To make it clearer we currently have:
* the antora site generated by the re-organised repository
  * The URL for this site is https://eprocurementontology.github.io/eprocurementontology
  * The source of this site is here (gh-pages branch) https://github.com/eprocurementontology/eprocurementontology/tree/gh-pages
* the eprocurementontology.github.io site coming from the "past"
  * The URL for this site is https://eprocurementontology.github.io/
  * the source of this site is here (eprocurementontology.github.io repository) https://github.com/eprocurementontology/eprocurementontology.github.io
  
---

One option would be to transfer the ownership, but then, later, to merge the two contents as necessary/appropriate. When the manual merge is done, we delete/archive the unnecessary repository.  

---

Yes probably we will move the content to the other site but we need to take a look at it first and consider how it will work. For example, the other site contains files generated by Sprax EA. We need to think about how will publish these things in the future

---

For a start: we could try to continue the tradition.

---

Also from the title I would expect these two pages to have the same content but they don't, so we need to figure out which one is the correct one:
old site: ePO - eProcurement Ontology 2.0.0 [Report] https://eprocurementontology.github.io/
new site: ePO - eProcurement Ontology 2.0.0 [Report] :: EPO  https://eprocurementontology.github.io/eprocurementontology/EPO/2.0.1/index.html

---

If you mean the tradition of publishing these Sparx EA generated HTML pages, then I agree. I think they are useful.

**Comment by andreea-pasare** [comment]
All documentation regarding ePO has been transferred to https://docs.ted.europa.eu/ having the Github repository in https://github.com/OP-TED/epo-docs.
