### ISSUE TITLE
Insert useful code lists

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#31]
Claude Schmit proposed that useful code lists could already appear based on the use cases : CPV(+supplementary code), NUTS, contract type, procedure type, country, … Code lists can have 1..n cardinality and should be identified as enumeration pseudo-classes.

**Comment by JachymHercher** [comment]
I'm not sure what enumeration pseudo-classes are, but I expected that codelists would rather be covered by the "data type" section of "properties"? 

(E.g. we would have a property "hasCountry" which would have as data type the values in the ISO 3166-1 alpha-2 codelist. This means that e.g. "BE" (for Belgium) would not be a class, but rather a textual value.)

**Comment by makxdekkers** [comment]
The current modelling does not use 'code lists' in the sense of short strings like ISO 3166-1 country codes, CPV codes or NUTS codes, but works from the principle that the things that the codes stand for are identified by URIs. 
In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017), CPV is mentioned as the recommended controlled vocabulary for Classification, and NUTS is recommended as the controlled vocabulary for Country. Belgium would be identified by http://data.europa.eu/nuts/code/BE (note that a Linked Data pilot is currently being conducted and persistent URIs do not yet exist) or by http://publications.europa.eu/resource/authority/country/BEL.

**Comment by muricna** [comment]
Both the country code and the NUTs code are used in the notices so both need to be foreseen.  The country codes can be taken from MDR

**Comment by ocorcho** [comment]
I am very much in favour of using URIs for all those codelists. The more that we can refer to, the better. Obviously, better if they are official (e.g., from Eurostat). They should all be SKOS concepts in SKOS concept schemes.

**Comment by eprocurementontology** [comment]
MDR which is now EU vocabularies see: `[https://publications.europa.eu/en/web/eu-vocabularies/authority-tables] uses URIs for the concepts
