### ISSUE TITLE
Role - update definition

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#313]
Role: A part played by an agent in a particular business process.
Additional information
In ePO, the 'business processes' related to procurement can be 'purchasing', 'tendering', 'evaluating', 'awarding', 'ordering', 'invoicing', etc. 
The concept of 'role' is different from the concept of 'function'. However, functions can be carried out by procurement-related roles and other domain-related agents. Please refer to the class 'Function' to see the difference.

Remove last paragraph in Additional Information.  We no longer have functions in the ontology

**Comment by andreea-pasare** [comment]
In the latest version, ePO 3.0.1, the concept of AgentInRole is used with the following definition:

_Relative concept that ties an agent to a part they play in a given situational context._

_Additional information:
The classification of roles is based is based on the degree of involvement into the procurement process:_
_- Primary (Procurement) role is directly involved in the procurement process;_
_- Secondary (Procurement sub-)role is secondary to the procurement process_
_- Tertiary (Related) role is not involved in the procurement process._
