### ISSUE TITLE
hasMainClassification and hasAdditionalClassification in the purpose - cardinalities

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#314]
In the diagram Procedure accessible via HTML the attribute epo:MainClassification of the class Purpose has cardinality 0..1 while the corresponding property to the CPV controlled vocabulary (green box) has cardinality 1..*.

We said this modelling should be revised, but I think we first need to align here the cardinalities. The MainClassification should be 1, as far as I've understood.

**Comment by andreea-pasare** [comment]
This was fixed when we decided to remove all epo:Code type attributes and keep only the dependency relations between classes and controlled vocabularies.
