### ISSUE TITLE
Legal registration information of organizations (catalogue provider/receiver)

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#315]
In the context of a eCatalogue, the following information with respect to the legal registration (in a business register) of the Catalogue Provider and the Catalogue Receiver:

* Registered name of the Catalogue Provide/Receiver
* Registration Id of the of Catalogue Provide/Receiver
* Registered address of the Catalogue Provide/Receiver (optional)

Righ now I could not found anything related to this kind of information.

For details, see also the Peppol BIS

https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-ProviderParty/cac-PartyLegalEntity/
https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/tree/

**Comment by costezki** [comment]
**Registered name of the Catalogue Provide/Receiver**
We have added the attribute *epo:hasLegalName* to the class *epo:Organisation*

**Registration Id of the of Catalogue Provide/Receiver**
The attribute *epo:hasID* in the class *epo:Agent* can be used for this purpose. The identifier class contains several attributes concerning the scheme used. 

**Registered address of the Catalogue Provide/Receiver (optional)**
We have added the *epo:hasLegalLocaltion* relation from *epo:Organisation* to *epo:Location* class.

**Comment by idolum** [comment]
@costezki My apologies for the late reply! Thank you for adding this to the ePO. Should work for us right now.

**Comment by muricna** [comment]
I see epo:hasRegisteredAddress instead of epo:hasLegallocation other predicates seem ok

**Comment by muricna** [comment]
Agreed with idolum 20/01/2022
