### ISSUE TITLE
Roles and Address and contract Point of agents

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#316]
In the eCatalogue, there are the roles Catalogue Provider, Catalogue Receiver, Buyer and Seller. In the eCatalogue, information is provided on the address on the agent/organizations playing the mentioned roles as well as the contact point of agent/organizations which play the roles of Buyer and Seller. Right now the model would look like this

![image](https://user-images.githubusercontent.com/1178743/139416228-481b341b-332c-4636-bfcc-ff7526ecdbc4.png)

This covers this aspects not fully, because the Catalogue Provider etc. has only an indirect association to the Address. Is this something, that should be defined in the ePO somehow? In terms of an inferred association?

**Comment by giorgialodi** [comment]
Hi @idolum this is a fundamental point in semantic models. The Catalogue Provider is just a role, a part played by an Agent (e.g., an organisation) in a specific context. The address i**s not of the role**, but rather of the Organisation playing the role of CatalogueProvider in a context. 
Just to clarify better. Organisation X is a CatalogueProvider in a context and is located in Street ZZZ, number 666. If the same organisation X plays the role of CatalogueReceiver in another context, its address does not change, it remains the same independently of the role the organisation plays in some procedures.

Hope this clarifies.  This means that 'attaching' the Address directly to a role for me does not make sense.

**Comment by idolum** [comment]
Hi @giorgialodi, thank you for your feedback. I do not question the model and you clarified it perfectly. My concerns on context specifc restrictions. For example. in the eCatalogue I want express restricitions like

* An Organisation that plays to role of the Catalogue Provider needs to have a Location which has an Address
* An Organisation that plays to role of the Catalogue Receiver needs to have a Location which has an Address

and so one  for Buyer and Seller. The use case behind this is that providing the Address of the Catalogue Provider/Receiver in an eCatalogue is mandatory. Or are these kind of restriction out of scope of the ePO and I define them in whatever I create on top of the ePO?

Another aspect is to define a "shortcut concept". For example, Catalogue Provider Address, which is the Address of the Location which belongs to the Organisation that plays the Catalogue Provider role.

So, my question is not about the semantic and the semantic structure, but on restrictions on top of that.

**Comment by costezki** [comment]
The ontology must cover as many pre-award and post-award use cases. The restriction you mention above is specific to the catalogue use case and therefore need to be dealt with in a dedicated _application profile_. Such restrictions are not in the scope of the ontology.

**Comment by costezki** [comment]
@idolum The ontology covers the possibility to specify a contact point for the role of an organisation.

![image](https://user-images.githubusercontent.com/13567133/150320216-71177bd6-3a09-44ea-afa7-25d43775d5c3.png)


The cardinality however of the contact point is left loose (0..*) because there may be use-cases where roles are without contact points. Therefore, as specified above, an application profile (AP) shall be developed to enforce this cardinality. This AP would look like in the image below (not implemented in the ontology, however). 

![image](https://user-images.githubusercontent.com/13567133/150319948-6a8897a5-8c0e-4234-a930-62923f1c0e81.png)
