### ISSUE TITLE
Catatlogue Line and Item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#317]
In general, an eCatalogue contains to kinds of information related to an item:

1. the information needed to place a proper order of an item
2. the information needed to described the item which is offered

The first is usually called Catalogue Line (for instance, in BII3 and Peppol). In analogy to a printed catalogue, it can be thought as a line in a table in the printed catalogue providing the information on the item and to what conditions it can be ordered. E.g., it might be the case that for the same item, one can find two catalogue lines where the price and the order unit is different.

Based on the BII3 transaction and the [Peppol BIS](https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/tree/), a semantic model would look like this:

![grafik](https://user-images.githubusercontent.com/1178743/139595726-7a09451f-f2af-4e51-887a-4e27413d5361.png)

The following definitions are proposed for the classes and attributes:

*Catalogue Line*: Detailed information of an item, price and its composition  in a catalogue.

* Action Code: Code that defines how the line should be applied to an existing eCatalogue.
* Orderable indicator: Indicator, if the item is orderable or not, e.g. because it is temporarily out of stock.
* Orderable unit: The unit in which the item described in this catalogue line can be ordered.
* Orderable unit factor rate: The factor by which the Item net price of an unit of an item can be converted to the orderable unit.
* Orderable quantity increment: The increment of Orderable units that can be ordered.
* Maximum order quantity: The maximum number of orderable units that can be ordered according to details provided in the catalogue line, such as price.
* Minimum order guaranteed for delivery: The minimum quantity of an item that is guaranteed by the seller to be delivered.
* Warranty information: Warranty information that applies to the catalogue line item.
* Contracted item indicator: Indicator if the item is offered in accordance to an existing contract.
* Transaction conditions: Textual description of the specific transaction conditions (purchasing, sales, payment) for an item.
* Transaction conditions code: Coded description of the specific transaction conditions (purchasing, sales, payment) for an item.

*Item*: tbd.

* Standard ID: An item identifier based on a registered scheme.
* Manufacturers ID: The manufacturer's identifier for the item.
* Brand Name: Name of the brand of the item to allow economic operators to distinctively describe an item in their eCatalogue.
* Keywords: List of words to make the item searchable, e.g, synonyms.
* External Specification: URI reference to external item information or specifications, e.g. web address.
* VAT category code: Value-added tax category of the item.
* VAT rate: Percentage of value-added teax of the item.
* In stock indicator: Indicator whether an item is in the supplier's stock. If not in stock the supplier has to order the item himself.
* Expiry date: The date on which the item will expire and not orderable anymore.
* Best before date: The date until when the relevant item qualities will remain at their best.
* Batch number: Identification of the production batch in which the relevant items were produced. Identifies the production batch that the item(s) listed in the catalogue line were part of.
* Manufacturer name: The name of the manufacturer of the item.
* Dimension description: Textual description of the item's dimensions.
* Net quantity: The net quantity of the item that is contained in each consumable unit, excluding any packaging materials.
* Hazardous item UNDG code: Specification of the hazardous nature of an item according to the UNDG classification schema. Provides detail of the classification and nature of a hazardous item.
* Hazardous class: Specification of the hazardous nature of an item according to a classification schema. Provides detail of the classification and nature of a hazardous item.

Attributes which were defined already in the ePO are left out in the lists above. They are also just examples.

They are also more classes and attributes related to the catalogue line and the item, but for them I will open seperate issues, as they refer to specifc subjects.

**Comment by costezki** [comment]
Based on today's discussion
* Item is context free, and catalogue line is contextualized.
* Added a new controlled vocabulary epo:vat-category 
* Transformed the attributes pointing to the epo:Code into dependency relations pointing to controlled vocabularies; as depicted in the figure below.
* Renamed eCatalogueItem to Item.
* Model manufacturer is a role that is played by an agent and an item has a manufacturer. [To be implemented.]

![image](https://user-images.githubusercontent.com/13567133/151395749-624bbb06-f0cc-4ecb-bcb6-433b449119e0.png)

**Comment by andreea-pasare** [comment]
In the figure below is presented the implemented model for Catalogue Line and Item (from the ePO master branch):
![image](https://user-images.githubusercontent.com/88081600/167145811-c62b8dff-324c-452a-aee9-b14b76131904.png)
