### ISSUE TITLE
Add a contact person name to epo:ContactPoint

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#319]
The contact point summaries details used to reach an organisation, but does not allow to provide a name of a person. This is used quiet often, in particular if a contact point is provided for a specific purpose, for instance, providing a eCatalogue. Thus, it is proposed:

* Either add epo:Name (and to reuse this attribute)
* or add a epo:ContactPersonName: epo:Text

In both cases, as an optional attribute.

See the Peppol BIS for the Catalogue as an example:
https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-SellerSupplierParty/cac-Party/cac-Contact/

**Comment by costezki** [comment]
In the current version of the model, we have a *epo:isPersonOfCcontact* relation from *epo:ProcurementRole* to the *epo:ContactPoint*. *epo:ContactPoint* class has the attribute *epo:hasDescription* which can be used to specify the name of the person.

This part of the model is under revision and we will take into consideration your point.

**Comment by idolum** [comment]
@costezki I will check the _epo:isPersonOfContact_. I proposed the description already, but it was rejected, as it can be everything and not the name of the person in particular.

**Comment by idolum** [comment]
@costezki Thanks for considering my request! I checked the changes. Just a question: The relation _epo:isPersonOfContact_ implies that the _epo:ProcurementRole_ is played by a _epo:Person_?

But that this part is under revision is fine. In the course of our discussion, it turned out that a _epo:ContactPoint_ might not be a _epo:Person_, but also a _epo:Organisation_ or a department within this _epo:Organisation_. _epo:hasDescription_ would be enough to provide this information, but still would not indicate, if this is a _epo:Person_ or a _epo:Organisation_.

**Comment by costezki** [comment]
A new attribute _epo:hasContactName_ is added to the _epo:ContactPoint_ class, which allows specifying "A short text by which a contact is known or referred to."

A decision was taken not to make the connection the class epo:Agent in order to avoid:
* complexity on the implementation side
* complexity that may arise in handling the personal data and compliance to GDPR
