### ISSUE TITLE
Agreement on a description of the classes, properties and relationships

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#32]
Claude Schmit said that in the detailed textual descriptions of the classes, properties and relationships, it could be more efficient:
1) to propose the best found description (instead of leaving it in blank); 
2) also to mention all synonyms; and 
3) flag in which use cases they are used. Many "foreseen/probable" properties could be added and evaluated later if no use cases refers to them.

**Comment by JachymHercher** [comment]
1. agree
2. no opinion, but if it is added, it should be in a separate section (not part of the textual description)
3. rather than use cases, I would propose having a link to the information requirements (which then have links to use cases).

**Comment by makxdekkers** [comment]
1. In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017), all classes and properties have proposed definitions, with references to sources where the definition was based on external resources.
2. Synonyms can be added to the definitions later as soon as they are agreed by the Working Group.
3. Such a cross-reference is already included in the document, i.e. in Table 6 Information requirements which presents the relationships between the information requirements, the model elements and the use cases.

**Comment by muricna** [comment]
It was decided in the working group meeting of 24/05/2017 that in the next stages of the work the editor would list terms and definitions from other ontologies and vocabularies.   The editor would then analyse this list so as to propose the term and its definition to be used in the ontology.  The working group would then to discuss and agree on the term and definition to be used based on the input of the editor or any further input from the working group members.
