### ISSUE TITLE
Support simple addresses for eCatalogues

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#324]
The current model of an address in the ePO looks like this:

![grafik](https://user-images.githubusercontent.com/1178743/144707511-c4009dc8-9bc6-42af-951d-b20a2f9e2f14.png)

which is much in line with the model of an [address in the UBL](http://www.datypic.com/sc/ubl21/e-cac_Address.html).

In the context of eCatalogues, such an address model is considered as too complex and gives implementers of eCatalogue systems, in particular smaller ones like SMEs.

Usually, some basic data (street, city etc.) combined with three generic address lines is enough in these use cases. As an example, Peppol it implemented as follows:

* Address line 1
* Address line 2
* Address line 3
* City name
* Postal code
* Country code
* Coundtry subentity code

See https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-ProviderParty/cac-PostalAddress/

As the full address is also used in other uses cases, the ontology might be extended as follows:

![grafik](https://user-images.githubusercontent.com/1178743/144707954-a814a51f-43b6-462d-afb5-f59fd8823eb0.png)

Two address, a simple and a complex one. In the context of eCatalogue these might get restricted via an Application Profile, as proposed in #316.

**Comment by jpmckinney** [comment]
I would have expected the ISA Core Location Vocabulary to be used.

**Comment by muricna** [comment]
The plan is to use the Core Location Vocabulary - we are currently working on it.

**Comment by costezki** [comment]
A Catalogue is provided by a CatalogueProvider, which is playedBy an Organisation, which has an Address. 

![image](https://user-images.githubusercontent.com/13567133/172401687-96461e09-a157-4009-9647-27e0f3c8501e.png)
