### ISSUE TITLE
Notice systematisation

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#333]
Implementation of Notice module that contains:
- Notice core model
- eForms mapping
- standard (current) Forms mapping

All development for this ticket is done in the following branch:
https://github.com/OP-TED/ePO/tree/feature/notice-systematisation

**Comment by giorgialodi** [comment]
Hi @andreea-pasare even this link brings to 404 error

**Comment by andreea-pasare** [comment]
The published Notice module HTML diagrams for the latest release, ePO 3.1.0, can be consulted [here](https://docs.ted.europa.eu/EPO/latest/_attachments/html_reports/eNotice/index.html).

The conceptual model eap file for the latest release, ePO 3.1.0, can be found [here](https://github.com/OP-TED/ePO/blob/v3.1.0/analysis_and_design/conceptual_model/ePO_CM.eap)

All future development can be tracked in the [GitHub development branch](https://github.com/OP-TED/ePO/tree/feature/development).
