### ISSUE TITLE
Type of Item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#336]
Sometimes it is needed to specify the type of an item. In particular, if a classification systems like UNSPSC is used or would not be useful.

Used are often codes from the EANCOM 2002 Dataelement 7009, Item description code: https://www.gs1.org/sites/default/files/docs/eancom/ean02s4/part3/dc245.htm

For instance, in Sweden the following codes are used

* SER - Trade item is a service
* MTO - Trade item is manufactured after order
* VQ - Trade item is variable measure item, that is, the quantity in the package is not fixed, and the price for the item varies with the quantity
* RC - Trade item is a returnable unit

Proposed would be a controlled vocabulary with `hasItemType` association for the class `Item`:

![image](https://user-images.githubusercontent.com/1178743/159860744-5022bdc3-cda6-48aa-93e8-00bc62693bcc.png)

**Comment by andreea-pasare** [comment]
Proposed to add a new enumeration at-voc-new:delivery-item-type - indication whether an item is a product or a service. The dependency relationship between epo:Item and this enumeration should be epo-ecat:hasDeliveryClassification.
In the figure below is presented the implemented model for Type of Item (from the ePO master branch):
![image](https://user-images.githubusercontent.com/88081600/167146479-34078542-deb3-4783-868c-e6fdc60c5f2a.png)
