### ISSUE TITLE
Price of items related to ordered quantity, delivery location and period

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#337]
Proposed model:

![image](https://user-images.githubusercontent.com/1178743/159862234-db2b805c-320f-438b-b8bd-5325c7992b06.png)

Definitions:

Attributes:

* Price: The price for an item.
* hasNetPrice: The price amount of an Item exclusive of taxes and after substracting price discounts.
* hasOrderabableUnitFactorRate: The factor by which the Item net price of an unit of an item can be converted to the orderable unit. (Might be redundant).
* hasQuantityThreshold: The minimum quantity of the item that can be ordered to the given price.
* hasLeadTime: The time taken from the time at which an item is ordered to the time of its delivery. (as definied by UBL)
* hasValidityPeriod: The period of time when the Item can be ordered to the given price.
* hasLocation: Location whare the price applies.

**Comment by andreea-pasare** [comment]
In the figure below is presented the implemented model for price of items (from the ePO master branch):
![image](https://user-images.githubusercontent.com/88081600/167143981-a6bd37cb-0f4b-4be7-a5e8-c75d7339c431.png)
