### ISSUE TITLE
List of post-award catalogue issues

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#339]
List of catalogue issues to keep track of the catalogue work:

* [x] https://github.com/OP-TED/ePO/issues/284
* [x] https://github.com/OP-TED/ePO/issues/317
* [x] https://github.com/OP-TED/ePO/issues/316
* [x] https://github.com/OP-TED/ePO/issues/315
* [x] https://github.com/OP-TED/ePO/issues/319
* [x] https://github.com/OP-TED/ePO/issues/324
* [x] https://github.com/OP-TED/ePO/issues/336
* [x] https://github.com/OP-TED/ePO/issues/337
* [x] https://github.com/OP-TED/ePO/issues/340
* [x] https://github.com/OP-TED/ePO/issues/341
* [x] https://github.com/OP-TED/ePO/issues/342
* [x] https://github.com/OP-TED/ePO/issues/343
* [x] https://github.com/OP-TED/ePO/issues/355
* [x] https://github.com/OP-TED/ePO/issues/356

**Comment by idolum** [comment]
@costezki I made a list of the catalogue issues to get an overview and assess when we are finished. But it is not complete.

**Comment by costezki** [comment]
@idolum The abovementioned issues have been resolved; therefore, we also close this ticket.
