### ISSUE TITLE
Relationships between catalogue items

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#340]
As part of a description of an item in catalogue, the relationship between items has to be described. Relevant relationships between items:

* Accessory: An item is an accessory to an item, i.e., an item that can be added to  an item to make it more useful like an tablet bag for an tablet.
* Required: An item is required for using another item, for instance, an cartridge for an ink printer.
* Component: An item is a component for another, for instance, to describe different package levels of an item and other hierarchies of items.
* Replacement relationship between items
  - In Denmark used, if an item not produced any more. Then, a new item has to be used instead. For instance, new model of a notebook series. Is often part of the contract in the public sector.
  - In Hungary: In GS1: If a item changes its features to much, a new GTIN is assigned making it a new item.. Then the relationship can be used to express the relationship between the old and the new item.
* Complementary: Items that are often bought or used together Example: Gin and Tonic Water.

Proposal for extending the ontology:

![image](https://user-images.githubusercontent.com/1178743/167155201-f52a88e1-ac74-4e14-9a03-fb219039b3e5.png)

Proposed definitions:

* hasAccessoryItem: An item that can be added to the item to make it more useful.
* hasRequiredItem: An item is required for using the item.
* hasComponentItem: An item is a component of the item. Note: Useful to describe different package levels of an item or hierarchies of items.
* hasReplacementItem: An item is replaced by another item. Note: Use to define relationships where an item is not offered anymore and is replaced by a new one.
* hasComplementaryItem: An item can be or is recommended used together with another item.

**Comment by idolum** [comment]
@costezki Finished the description of this issue.

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/169311489-17e2397d-33e6-403a-b718-58d154ce08a8.png)

**Comment by idolum** [comment]
@costezki We discussed this this week in CEN/TC 440/WG 5. From our point of view, the quantities on the relationships are relevant. Some example from experts in WG 5

* isReplacedBy: 1 bottle of 1 liter is replaced by 2 bottles of 0,5 liter
* replaces: Two bottle of 0,5 liter are replaced by 1 bottle of 1 liter
* hasComponent: A whell chair 2 wheels as components
* hasRequiredItem: When you by a wheel chair you need to buy 4 hours of mounting as well
* hasAccessory: An item is run on battery. An assecory is 2 batteries

In favor of constistency, we prefer the quantities on all of the relationship. The same is done by Peppol.

* https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-CatalogueLine/cac-RequiredRelatedItem/
* https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-CatalogueLine/cac-AccessoryRelatedItem/
* https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-CatalogueLine/cac-ReplacedRelatedItem/
* https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-CatalogueLine/cac-ComponentRelatedItem/

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/171652554-ab23fcea-566b-4a47-a7e3-7adf2399d1eb.png)

**Comment by andreea-pasare** [comment]
Proliferate sub-classes of item relationships to cover all item relations.

**Comment by idolum** [comment]
Classes were be added.
