### ISSUE TITLE
Item properties for structured description of items

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#341]
Items in a catalogue are described usually in a textual manner. But this allows only text searches for item. If a structured search for an item with a specific property is needed, such text search produce a lot of noise. For instance, a search for printing paper, which can be used for laser printer. A search result migth also contain laser printers itself or 

Classification systems like GPC or ECLASS provide property system to describe items in a structured manner. For instance, GPC has the property (here called attribute) "20000924/Type of Paper/Card" with the defined value "30011357/LASER". This allows searches for all items which have the attribute 20000924, and only those are in the search result. Similar for ECLASS.

For some of these values are provided, but in other cases free values can be provided. For instance, shirt sizes (XS, S, M, etc.).

In BII3 this was modelled like this:

![image](https://user-images.githubusercontent.com/1178743/169026802-549aeed9-3390-4458-af66-da1c1321dcbc.png)

**Comment by idolum** [comment]
@costezki Finished the description of this issue.

**Comment by andreea-pasare** [comment]
We provide the ItemDescription class which decribes an Item.
![item relations](https://user-images.githubusercontent.com/88081600/173609996-54cbbd0e-ebf4-4445-b514-3b09f77cebfe.png)

**Comment by idolum** [comment]
> We provide the ItemDescription class which decribes an Item. ![item relations](https://user-images.githubusercontent.com/88081600/173609996-54cbbd0e-ebf4-4445-b514-3b09f77cebfe.png)

Looks good to me. Will review it with the CEN/TC 440/WG5 members.
