### ISSUE TITLE
Involved subcontractors of an item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#342]
Someone who orders from a catalogue should allowed to assess the social aspects of an catalogue item. In particular,

* if subcontractors are involved with the production/delivery/providing the item
* if subcontractors are involved it should be possible to check, if they comply with the requirements defined in the overall contract

### Notes

* To be able to gain control of and investigage supply chains
* Relationship to buying warranty obligations and involved parties
* At least two level down the supply chain is relvant

### User Story

I choose a product in the catalog. I need to know if the supplier uses subcontractors. If the supplier uses subcontractors, then I need the subcontractors name and country. Some countries are blacklisted and subcontractors in these countries need to be followed up to see if their standard are up to date on environment, work crime and HSE.

I would like the agreement between the supplier and his subcontractors to see if requirements for the environment, work crime and HSE is in place and at my requirements. This is also important if the subcontractor has a subcontractor. The chain of subcontractors must be known.

It is important for me to know that the subcontractor has the same good standard as the supplier. If the subcontractor does not have good standards and I do not discover it, I risk that I can encourage suppliers to not deliver procurements to the public sector's requirements.

### Proposal

![image](https://user-images.githubusercontent.com/1178743/169025505-eeea8e8b-b4f2-4a4b-8809-6c119e75a6a6.png)

* EconomicOperator: A role of an agent which offers the execution of works, services, or supplies on the market.
* Manufacturer: The Economic Operator manufacturing the Item
* Subcontractor: A role of an agent that has an aggreement to perform part or all of the obligations of another agent’s contract.

**Comment by idolum** [comment]
@costezki Finished the description of this issue.

**Comment by costezki** [comment]
We believe that the Item has a Manufacturer that has a contract with someone.


![image](https://user-images.githubusercontent.com/13567133/171655945-69dced44-317e-4eb1-94fd-ceecea17933a.png)

**Comment by idolum** [comment]
@costezki We discussed this in the last CEN/TC 440/WG 5 meeting and all of the WG members agree on your proposed solution. Ticket can be closed.

**Comment by andreea-pasare** [comment]
Proposed solution was implemented. Marking closed.
