### ISSUE TITLE
 Ontology reference URI doesn't work

### ISSUE THREAD

**Issue by mariaclaudia** [OP-TED/ePO#347]
Hi,
the links Ontology reference URI: http://data.europa.eu/a4g/ontology is not working.
please could you fix it?

Many thanks

Maria Claudia Bodino

**Comment by costezki** [comment]
Dear Maria Claudia, 
 The ontology dereferencing has not yet been implemented. 

We are currently looking into this, and hope to implement it soon.

Eugeniu Costetchi

**Comment by andreea-pasare** [comment]
The ontology dereferencing has been implemented.
