### ISSUE TITLE
v3.0 Definition of FrameworkAgreementTerm is not correct

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#348]
Definition is "Reason for extending time limits" which is the definition of epo:hasDurationExtensionJustification.
I understood that this class would be instantiated if the Lot foresees to establish a FrameworkAgreement, meaning that the class FrameworkAgreementTerm "indicates whether the Lot it applies to forsees to establish a FrameworkAgreement and additional conditions around this setting."

**Comment by andreea-pasare** [comment]
The new definition for epo:FrameworkAgreementTerm is:
"Conditions and stipulations defining particularities in a framework agreement."
