### ISSUE TITLE
v3.0 How to find Buyer information?

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#349]
Who is the buyer organising the procedure is a very common question. 
Did I read correctly that to access Buyer information the path is : 
"CAN is a ResultNotice,
ResultNotice refersToProcedureTerm ProcedureTerm,
ProcedureTerm involvesBuyer Buyer, 
Buyer is AgentInRole,
AgentInRole isPlayedByOrganisation Organisation"

If it is the case I am concerned that Buyer is a property of ProcedureTerm.

**Comment by costezki** [comment]
After deliberation, we have concluded that the Roles will be related to the Procurement Objects directly (not via Terms). So, in this case, the Procedure is linked to the Buyer via epo:involvesBuyer relation.

**Comment by giorgialodi** [comment]
I have a doubt about the naming of this relationship. In past versions of the ontology the property indicated a responsibility of the Buyer, which is what happens. InvolvesBuyer is too generic from my point of view. It seems that the buyer is accidentally involved in it. It can be involved another organisation playing another role, but a Buyer with respect to a procedure is a strategic role. Therefore, I would suggest to roll back to previous versions of the ontology where a more appropriate name for that property was used. @guascce @muricna

**Comment by costezki** [comment]
@giorgialodi recommends that we discuss the relation between Procedure and Buyer and the boolean flag in the Buyer class. 

![image](https://user-images.githubusercontent.com/13567133/172390140-4186259e-25fe-49e2-91e5-379be6e0335a.png)

**Comment by costezki** [comment]
Indeed if we used a boolean attribute, it allowed for the possibility to have multiple buyers involved, none of which were responsible for the procedure. Using two relations, however, enables us to enforce that at least one buyer MUST be responsible for the procedure. 

![image](https://user-images.githubusercontent.com/13567133/172404633-b4f81aa9-3b2c-4eed-a1f4-2922913ca31b.png)

**Comment by giorgialodi** [comment]
Makes more sense indeed. I personally need to understand the brand-new requirement of more than one buyer with "some" responsible for the procedure and some others not. @muricna @guascce

**Comment by muricna** [comment]
In some procedures the Buyer responsible for the procedure can foresee that other Buyers use its contract particularly in the case of Framework Agreements.
