### ISSUE TITLE
v3.0 Organisation Registration ID (both for public organisation and Business ) not available

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#353]
I need to identify procedures where the Registration ID of the winner or the Buyer is missing. 
I cannot find this information element as part of the Agent diagrams neither in the foaf: Agent properties.

**Comment by andreea-pasare** [comment]
The ID of a foaf:Agent is represented by epo:hasID predicate between foaf:Agent and epo:Identifier as depicted in the diagram above:
![image](https://user-images.githubusercontent.com/88081600/204294335-62eb2444-553f-436f-9b3c-d7229ecebd14.png)
