### ISSUE TITLE
v3.0 ResultNotice refers to ComptetionNotice is missing

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#354]
I need to identify ResultNotices that are not resulting from a competition. A powwible way (not very accurate though) is to use the information of the CompetitionNotice linked to the ResultNotice. This is missing from ePO

**Comment by muricna** [comment]
I am not sure if I understand exactly what you need could it not be retrieved from the instantiation of the [DirectAwardJustification](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/direct-award-justification).  See: 

![image](https://user-images.githubusercontent.com/26601116/173551441-213f1b08-8e4c-4a3c-a6e2-3c1650bcd087.png)

**Comment by andreea-pasare** [comment]
We also provide two other relations, `epo: refersToPrevious` and `epo:refersToNotice` as depicted in the diagram below:
![image](https://user-images.githubusercontent.com/88081600/206891703-f92efee5-a3a2-4f62-b679-b966915dfbde.png)
