### ISSUE TITLE
Tax category of an item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#355]
To an item different kinds of taxes, duties or fees may apply. Usually, it is the value added tax (VAT). But even in this case, there are different rats of value added taxes (excluded from VAT, reduced VAT rate etc.). Another example is the "Canary Islands general indirect tax", which is an indirect tax levied on goods and services supplied in the Canary Islands.

Other examples are, taxes or additional fees on alcohol, tobaco or sugar in NO, DK or SE.

Fuel tax is another example, with a fixed amount that is added to the price. (3 ct per l)

For further details, see also https://docs.peppol.eu/poacc/upgrade-3/profiles/1-catalogueonly/#_line_tax_category

Is also relevant, if invoicing and billing is also incorporated into the ePO.

### User Story

I want to order an bottles of lemonade. As it contains a sugar, but is a nutrient the reduced VAT rate applies, but also the additional sugar fee. To know how much the item item will cost me add the end, I need also to the percentage or amount that have to be added to the item price.

### Proposal

![image](https://user-images.githubusercontent.com/1178743/174082729-c5d4f140-181c-4c01-a9fb-f5de570d08de.png)

* TaxCategory: A tax, duty or fee that applies to the item and has to be taken into account for calculating the full price of the item.
  - hasPercentage: The rate as percentage that applies to amount of the item.
* TaxCatagoryType: Type tax/duty/fee category within a tax/duty/fee type scheme
  - https://service.unece.org/trade/untdid/d97a/uncl/uncl5305.htm
  - https://docs.peppol.eu/poacc/upgrade-3/codelist/UNCL5305/
* TaxScheme: The system of taxes, duty or fee.
  - VAT = Value Added Tax
  - GST = Goods and Services Tax
  - Sales Tax

**Comment by andreea-pasare** [comment]
The following model was implemented:
![image](https://user-images.githubusercontent.com/88081600/179012169-dbb1fcf9-483a-4915-9047-58189636ca16.png)
