### ISSUE TITLE
Comparison of items

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#356]
Often the offered packages of items of the same type are different, so that the prices of the packages cannot be used to compare them. This is often resolved by providing a standardized unit that is priced.

### User Story

A person wants to by printer paper. Via the catalogue print paper by two different manufacturers are available, but the packaged and priced them differently:

* Manufacturer A: 1 Box with 3 packages with 500 sheets of paper each for 15 EUR.
* Manufacturer B: 1 package with 750 sheets of paper for 7.50 EUR

Actually, the price for one sheet of paper is the same, but it is hard to tell for the buying person.

Thus, for A and B the following information is provided:

* Manufacturer A
  - Standardized unit quantity: 1 piece (for one sheet)
  - Standardized unit price: 0,01 EUR
* Manufacturer B
  - Standardized unit quantity: 1 piece (for one sheet)
  - Standardized unit price: 0,01 EUR

### Proposal

In CEN/WS BII3 it was modelled like this

![image](https://user-images.githubusercontent.com/1178743/176673400-01558713-0f1f-4883-ae6a-c384e4ea3408.png)

Definitions

* Standardized unit quantity: The quantity of standard units that are in each consumable unit.
* Standardized unit price: The item price based on a standardized unit.

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/178709697-230d9395-bfca-4754-9732-6b88f6179a91.png)

**Comment by giorgialodi** [comment]
What does it mean that a price has a delivery location? A price? Are you sure? Probably the item but I don't think a price. A price may include the delivery part but it is very strange saying that a price has a delivery location.

**Comment by idolum** [comment]
@giorgialodi It's not the delivery location of the price, but the price might depend on the delivery location of the price. For example, the magazine in front of me: Its a German magazine and costs in Germany 4.90 EUR. If you order it from Austria or The Netherlands it costs 5.50 EUR, from Luxembourg 5.80 EUR, from Switzerland 9.50 CHF and from Hungary 2150 HUF.

**Comment by idolum** [comment]
> ![image](https://user-images.githubusercontent.com/88081600/178709697-230d9395-bfca-4754-9732-6b88f6179a91.png)

@andreea-pasare So the "Standardized unit quantity" is covered by the epo-ecat:hasBaseQuantity of the related hasStandardizedUnitPrice instance, is it?

**Comment by andreea-pasare** [comment]
@idolum Yes, this is the case. Here's an example of instantiating the model:
![image](https://user-images.githubusercontent.com/88081600/178988726-198021e7-8019-40fa-87a0-c718e46d33a4.png)

**Comment by giorgialodi** [comment]
@idolum ok but then the model above is strange. That model says that the price has a delivery location but it seems to me that you want to say that there is a portion of the price specification of an item that depends on the delivery location.
