### ISSUE TITLE
Procedure epo:isCompetitionTermination

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#357]
The definition of the attribute is clear however the name of the attribute is not so nice.  Maybe it is no longer needed as there is the class CompetitionTerminationInformation

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/177753064-e74e1b36-3df1-4f20-b542-83be3d0fcf8d.png)

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/177797272-12a24443-d0fc-46f1-9534-806a5a583caa.png)

**Comment by andreea-pasare** [comment]
In the latest version, ePO 3.0.1, the attribute epo:isCompetitionTerminated is depicted as in the following diagram:

![image](https://user-images.githubusercontent.com/88081600/196932641-6e8dd7cc-b390-492e-8736-d350d6cabf75.png)

**Comment by andreea-pasare** [comment]
As of ePO 3.1.0, the attribute epo:isCompetitionTerminated is described as in the following diagram:
![image](https://github.com/OP-TED/ePO/assets/88081600/9c0ecedd-47a5-4bad-b702-06386acd9adb)
