### ISSUE TITLE
DynamicPurchaseSystemTechnique hasDPSTermination

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#358]
Should the attribute not be isTerminated

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/177752954-8bf18176-d916-46e1-a0a2-7e6f41cfa6e8.png)

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/177797326-e632853f-0eed-42c2-b782-31acc5464bfa.png)

**Comment by giorgialodi** [comment]
Why using the boolean in the status class?

**Comment by andreea-pasare** [comment]
In the latest version, ePO 3.0.1, the attribute epo:isDPSTerminated is depicted as in the following diagram:

![image](https://user-images.githubusercontent.com/88081600/196932855-66b49911-51f4-4b4e-807e-87e1bfce191c.png)

**Comment by giorgialodi** [comment]
I believe I have understood the meaning of ContextSpecificDescription, hopefully :)  However I have two doubts: 1) If it is context based it is already specific to that context, no? So probably ContextDescription is sufficient? 
2) looking at the diagram the class has just subclasses but no properties. Is it really needed this classification pattern to group all its subclasses?

**Comment by andreea-pasare** [comment]
@giorgialodi, in ePO v4.0.0-rc.1, we changed the name of the concept from ContextSpecificDescription to ContextDescription, as you suggested. 
![image](https://github.com/OP-TED/ePO/assets/88081600/d760119b-003f-4729-acd4-89b450fc09fe)

We do use this concept as a gathering class for all our Information concepts and it will not be instantiated.
