### ISSUE TITLE
Consignee vs Deliveree

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#367]
Suggestion: epo-ord:Deliveree to be equivalent to both the role of Consignee (in PEPPOL ordering) and of Consignee (in PEPPOL dispatch); both of which have different definitions.

```
(Deliveree) Definition from epo-ord:Deliveree:
A role of an agent that receives the result of the procurement (service, product or work) and who is taking possession.

(Consignee) Definition from PEPPOL Ordering:
A person or unit to where the seller, or a dispatching party on behalf of the seller, delivers the goods.

(Consignee) Definition from PEPPOL Despatch:
The consignee is the person or organization to which the products will be shipped and who is taking possession. The role is carried out by the customer or on behalf of the customer.
```

**Comment by andreea-pasare** [comment]
In the Working Group meetings it was decided that epo-ord:Consignee class is a epo:PrimaryRole, having the following definition:

> A role of an agent that receives the shipment of the procurement (service, goods or works) and who is taking possession.
> 
> Additional information:
> The role is carried out by the customer or on behalf of the customer.
> The possession of the goods does not necessary imply ownership.
> 
> (Consignee) Definition from PEPPOL Despatch:
> The consignee is the person or organization to which the products will be shipped and who is taking possession. The role is carried out by the customer or on behalf of the customer.
> 
> WG approval: 20/10/2022
> 

It was voted to omit mentioning the term "delivered".
