### ISSUE TITLE
Notice metadata needed to compute SMS indicators.

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#369]
Information such as
 DATE_PUB
NO_DOC_OJS
and previous notice ID are needed to build the SMS indicators.

**Comment by andreea-pasare** [comment]
Notice metadata has been discussed and implemented during the [WGM](https://docs.ted.europa.eu/epo-wgm/notes/2022-09-06-wgm.html).
![image](https://user-images.githubusercontent.com/88081600/206890821-2b1333a9-ee41-493e-8b60-0778563623c7.png)
