### ISSUE TITLE
Checking line 217 of the conceptual mapping

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#370]
Can you confirm that line 217 correct ?
I suspect that the reason for launching a procedure outside the directive is used to state that the procedure is outside, but then there should be a formula.
This does not match with the policy to map each information element of teh standard forms to ePO without transformation.

D1.2.1	The procurement falls outside the scope of application of the directive	PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_CALL/D_OUTSIDE_SCOPE		epo:Procedure / epo:DirectAwardTerm / at-voc:direct-award-justification	[?this epo:isSubjectToProcedureSpecificTerm / epo:hasDirectAwardJustification <http://publications.europa.eu/resource/authority/direct-award-justification/dir24-list> .](http://publications.europa.eu/resource/authority/direct-award-justification/dir24-list)

**Comment by muricna** [comment]
The mapping is correct see Annex D1 (last page of F03): https://simap.ted.europa.eu/documents/10184/99173/EN_F03.pdf to understand the usage in the current forms.

The code dir24-list has the definition "Contracts listed in Directive 2014/24/EU Art. 7, but not falling within the scope of Directive 2014/25/EU" would appear to be the good mapping as we are mapping F03 which has the legal basis of Directive 2014/24/EU.

However the identifier of the field  (column A) maybe misleading.  D1 refers to Annex D1 and the 2 to the section

**Comment by muricna** [comment]
Dear Andrea,

I think there is another github issue concerning this there is a problem with the mapping of section D1 across the different forms, we need to discuss this perhaps in the meeting tomorrow if we have time?

Kind regards,

Natalie

**Comment by andreea-pasare** [comment]
@muricna, I will add it to the agenda for tomorrow's meeting and will try to find the other related issue as well.

**Comment by andreea-pasare** [comment]
This seems linked to the following ted-rdf-mapping issue: https://github.com/OP-TED/ted-rdf-mapping/issues/308

**Comment by andreea-pasare** [comment]
A new code was added in the direct-award-justification Authority Table on EU Vocabularies:
![image](https://github.com/OP-TED/ePO/assets/88081600/1af10be5-98da-4a7c-a8ce-e06a0e62d139)
