### ISSUE TITLE
Inconsistent definitions of epo:Period's object properties

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#375]
In [3.0.0](https://github.com/OP-TED/ePO/releases/tag/v3.0.0), the [objects properties](https://docs.ted.europa.eu/EPO/3.0.0/_attachments/html_reports/v3.0.0/glossary/glossary.html#predicates-(object-properties)-and-definitions) of epo:Period are defined as follows:

* epo:hasBeginning: The _date_ on which this period begins.
* epo:hasEnd: The _time_ at which this period ends.

which is inconsistent (date vs time). As the data type is xsd:dateTime, the following new definitions are proposed:

* epo:hasBeginning: The date and time on which this period begins.
* epo:hasEnd: The date and time at which this period ends.

**Comment by andreea-pasare** [comment]
The definitions have been changed according to the proposition above.
