### ISSUE TITLE
epo:CatalogueReceiver not linked to epo-cat:Catalogue

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#376]
In  [3.0.0](https://github.com/OP-TED/ePO/releases/tag/v3.0.0), a catalogue is provided by a `epo:CatalogueProvider` to a `epo:CatalogueReceiver` (described as `epo:Role` played by an `epo:Agent`). But while, the `epo:CatalogueProvider` is linked to the `epo-cat:Catalogue` via `epo-cat:isProvidedByCatalogueProvider`, none of such an association was defined for the `epo:CatalogueReceiver`. (It seems, we forgot that in the course of our discussions.)

![image](https://user-images.githubusercontent.com/1178743/190710378-0a915a29-055e-43be-b836-8d4131946d02.png)

As a consequence, it can not be expressed, who actually is the receiver of a catalogue. But to check, if the the actual receiver is the intended receiver of a catalogue, this information has to be provided in a catalogue as well. Thus, it is proposed to as an assocation as follows:

```
epo:CatalogueReceiver <-- (0..1) - (epo-cat:isReceivedByCatalogueReceiver) ---- (0..n) -- epo-cat:Catalogue
```

**Comment by andreea-pasare** [comment]
This relation has been added to the model and it will be included in the ePO 3.1.0 release:
![image](https://user-images.githubusercontent.com/88081600/201928813-75dd7c6e-4b72-4fdc-bf88-697fe58008fa.png)
