### ISSUE TITLE
Consider removing all ontology restrictions

### ISSUE THREAD

**Issue by kvistgaard** [OP-TED/ePO#378]
How would OWL restrictions be applied in practice over the volume of instance data?
To what extent will they be useful, especially cardinality restrictions, some of which don't work as actual restrictions under the OWA?
Is OWA applicable for PPDS at all?

Consider keeping all[^1] axioms together with other constraints and rules in SHACL.

[^1]: It might be that RDFS ones, domain/range can be useful to be kept, while still maintained also in the corresponding SHACL constraints.

**Comment by costezki** [comment]
They are useful in separating two layers of complexity in the model. To be aligned with SEMIC practice, we keep the "core" as loose as possible, while "restrictions" can still be there for anyone interested in lightweight reasoning.
