### ISSUE TITLE
Add identifier for epo-cat:CatalogueLine

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#379]
The concepts `epo-cat:CatalogueLine` lacks an identifier.

**Use Case**

In messages created based on a catalogue, references to this catalogue are made. But not only the catalogue as a whole, but to certain lines within this catalogue. This allows to reference a specific order once made by the seller/supplier via a catalogue. An example for such an message is an order: A buyer wants to order item 1 as offered in catalogue A, line 2.

**Proposal**

Add an association `epo:hasID` from `epo-cat:CatalogueLine` to `epo:Identifier` as follows
```
epo-cat:CatalogueLine -- (0..n) ----- (epo-cat:hasID/hasUUID) -- (1) -> epo:Identifier
```

**Comment by andreea-pasare** [comment]
In the latest release version, ePO 3.0.1, epo-cat:CatalogueLine does have a link to epo:Identifier, epo:hasID. This relation was not visible in any of the diagrams of the catalogue module, but now it is fixed:

![image](https://user-images.githubusercontent.com/88081600/196939440-a8663689-b5a6-4d91-9235-a9e30680998a.png)

**Comment by idolum** [comment]
@andreea-pasare Thank you!
