### ISSUE TITLE
Add identifiers for epo-cat:Item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#380]
We discussed this in the course of adding catalogue concepts to the ePO 3.0.0, but it seems we lost it out of sight.

**Use Case:**

An order shall be placed based on a catalogue. For specifying the item unambiguously in the order, a identifier is used instead of a name. A name might be ambiguous. To this end, a unambiguous identifier has to be provided in a catalogue for the item.

In addition, items have more than one identifier:

* identifier assigned by the seller
* identifier assigned by the buyer
* identifier assigned by the manufactuer
* identifier according to a standard system like EAN/GTIN
* ...

**Proposal:**

Add associations to the epo-cat:Item:

```
epo-cat:Item ----- (epo:hasID/hasUUID) - 1 --> epo:Identifier
epo-cat:Item ----- (epo:hasBuyerIdentifier) - 1 --> epo:Identifier
epo-cat:Item ----- (epo:hasStandardizedIdentifier) - 0..1 --> epo:Identifier
epo-cat:Item ----- (epo:hasManufacturerIdentifier) - 0..1 --> epo:Identifier
```

An alternative, more flexible approach would be:

```
epo-cat:Item ----- (epo:hasID/hasUUID) - 1..n --> epo:Identifier
```

**Comment by andreea-pasare** [comment]
In the latest release version, ePO 3.0.1, epo-cat:Item does have multiple links to epo:Identifier but they were not visible in any of the diagrams of the catalogue module. In the diagram below are depicted the already existing links to epo:Identifier:

![image](https://user-images.githubusercontent.com/88081600/196940043-eda8f1e2-bae7-4c7d-bf61-e3827caa7885.png)

Are these enough or do we need to add more identifiers?

**Comment by idolum** [comment]
@andreea-pasare These are enough! Thank you, Andreaa! So, I remembered correctly that we discussed this. Will add this to our spec and discuss this with the working group. If we have further comments, we will come back to you. Issue can be closed then.
