### ISSUE TITLE
Ontology terms review

### ISSUE THREAD

**Issue by dachafra** [OP-TED/ePO#382]
Some terms in the ontology might be misleading, especially taking into account that in several descriptions it is mentioned that the Open Contracting Data Standard was used as the reference:
- Agree on clear core terms: the term "Tender" is used in indicators and OCDS in the sense of public procurement procedure, while epo:Tender refers to the bids.
- Review the description of the classes to see if they are clear enough to users. Include references to OCDS when used as the source.

**Comment by costezki** [comment]
There are several clarification questions regarding this issue. It would be best to join the next workgroup sessions to clarify. 
They are recurring meetings on Tuesday afternoons from 14:30 to 16:30 
[at this link](https://ecconf.webex.com/wbxmjs/joinservice/sites/ecconf/meeting/download/97bac957e00a446285a1aa1d55370979_20221018T121500Z?MTID=mc9b4a430d67591e79374801c5911a82b&launchApp=true&siteurl=ecconf).

**Comment by dachafra** [comment]
Ok, @mnavasloro and I will attend next meeting

**Comment by costezki** [comment]
The questions raised in this ticker have been answered during a meeting. Only clarifications were necessary. No changes in the EPO.
