### ISSUE TITLE
What do the cv and legal stand for in the predicates between org:Organization and locn:Address

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#384]
![image](https://user-images.githubusercontent.com/26601116/196497320-b8acc4da-aa82-4e6f-8dff-55cce9d49c15.png)

**Comment by giorgialodi** [comment]
cv is the prefix of Core Vocabulary while legal is the prefix of something that is currently not really available https://www.w3.org/ns/legal#registeredAddress (redirect to this https://www.w3.org/ns/legal-entity that is declared as obsolete. There is a kind of indication about RegOrg vocabulary that doesn't include that property).

I will raise this issues about the legal:registeredAddress in the working group of core vocabularies.

**Comment by giorgialodi** [comment]
@muricna the registeredAddress property is going to be under the namespace of cv, after my feedback on the issue above with legal-entity namespace. Please take this into account for the diagram and ontology @costezki @andreea-pasare

**Comment by VladimirAlexiev** [comment]
@giorgialodi by Core Vocabulary do you mean https://github.com/OP-TED/ePO/blob/master/implementation/ePO/owl_ontology/ePO_owl_core.rdf? If so please don't use `cv` but `epo` because:
- there are many "core" vocabularies. Eg the SEMIC core vocabs include Person, Org, Locn
- for the average person, "cv" means "curriculum vitae"

**Comment by giorgialodi** [comment]
Hi @VladimirAlexiev no I mean SEMIC core vocabularies whose prefix is cv.

**Comment by costezki** [comment]
This has been updated in the Core Location Vocabulary (https://github.com/SEMICeu/Core-Location-Vocabulary/issues/26). 
The reuse of the relation in the ePO ontology has been updated accordingly.

![image](https://user-images.githubusercontent.com/13567133/205342579-30d2346e-6f45-427e-ad15-38324222aaa2.png)
