### ISSUE TITLE
Relationship between Contract Award Notice and Buyer

### ISSUE THREAD

**Issue by brechtwyns** [OP-TED/ePO#39]
Should there be a direct relationship between the Contract Award Notice and the Buyer, given that there already is a direct relationship with Procuring Entity? How do we define that relationship?

**Comment by makxdekkers** [comment]
A Contract Award Notice could have a relationship with Buyer, e.g. Contract Award Notice 'is procured for' Buyer.

**Comment by muricna** [comment]
A contract award notice is not procured for a buyer.  A service is procured.  The contract award notice announces the award of a contract by a buyer.

**Comment by makxdekkers** [comment]
So, we could have the relationship:
Contract Award Notice "is awarded for" Buyer. 
Should this be added to the model?

**Comment by muricna** [comment]
No, something more like Contract Award Notice is announced by/for Buyer.  I think there needs to be a general discussion on how notices are related to the Buyers and the economic operators.  Indeed should the economic operators be referred to as sellers?

**Comment by JachymHercher** [comment]
I think this was discussed elsewhere, but do we need all these inverse relationships? I.e. we should definitely say that a Buyer fills in / sends / publishes (depending on the level detail we want to model) a notice. Do we need to say also the inverse, which is, if I'm not mistaken, what you are trying to do above?

I would vote hesitantly in favor of referring to Economic Operators as Sellers...

**Comment by makxdekkers** [comment]
In the current model, relationships are defined for the entity where they are most easily managed. For example, if the relationship to a Notice is asserted in the metadata for the Organisation, then every time an Organisation publishes a Notice, the metadata for that Organisation would need to be updated. On the other hand, asserting the relationship with the Organisation in the metadata for the Notice is something that has to be done only once and does not need to be updated.

**Comment by JachymHercher** [comment]
That makes sense. Does that mean we don't normally introduce inverse relationships?

**Comment by makxdekkers** [comment]
I would say we only create inverses if there is a good reason to do so. They might improve performance but add maintenance requirements to keep the data consistent.
