### ISSUE TITLE
TechniqueUsage meaning and Validity Period for it

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#390]
Why the class Technique has been changed in TechniqueUsage? Which is the ratio for this choice? Looking at the definition of TechniqueUsage "Methods used for conducting procurement procedure."  it is rather the technique itself than the usage of the technique. In addition, what does it mean that a Procedure usesTechnique TechniqueUsage? It seems to me more natural saying that a Procedure usesTechnique Technique. In addition a TechniqueUsage hasUsage?  Probably do you mean hasUsageType? All these named properties make me think that you are referring to the Technique.

If you want to model the fact that a Procedure makes usage of more than one technique in its different time periods, than probably the reification of the TechniqueUsage makes sense but I would rather propose the following:
1) Procedure makesTechniqueUsage TechniqueUsage
2) TechniqueUsage hasTechnique/basedOnTechnique Technique (where you can detail the techniques)
3) TechniqueUsage hasUsageType (to the skos voc usage) 
4) TechniqueUsage doneAt/doneAtPeriod Period (with the name of the property more inline for me to the concept of usage).

**Comment by andreea-pasare** [comment]
In ePO v4.0.0-rc.1 the Technique is modeled as follows:
![image](https://github.com/OP-TED/ePO/assets/88081600/574e2f06-15ab-4cc6-9760-0fd1a3135d0d)
