### ISSUE TITLE
`hasMainClassification, hasAdditionalClassification` codelist and example

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#397]
These two props
```ttl
epo:hasAdditionalClassification   rdf:type          owl:ObjectProperty ;
epo:hasMainClassification rdf:type          owl:ObjectProperty ;
```

Refer to "The codelist to be used is at-voc:cpv which is available at http://publications.europa.eu/resource/dataset/cpv".

In the browser this resolves to http://publications.europa.eu/resource/cellar/1356ebf8-80b9-11ea-bf12-01aa75ed71a1.0001.05/DOC_1, which is a `gc.xml` file and doesn't offer RDF nodes that can be used in an ObjectProperty. Here's how it looks:
```xml
	<SimpleCodeList>
		<Row>
			<Value ColumnRef="code">
				<SimpleValue>03000000</SimpleValue>
			</Value>
			<Value ColumnRef="Name">
				<SimpleValue>Agricultural, farming, fishing, forestry and related products</SimpleValue>
			</Value>
```
But if you get it with curl, you get an RDF file that refers to http://publications.europa.eu/resource/expression/cpv.
Get this with curl and you see another RDF file that has these triples:
```ttl
<http://publications.europa.eu/resource/expression/cpv>
        cdm:expression_manifested_by_manifestation
                <http://publications.europa.eu/resource/distribution/cpv/rdf/skos_ap_eu> , 
                <http://publications.europa.eu/resource/distribution/cpv/rdf/skos_core> , 
                <http://publications.europa.eu/resource/distribution/cpv/xml/gc> ;
```
Finally, these 3 refer to machine-readable distributions of CPV:
- http://publications.europa.eu/resource/distribution/cpv/rdf/skos_ap_eu/cpv-skos-ap-eu.rdf
- http://publications.europa.eu/resource/distribution/cpv/rdf/skos_core/cpv-skos.rdf
- http://publications.europa.eu/resource/distribution/cpv/xml/gc/Cpv.gc (the same `.gc.xml` file)

**I think** the first is the richer one of the RDF formats. You can get it like this:
```
curl -LO http://publications.europa.eu/resource/distribution/cpv/rdf/skos_ap_eu/cpv-skos-ap-eu.rdf
```

Therefore please:
- change the reference to http://publications.europa.eu/resource/distribution/cpv/rdf/skos_ap_eu/cpv-skos-ap-eu.rdf (or http://publications.europa.eu/resource/distribution/cpv/rdf/skos_ap_eu/)
- put the same in `rdfs:seeAlso`
- give `skos:example <http://data.europa.eu/cpv/cpv/03100000>` to illustrate the form of URL (that's "Agricultural and horticultural products")

**Comment by VladimirAlexiev** [comment]
The URLs in http://publications.europa.eu/resource/distribution/cpv/rdf/skos_core/cpv-skos.rdf are the same, and the file is much smaller (not because skos_ap_eu is much richer, but because it's formatted badly).

So it's better to refer to http://publications.europa.eu/resource/distribution/cpv/rdf/skos_core/cpv-skos.rdf  (or http://publications.europa.eu/resource/distribution/cpv/rdf/skos_core)

**Comment by andreea-pasare** [comment]
The codelists are just recommendations in the ePO UML diagrams, therefore all reference to codelists in the machine readable files have been removed.

**Comment by VladimirAlexiev** [comment]
Similar objections to closing this as https://github.com/OP-TED/ePO/issues/396

**Comment by andreea-pasare** [comment]
@VladimirAlexiev, thank you for your reply. This seems to be a change that needs to be done in model2owl. I added a ticket there regarding this request: 

- https://github.com/OP-TED/model2owl/issues/198
