### ISSUE TITLE
Standard Forms F20 Sect VII.2.3

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#408]
Need to model in EPO Standard Forms F20 Sect VII.2.3

![image](https://user-images.githubusercontent.com/13567133/200573755-1edae0e3-d2a4-4bdd-accb-459580355b47.png)

**Comment by costezki** [comment]
This is related to #389 and shall be addressed when modelling Contract module.

**Comment by costezki** [comment]
A new relation has been added "epo:hasRestatedAwardedValue". This relation should be used for the field VII.2.3.1 "Value Excluding VAT". The field VII.2.3.3 "Total contract value after the modifications" should use "epo:hasAwaredValue". 

![image](https://user-images.githubusercontent.com/13567133/200796693-021e0212-ca76-4fe2-a1ce-2f50706676a6.png)

**Comment by andreea-pasare** [comment]
Please check the comment section from #431 for the proper mapping of this section.
