### ISSUE TITLE
Model relied-upon entity (as a Role)

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#409]
[oeron](https://op.europa.eu/web/eu-vocabularies/concept/-/resource?uri=http://publications.europa.eu/resource/authority/eo-role-type/oeron)	Other entity (relied upon)

Other entity (relied upon)
oeron
Economic operator (who is not a subcontractor) on which the tenderer relies upon, to meet selection criteria.

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/203095864-ad4d4c76-f896-4ed9-8ba8-8b1146e48c15.png)
