### ISSUE TITLE
Contract award notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#41]
A contract award notice does not award a tender.  It announces the award of a contract.

**Comment by makxdekkers** [comment]
Should there still be a relationship between the Contract Award Notice and the Tender? For example:
Contract Award Notice "accepts" Tender 
Contract Award Notice "awards" Contract

**Comment by muricna** [comment]
No, unless you give some kind of complicated relationship such as

Contract Award Notice concerning the winning tender

But I'm not sure that this is needed

**Comment by muricna** [comment]
Term: Contract award notice
Definition: An announcement of the award of a contract by a procuring entity.

WG approval 18/05/2018

**Comment by JachymHercher** [comment]
If you want to be very precise, don't forget that a CAN can also announce that a contract was _not_ awarded. In this sense, it might be better to speak about the "result of a procedure (or lot)".

**Comment by eprocurementontology** [comment]
WG approval 18/05/2018

Term: Contract Award Notice 
Definition: An announcement of the award of a contract by a procuring entity.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
My comment above has not been resolved / reacted to. May I ask for a reply or the reopening of the issue?

**Comment by muricna** [comment]
The suggestion for the definition is therefore:

Term: Contract Award Notice
Definition: An announcement of the award or non-award of a contract by a procuring entity.

**Comment by eprocurementontology** [comment]
To be discussed when covering documents.  Pay attention to the definition of Contract award notice

**Comment by paulakeen** [comment]
The new definition has been updated in the ePO EAP file.
