### ISSUE TITLE
Modelling the pairing of the CPV classifications

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#410]
The CPV code and the CPV supplementary code shall be paired.
This is a good chance to rethink the "Purpose" as well.

Solution 1: Multiple instances of Purpose
Solution2: create a new class "classification" that pairs the CPV codes

![image](https://user-images.githubusercontent.com/13567133/200795046-245f7cd1-1d73-447e-ac71-8cdfa89c59be.png)

**Comment by andreea-pasare** [comment]
@muricna confirmed no mapping is required for this, unless specifically requested later by someone else.
