### ISSUE TITLE
Link Buyer and Seller to epo:Catalogue

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#412]
As a follow up to #284: It is needed to include information on the buyer and the seller explicitly, as both might not be the catalogue provider and/or catalogue receiver.

### Use Cases

1. Simple: A company and a municipality agreed on a contract for items that can be bought by the municipality from the seller. To this end, the selling company sends a catalogue of the items to the municipality. Here, the epo-cat:CatalogueProvider and the epo-cat:CatalogueReceiver are also the epo:OfferingParty and the epo:Seller.
2. Complex: A central purchasing body agreed with a company on a contract allowing contracting authorities associated to the central purchasing body to buy items from this company. To this end, the company sends a epo:Catalogue with the items that can be bought to the central purchasing body. The central purchasing body validates the epo:Catalogue, and if valid forwards it to the contracting authorities. Thus, there are two transactions were organisations act in different roles:
  -  The Company (epo:OfferingParty & epo-cat:CatalogueProvider) sends the epo:Catalogue to the central purchasing body (epo:CatalogueReceiver)
  -  The central purchasing body (epo:CatalogueProvider) sends the catalogue  of the comany (epo:OfferingParty) to the various contracting authorites (epo-cat:CatalogueReceiver & epo:Buyer).

### Proposal

Add the following associations:

```
epo-cat:Catalogue ---- epo-cat:isOfferedBy -- 0..1 -> epo:OfferingParty
epo-cat:Catalogue ---- epo-cat:isUsedBy -- 0..1 -> epo:Buyer
```

**Comment by costezki** [comment]
It is covered by the model now. 

![image](https://user-images.githubusercontent.com/13567133/202487113-7c5d0a3f-c27d-4574-a7b6-a81dd5374ae2.png)

**Comment by idolum** [comment]
@costezki  We discussed this today in CEN/TC 440/WG 5. The solutions works for us. Thank you!
