### ISSUE TITLE
Add a type to epo-cat:Price

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#414]
As a follow-up to #337, it is requested to add a type to the class epo-cat:Price.

### Use case

Usually, Buyer and Seller agree on a price, which is fixed in the contract. These prices should be in the catalogue. But they can also agree that the price might change during the contract period. To indicate this difference, it has to be indicated if the price is the agreed price or a varying price according to rules define in the contract.

A example for such prices are prices for items where the price is based on the time the item is ordered (like stock-exchange-based prices).

Another example, if a discount is offered by the seller. In this case, it is needed to indicate that this is a reduced price lower than the usual list value.

Peppol used the UNCL5387 list for this purpose:

* https://docs.peppol.eu/pracc/catalogue/1.0/codelist/UNCL5387/
* https://service.unece.org/trade/untdid/d95b/uncl/uncl5387.htm

### Proposal

Add a controlled vocabulary (UNCL5387 would be a candidate for this) to the class, epo-cat:Price:

```
epo-cat:Price --- epo-cat:price-type
```

**Comment by andreea-pasare** [comment]
A new controlled vocabulary `epo-cat:price-type` was added in the development branch and will be included in the next release.
![image](https://user-images.githubusercontent.com/88081600/203088230-65ba9a9c-0e7a-493c-b614-3bf8734d495f.png)

**Comment by idolum** [comment]
@andreea-pasare We discussed this today in CEN/TC 440/WG 5. The solutions works for us. Thank you!
