### ISSUE TITLE
Add a way to indicate the type of a epo-cat:ProductSpecification

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#415]
As a follow-up to #317 it is requested, to add means to distinguish various types of external documents provided along with an item. External documents are covered by epo-cat:ProductSpecification.

### Use cases

A seller wants to provide several documents along with an item, e.g., a printer. These documents are:

* Image of the printer
* Manual of the printer
* Certificate of conformity
* Advertising brochure for the item
* ...

Peppol uses a document type code including the code list UNCL1001:

* https://docs.peppol.eu/poacc/upgrade-3/syntax/Catalogue/cac-CatalogueLine/cac-Item/cac-ItemSpecificationDocumentReference/cbc-DocumentTypeCode/
* https://docs.peppol.eu/poacc/upgrade-3/codelist/UNCL1001/
* https://docs.peppol.eu/poacc/upgrade-3/codelist/Image/

### Proposal

As there is a hierarchy of documents already in the ePO, there a several options:

Either link epo-cat:ProductSpecification to a controlled vocabulary

```
epo-cat:ProductSpecification --- epo:hasDocumentType -- 0..1 --> epo-cat:document-type
```
This approach is preferred by CEN/TC 440/WG 5.

Or add several subclasses to the document hierarchy and link them with the item:

```
epo:Document <|--- epo-cat:cat:ProductSpecification <-- 0..1 -- epo:hasSpecification -- epo-cat:Item
              |--- epo-cat:Image <-- 0..n -- epo:hasImage -- epo-cat:Item
```

**Comment by andreea-pasare** [comment]
A new controlled vocabulary `epo-cat:document-type` has been added to the development branch and will be included in the next release: 
![image](https://user-images.githubusercontent.com/88081600/203088724-bd634499-83a2-4a66-a347-4d24a0c3fa92.png)

**Comment by idolum** [comment]
@andreea-pasare We discussed this today in CEN/TC 440/WG 5. The solutions works for us. Thank you!
