### ISSUE TITLE
Modelling procedure & sub-procedure in the cases of DPS, FA, PQS and possibly others

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#416]
It was discovered that the Dynamic Purchasing System, Qualification System, Framework agreement, and other multi-stage procedures need to consider the concept of mini-competition. This has impact on the core of the EPO.

Some (possibly) related tickets: #169 #193 #198 #216 #267 #161

**Comment by costezki** [comment]
In F21, F22, F23 Forms, we will use the `type` attribute in <notice/> element when present.

![image](https://user-images.githubusercontent.com/13567133/203508333-2e4a6cd7-71b9-45f1-8de4-25e36c08e6e0.png)

![image](https://user-images.githubusercontent.com/13567133/203507658-0ad8ebde-e9c2-4579-8652-ae329b4d9909.png)

**Comment by costezki** [comment]
Context: comments on the mappings to F06 (tx1-2)

> IV.1.3.1 is about the establishment of a FA whereas the concept from the ontology is epo:uses technique.  However is probably ok as used in combination with termination of FA

> IV.1.3.2 is about the set-up of a DPS whereas the concept from the ontology is epo:uses technique. However is probably ok as used in combination with termination of DPS

> Although the ontology foresees by default one lot. In the case of CAN for DPSs and FAs the relation to the lot can not be used for all awarded contracts they need to be done at the level of the mini-competition which in turn could be related to the lot it is part of the same procedure (231436-2021)

> 231436-2021  V2.2.1-V.2.2.6 Concerns a DPS with only 1 lot but many contracts concerned therefore the information about the tenders received per “mini-competition” needs to be made rather than per lot there is only 1 lot but 22 SubmissionStatisticalInformation the submissionStatistical needs to relate to the” mini-competitions”

> V.2.4.3 if a DPS and FA is used the statistical informationof the lowest and highest TenderValue will not work as it is not per lot but mini competition

> The problems of DPS for mini competitions will be the same/similar for FAs.  It should be noted that you can have a procedure with many lots and several DPSs or several FAs so the DPSs/FAs will need to have a relation to the corresponding procedures and lots.

> 231436-2021 V.2.4 Lot hasRestatedEstimatedValue.  The estimated value varies per contract however as this is calculated from the lot in this case it does not work as there is only one lot and this is about DPS, the same could be seen in the case of FAs.  The estimated value probably comes from the “sub-procedure.

**Comment by muricna** [comment]
One lot can have many contracts as noted in the ontology.
And one contract can result from  0..* LotAwardOutcome
And many  LotAwardOutcome can describe one Lot
Therefore the problem does not seem to be between the lot, lot Award and Contract
The problem may be that the relation SubmissionStaticialInformation concerns SubmissionsForLot Lot

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/204584517-50f065c3-32d4-4eb3-a678-0954dbe01a73.png)

**Comment by andreea-pasare** [comment]
The ePO v4.0.0-rc.1 provides the following:
![image](https://github.com/OP-TED/ePO/assets/88081600/bb0084bd-362e-461f-a8b6-a79a2c15bb7b)
