### ISSUE TITLE
Re-visit the concept of Contract in EPO core and its role in the entire procedure (start to end)

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#417]
Among minor questions to be addressed: 
* Result notice announces Contract is that correct? Is this used for non-award?

**Comment by andreea-pasare** [comment]
In ePO v.4.0.0-rc.1 there are provisions for both the award and non-award of the procurement:
![image](https://github.com/OP-TED/ePO/assets/88081600/26795fe2-7df0-4ba3-965f-f740e49f45ce)

![image](https://github.com/OP-TED/ePO/assets/88081600/7e2326d9-9b5d-47af-9494-186e11b452fc)

At the same time, ePO v4.0.0-rc.1 provides a new module, eContract, that targets the implementation of the Contract.
