### ISSUE TITLE
tx1-2: remove LotAwardLimit as it seems redundant

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#419]
[N Muric tx1-2 feedback] form F21
> II.1.6.2: 407866-2021 The mapping is good however, in the ontology there are 2 elements hasMaximumNumberOfLotsToBeAwarded and LotAwardLimit to keep the mapping correct LotAwardLimit should be removed from the ontology.

**Comment by andreea-pasare** [comment]
Closing this ticket since LotAwardLimit attribute was removed from ProcedureTerm:
![image](https://user-images.githubusercontent.com/88081600/214309924-5e3e8ca5-0fa3-443d-9899-bc6a15e580b4.png)
