### ISSUE TITLE
rules for participation field needed, in addition to criteria

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#420]
[N Muric] in the context of F21
III.1.4.1 This is not about selection criteria as shown in the mapping but about the rules and criteria for participation

Answer: EPO does not seem to cover any other type of rules and participation criteria than the criteria (exclussion, selection and acceptance). 

![image](https://user-images.githubusercontent.com/13567133/203573088-bc0dead4-6a30-4076-a66e-db76e4a6bd72.png)

**Comment by andreea-pasare** [comment]
The below model was discussed and implemented in [WGM](https://docs.ted.europa.eu/epo-wgm/notes/2023-01-24-wgm.html):
![image](https://user-images.githubusercontent.com/88081600/221512561-d0c26953-39d6-43cb-b94a-a48768d8d724.png)
