### ISSUE TITLE
SecIII F21: lot / procedure discrepancy between eForms and Standard Forms

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#421]
[N Muric]  context tx1-2 for F21
> III.1.5.1-III.2.3.1 and all intermediary rows are at Procedure level not Lot level this is the particularity of the current forms as opposed to eForms.  Therefore other elements of these fields have not been considered

Related to #420

**Comment by andreea-pasare** [comment]
The below model was discussed and implemented in [WGM](https://docs.ted.europa.eu/epo-wgm/notes/2023-01-31-wgm.html):
![image](https://user-images.githubusercontent.com/88081600/221512561-d0c26953-39d6-43cb-b94a-a48768d8d724.png)
