### ISSUE TITLE
Missing fields F21, IV.2.5, IV.2.9

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#422]
Two fields from the Standard Form F21 are not mappable into the current EPO. 

IV.2.5	Scheduled date for start of award procedures	PROCEDURE/DATE_AWARD_SCHEDULED
IV.2.9	Information about termination of call for competition in the form of a perior information notice

**Comment by csnyulas** [comment]
Seems to be related to these issues:
https://github.com/OP-TED/ted-rdf-mapping/issues/270
https://github.com/OP-TED/ted-rdf-mapping/issues/124

**Comment by andreea-pasare** [comment]
**IV.2.5 Scheduled date for start of award procedures PROCEDURE/DATE_AWARD_SCHEDULED**
- epo:hasEstimatedTenderInvitationDate on epo:ProcessPlanningTerm to be used
- as per directive 24, "award procedure" means the actual procedure
- this section appears in F21 - a PIN used as CFC (noted in the legend of the form, no. 15)
- the conclusion is that the start of award procedure is the date for the dispatch of the invitations to submit tenders. (from the definition of epo:hasEstimatedTenderInvitationDate)
![image](https://github.com/OP-TED/ePO/assets/88081600/dc09dc7d-1c03-4e79-a156-2e0fac26875c)

**Comment by andreea-pasare** [comment]
IV.2.9 Information about termination of call for competition in the form of a perior information notice
![image](https://github.com/OP-TED/ePO/assets/88081600/66909387-0c29-4504-a39d-5cab750f945d)
