### ISSUE TITLE
Missing fields: F22 III.1.9.x

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#423]
Need for accommodating information about qualification system. 

III.1.9	Qualification for the system			LEFTI/QUALIFICATION
III.1.9.1	Conditions to be fulfilled by economic operators in view of their qualification			LEFTI/QUALIFICATION/CONDITIONS
III.1.9.2	Methods according to which each of those conditions will be verified			LEFTI/QUALIFICATION/METHODS

**Comment by andreea-pasare** [comment]
![image](https://github.com/OP-TED/ePO/assets/88081600/93ae52f0-15b1-4990-ba75-01b5df2bcd17)
