### ISSUE TITLE
segregate the process and the procurement-object information 

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#427]
The conflation of both types of information can be found in multiple places (procedure, lot, terms, purpose, notice, processInformation, etc. ) 

For example: 
Estimated dates are not really conditions and stipulations, they are not terms. We need to segregate the procedural/process information from the procurement-object information in the future. 

![image](https://user-images.githubusercontent.com/13567133/206665996-94fd7990-4d83-4db5-81ec-51b0399c86ca.png)

Or for example
![image](https://user-images.githubusercontent.com/13567133/206666099-cc14d0a3-b1f5-43b4-bd85-8f1fad2f846a.png)

**Comment by AchillesDougalis** [comment]
The ePO represents data and not proccesses. If data regarding the process is required it is associated with the appropriate procurement object.
