### ISSUE TITLE
PlannedProcurementPart does not use Technique

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#428]
Is a restriction to be made to prevent PlannedProcurementPart usesTechnique? How should this be better visualised:

![image](https://user-images.githubusercontent.com/26601116/207077014-0ccfd7bb-7ddd-4fd2-bee2-5be82dbd7bd8.png)

**Comment by AchillesDougalis** [comment]
I think that this is not a problem anymore since in epo 4.0.0, epo:PlannedProcurementPart is a specialization of epo:ProcurementElement and not epo:ProcurementObject. 
![2024-01-26_11-13](https://github.com/OP-TED/ePO/assets/143995053/b557c8a6-90e3-4224-a600-1a8b223390dc)
