### ISSUE TITLE
Resource oriented vs. event oriented ontology

### ISSUE THREAD

**Issue by brechtwyns** [OP-TED/ePO#43]
This issue follows up on the side discussion of issue https://github.com/eprocurementontology/eprocurementontology/issues/20, i.e. whether the ontology should be resource-oriented or event-oriented.

Summarising the earlier discussion:
@jachymhercher:
>Isn't the "number of times a contract notice has been read" a very important indicator for knowing where is the problem with attracting bidders? ("People do not know we are running tenders!" vs. "People know we are buying, they read the notice, but then decide not to apply, because our selection criteria are too strict!"

@makxdekkers:
> The fact that an Economic Operator 'opens' Contract Award Notice is a process transaction not a property of the data

@jachymhercher:
>This is a very interesting point and I would be grateful for a deeper clarification. My thinking is: 1) someone opening a contract notice is part of the eNotification phase of procurement; 2) this information can be stored as data (about the use of a website on public procurement); 3) this information can be used to answer a policy relevant question from public procurement (see the first post). Thus, I would think it should be covered in the ontology.  
>If it shouldn't be covered, then this should be clear from the scope section of the ontology document. I think it currently isn't?

**Comment by JachymHercher** [comment]
@brechtwyns Thanks a lot for opening this issue - it is very important, and I have possibly (probably) overlooked a basic dimension of the scope of the ontology. 

1) May I ask for the definition of resource-oriented and event-oriented? 
2) What is the link with basing the ontology on use cases? 
3) Is there any link with the question of whether to include information which is publicly available vs. also information which is not?

**Comment by makxdekkers** [comment]
My take on your question 1:
An event-oriented approach focuses on the process. Every time something happens, instance data is created that records the event, its actors and its consequences.
Resource-oriented focuses on the data. Instance data is created to describe agents, documents and things irrespective of how these entities came about.

The link with use cases is that the cases we have considered so far were cases where people were looking for data (UC1: contract data; UC2: item specification in calls for tender; UC3: payment data), not for process information. If use cases are agreed that require information about the process to be accessible -- such as the example of capturing the event that a notice has been accessed -- event classes need to be added to the ontology, and the corresponding event data needs to be extracted from existing procurement systems.

As to question 3, I don't think there is a relation between the issue of resource vs. event-oriented and public/non-public information.

**Comment by JachymHercher** [comment]
Thanks for the explanation. It's still not 100% clear to me, in particular because I'm not sure what "focusing on the data" means. Data are only records of reality, so data can essentially be anything we decide to measure? Also, I would say almost anything can be fit into both the event-oriented and resource-oriented approach. But I'm happy to let the others chip in. 

I've opened a specific issues for question 3, see #44 .

**Comment by makxdekkers** [comment]
Yes, anything can fit in either modeling approach. It just depends on where the main interest lies. I meant with 'focusing on the data' that the intended users -- at least the users in the current use cases -- are primarily interested in the resources (agents, documents, items) that play a role in the application, as opposed to a primary interest in 'what happened'.
