### ISSUE TITLE
Change definition of Candidate to that of the directive

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#436]
The organisation role definition should correspond to that of the directive:

An economic operator that has sought an invitation or has been invited to take part in a restricted procedure, in a competitive procedure with negotiation, in a negotiated procedure without prior publication, in a competitive dialogue or in an innovation partnership

**Comment by andreea-pasare** [comment]
Changed the definition of epo:Candidate to the following:

_The role of an agent that has sought an invitation or has been invited to take part in a restricted procedure, in a competitive procedure with negotiation, in a negotiated procedure without prior publication, in a competitive dialogue or in an innovation partnership._
