### ISSUE TITLE
Published / unpublished data in the ontology

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#44]
I have a clarifying question on the scope of the ontology: does the ontology aim to cover all data necessary for meeting the use cases, or just published (=publicly available) data? 

I've always assumed the former, e.g. because one of the problems the ontology is supposed to solve is 
"the relations between the different concepts in the procurement chain and data flow are not fully documented, therefore data and data relationships cannot be reused directly in a flexible and comparable manner;". (Quoting from https://joinup.ec.europa.eu/asset/eprocurementontology/document/report-policy-support-e-procurement). 

However, the same document also states that "This creates the need for a common data standard for publishing procurement data, hence allowing data from different sources to be easily accessed and linked, and consequently reused. The e-Procurement ontology (henceforth referred to as the ePO) introduced by this study aspires to play this role.", which to me sounds more like only published data

**Comment by muricna** [comment]
Not necessrily, you could also adapt the ontology within a closed system.
