### ISSUE TITLE
Identification of Cancelled contracts in the ePO

### ISSUE THREAD

**Issue by ignaciobavastro** [OP-TED/ePO#445]
@muricna

For the calculation of SMS Indicators in the PPDS Project we need to indentify cancelled contracts. Cancelled contracts are marked in TED with a text in red.

However, we are not able to find a mapping in the ePO ontology to a field showing a similar information. We have identified the following issue in the PO-TED GitHub that refers to this topic: [ISSUE 371](https://github.com/OP-TED/ePO/issues/371). 
The issue doesn’t have any reply, but we see that it has been marked as 2023 Q2. Does it mean that such information will be available in the ePO from July on? Does this also affect already existing contracts (meaning that you will show this field in a retroactive manner as well)?  Would you know if there is any workaround to detect if a CAN was cancelled using other ePO attributes?

Thank you very much in advance!

**Comment by ignaciobavastro** [comment]
Moved this issue to the correct Board.

**Comment by muricna** [comment]
@ignaciobavastro: What do you mean this issue was moved to the correct Board

**Comment by ignaciobavastro** [comment]
@muricna As this issue is part of the PPDS project, I moved it to a GitHub Board that corresponds to PPDS, you can see the same issue [here](https://git.fpfis.tech.ec.europa.eu/datateam/ana-ppds/analysis-indicators/-/issues/21)
