### ISSUE TITLE
Standard Forms Metadata Mapping: LEGAL_BASIS_OTHER 

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ePO#448]
We are missing a property in ePO for mapping the value of the `LEGAL_BASIS_OTHER` XML element.
See issue: https://github.com/OP-TED/ted-rdf-mapping/issues/290

**Comment by andreea-pasare** [comment]
Based on `TED_EXPORT/FORM_SECTION/XXXX/LegalBasis`, is the metadata of the form that has a legal basis. As the Notice is the reflection of the Form used, we can assume that the Notice has the same legal basis as the Form. 

For European Notices there is a specific set of directives which exist in a codelist. The values provided in the metadata of the Form are equivalent to the ones used in the legal basis codelist on EU vocabularies: http://publications.europa.eu/resource/dataset/legal-basis.

As the ePO only recommends and provides a `skos:Concept` for given codelists, any re-user may implement with the `skos:Concept` of their choice.

For the European Standard Forms, implementation can be directly done using the legal-basis codelist.
![image](https://github.com/OP-TED/ePO/assets/88081600/03705825-0325-4fbe-9e0b-635cc6a801c1)
