### ISSUE TITLE
Review and confirm that the model for Duration is appropriate

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ePO#449]
Related to the mapping to RDF of the (specific and indefinite) durations that are present in Standard forms (see for example issue
https://github.com/OP-TED/ted-rdf-mapping/issues/336), the current model (v3.1.0) seems to be appropriate. However, my understanding, based on a discussion with @muricna many months ago, was that this model is not ideal, and might need to be revised (yet again).

This issue is just to serve as a reminder to take another look at the modeling of duration, and other time related classes, considering their various usages, to see whether any further changes are necessary to the model.

**Comment by andreea-pasare** [comment]
Confirming that the model depicted below is the proper one for modeling the duration:
![image](https://github.com/OP-TED/ePO/assets/88081600/d54255fd-9e3b-4b9c-aa09-b40e5ee44c2d)

Specific start and end dates can be mapped using the Period:
![image](https://github.com/OP-TED/ePO/assets/88081600/583787dd-4039-40b6-a180-8bc74c051589)
