### ISSUE TITLE
Please provide conceptual data model view

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#45]
The link to the conceptual data model is broken (doesn't work).

**Comment by eprocurementontology** [comment]
We resolved the link issue. Please find the conceptual data model visualisation from [here](https://joinup.ec.europa.eu/sites/default/files/uml_v0.12_0.jpg)
or from the [page](https://github.com/eprocurementontology/eprocurementontology/wiki/CM---Visualisation).
