### ISSUE TITLE
Lot hasRestatedValue is probably not needed 

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#454]
This concept was to cover the case in standard forms whereby the intial estimated value appears twice in the same form ie section II and section V.  However this does not occur it occurs only in section II in a CN and only in section V in a CAN.  Therefore this concept is not required.

**Comment by andreea-pasare** [comment]
The predicate epo:hasRestatedValue between epo:LotAwardOutcome and epo:MonetaryValue is no longer in ePO v4.0.0-rc.1.
