### ISSUE TITLE
Regression of the Tax/Charge information on an item

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#461]
In #355 the concepts of additional taxes and charges of an item were introduced ot the catalogue.

In the course of the revision of the ePO, it seems, this was changed to the TaxInformation concepts.

![grafik](https://github.com/OP-TED/ePO/assets/1178743/c5c5b3ca-d5b2-47f2-92a3-d6ae6e576f13)

But some details were lost:

* An item can have only one TaxInformation. Item charges with several tax can be described anymore.
  - Example: A soft drink is charges with a Value added tax and a soft drink tax; See https://en.wikipedia.org/wiki/Sugary_drink_tax for example
* Charges with a fixed amount: In some cases additional taxes are not based on the net price, but have a fixed amount. An example is the former Danish sugar drink tax of 1.64 DKK per liter

**Comment by andreea-pasare** [comment]
@idolum we changed the cardinality for `epo-ord:hasTaxInformation` property, so now an Item can have multiple taxes defined. 
If there is a tax with percentage, the combination of `epo-cat:hasPercentage` and `epo:isCalculatedOn -> epo:MonetaryValue` properties should be used.
If there is a tax with fixed amount, then only the property `epo:hasAmount -> epo:MonetaryValue` should be used.
![image](https://github.com/OP-TED/ePO/assets/88081600/c0a4ef48-9501-490f-9cba-58713524c4d1)
