### ISSUE TITLE
Relationship between epo-cat:Item and epo-ful:GoodsItem

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#463]
The concept epo-ful:GoodsItem is defined as

> An Item including its initial packaging during transportation.

So it is different from the epo-cat:Item, but seems to me linked to each other. That the epo-ful:GoodsItem is the epo-cat:Item plus packaging. If so, this link is not experessed in the ontology:

![grafik](https://github.com/OP-TED/ePO/assets/1178743/4e30af1e-acb5-422b-aa6f-7e9829e85445)

### Proposed change

Add a link between both concepts:

```
epo-cat:Item ----- epo:isContainedIn -- 0..1 --> epo-ful:GoodsItem
```

This way, the packaging concepts can be used for the catalogue domain as well, without introducting additional ones.

**Comment by andreea-pasare** [comment]
This should be further discussed within the working group. Foreseen for the future minor release.

**Comment by andreea-pasare** [comment]
See [WGM meeting minutes](https://docs.ted.europa.eu/epo-wgm/indiv.html) from 21/09/2023:
![image](https://github.com/OP-TED/ePO/assets/88081600/86229ed8-fc8c-46e1-95cb-c62b36d1fd42)
