### ISSUE TITLE
Items with more than one hazard

### ISSUE THREAD

**Issue by idolum** [OP-TED/ePO#464]
Some goods may have more than one hazard:

> Example 1:  A hazardous material meets the defining criteria of Division 2.1 Flammable gas and Class 8 Corrosive material.
>Answer 1:  Division 2.1 Flammable Gas is higher on the list (3) than Class 8 Corrosive material (8).  Therefore Division 2.1 Flammable gas is the primary hazard class and Class 8 Corrosive material is the subsidiary hazard class.

Example taken from https://danielstraining.com/classification-of-a-material-having-more-than-one-hazard-49-cfr-173-2a/

So, in this case, two a primary and a secondary hazard has to be described in the catalouge. Right now, this is not possible, as the cardinality of epo-cat:hasHazardousClass and epo-cat:hasHazardousItemUNDGCode is 0..1

![grafik](https://github.com/OP-TED/ePO/assets/1178743/08ddf2ea-7e84-4139-86ec-4a1c948b37b0)

### Proposed change

Change the cardinalities to 0..n

```
epo-cat:Item ---- epo-cat:hasHazardousItemUNDGCode -- 0..* --> at-voc-new:dangerous-goods-list
- epo-cat:hasHazardousClass [0..*]
```

**Comment by andreea-pasare** [comment]
![image](https://github.com/OP-TED/ePO/assets/88081600/70589713-a507-4651-af27-c3cca3b44299)
Closed as fixed.

**Comment by idolum** [comment]
@andreea-pasare Great! Thank you!
