### ISSUE TITLE
Manufacturer and seller levels in the catalogue model

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#470]
See Q2 2023 meeting minutes: During the meeting, a participant raised a question regarding the consideration of manufacturer and seller levels in the catalogue model. For example the manufacturer of a car could be Volkswagen with a given manufacturer ID, however the manufacturer of the tyres could be Michelin and there would be a manufacturer ID for the tyres.  It was noted that these different levels should be looked into within the context of catalogues as they are not currently covered.

**Comment by AchillesDougalis** [comment]
In ePO 4.0.0, in the eCatalogue module, `epo-cat:Manufacturer` and `epo-cat:Item` classes exist.
- `epo-cat:Item` is connected with  `epo-cat:Manufacturer` with the `epo-cat:hasManufacturer` property. 
-  `epo-cat:Manufacturer` is connected with `adms:Identifier` with the `epo:hasManufacturerID` property. 
- `epo-cat:Item` can be connected with another `epo-cat:Item` with the `dct:hasPart` property.   

These classes and predicates should be sufficient to cover the Volkswagen example. 

![2024-02-07_13-48](https://github.com/OP-TED/ePO/assets/143995053/805f867f-7e16-47cf-bd0d-0c671aec6323)
