### ISSUE TITLE
Difference between NUMBER_OF_SME_TENDER and NUMBER_OF_SME_CONTRACTOR (PPDS)

### ISSUE THREAD

**Issue by acolomer** [OP-TED/ePO#471]
Working in the PPDS project, we have noticed that some Member States differenciate between NUMBER_OF_SME_TENDER and NUMBER_OF_SME_CONTRACTOR (we reckon that the semantics of this second field is "Number of winners that are SME, excluding subcontractors").
We understand that the ePO does not address this datum, is this correct?
If that is the case, should the ePO address it?

**Comment by AchillesDougalis** [comment]
In the ePO, the attribute  epo:hasSMEReceivedTenders in the class epo:SubmissionStatisticalInformation, was created for the mapping of the TED xml. Therefore you will understand that we cannot remove this attribute. Would your requirement be fulfilled if we add an attribute _epo:hasSMEReceivedTendersExcludingSubcontractors_ ?

**Comment by acolomer** [comment]
Thank you for your reply. 
Sure, adding this attribute will meet our need. Thank you!

**Comment by AchillesDougalis** [comment]
The attribute `epo:hasSMEReceivedTendersExcludingSubcontractors` was included in the latest release of  [ePO ](https://github.com/OP-TED/ePO/tree/4.1.0-rc.2)
![image](https://github.com/OP-TED/ePO/assets/143995053/ef055a88-22e8-4537-b6af-35e824b09e4e)
