### ISSUE TITLE
Release patch ePO 4.0.1

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#475]
The ePO 4.0.1 should contain the following:
- metadata update
- fix for OP-TED/ePO#473

**Comment by muricna** [comment]
There is also the need to:

- [x]  Remvove alll of the authority tables from the restrictions file.
- [ ]  Correct or remove Non-Existent or Irrelevant URIs in the Shacl:
URIs like http://publications.europa.eu/resource/authority/cpv and http://publications.europa.eu/resource/authority/nuts are either non-existent or not relevant. This can lead to broken links or incorrect data associations in the ontology, which can cause retrieval and interoperability issues.
- [x]	Remove code lists that do no exist the Shacl:  http://publications.europa.eu/resource/authority/**new**
- [x]	URIs such as http://publications.europa.eu/resource/authority/new/certification-label-type/ and 
        http://publications.europa.eu/resource/authority/new/price-type that are based on our base URI will cause namespace 
        conflicts or ambiguity. It's essential to maintain a clear and distinct namespace to avoid such issues.
- [ ]	Eliminate the redefinition of properties and reference existing ones to maintain ontology integrity.

**Comment by cristianvasquez** [comment]
Dear @muricna, after inspection it seems the points 2 and 5

- Eliminate the redefinition of properties and reference existing ones to maintain ontology integrity.
-  Correct or remove Non-Existent or Irrelevant URIs in the Shacl:
URIs like http://publications.europa.eu/resource/authority/cpv and http://publications.europa.eu/resource/authority/nuts are either non-existent or not relevant. This can lead to broken links or incorrect data associations in the ontology, which can cause retrieval and interoperability issues.

Are too big to be handled in a single pull request, if you don't mind I'll open separate issues to track them separately

- https://github.com/OP-TED/model2owl/issues/225

**Comment by cristianvasquez** [comment]
merged
