### ISSUE TITLE
Remove link between Procedure and ExclusionGround

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#482]
Remove the following predicate:
epo:Procedure **epo:specifiesExclusionGround** epo:ExclusionGround

**Comment by SellittoGiampaolo** [comment]
Why? Esclusion grounds are the same for all the procedures, but anyway they depend on the procedure type - for some procedures some specific exclusion grounds can be removed. -They can also depend on the country

**Comment by AchillesDougalis** [comment]
In the WG meeting on [6/2/24](https://docs.ted.europa.eu/epo-wgm/notes/2024-02-06-wgm.html), it was decided that **epo:specifiesExclusionGround**  will be deleted in future versions of ePO.
