### ISSUE TITLE
Instructions in proprietary format

### ISSUE THREAD

**Issue by edent** [OP-TED/ePO#49]
The instructions file appears to be in Microsoft Word format.

When I try to open it on a Mac it looks like this.

![screen shot 2018-01-24 at 13 56 14](https://user-images.githubusercontent.com/837136/35335850-8db3a340-010e-11e8-9290-1f6c34cf9a16.png)

If I use LibreOffice, I get a warning about embedded macros.

![screen shot 2018-01-24 at 13 59 05](https://user-images.githubusercontent.com/837136/35335905-c55d9f1c-010e-11e8-8824-cb768300fe69.png)

Would it be possible to get this converted to an Open Format? Ideally HTML / markdown, or perhaps ODT?

**Comment by muricna** [comment]
The issue has been resolved if you still experience problems please reopen the comment.

**Comment by edent** [comment]
Thanks!
