### ISSUE TITLE
eSubmission requirements: cbc::EconomicOperatorGroupName 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#499]
Taken from the notes on the Working Group meeting  on 16/01/2024 
At the UBL term:cbc::EconomicOperatorGroupName : taken from https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html,

Comment reads: "It was noted that each member of the Consortium will provide an ESPD Response, also the **Subcontractors** need to be taken into consideration. Name of the Organisation Group that the Economic Operator belongs to. "

**Comment by andreea-pasare** [comment]
As of [ePO v4.1.0-rc.2](https://github.com/OP-TED/ePO/releases/tag/4.1.0-rc.2) the economic operator roles are implemented as depicted below:
![submission eo roles](https://github.com/OP-TED/ePO/assets/88081600/daeed9d7-9998-4937-ac6c-e200804945d6)

**Comment by NoraBermingham** [comment]
Hi

I’ve tried repeatedly to unsubscribe from these notifications. On github it looks like I am unsubscribed but I am still receiving emails.

Grateful for help with unsubscribing.

Best wishes,

Nora
