### ISSUE TITLE
CM relationship 'responds to'

### ISSUE THREAD

**Issue by noeclai** [OP-TED/ePO#5]
The definition is a little strange 'the payement' is not concerned by  a relation between a 'Tender' (domain) and a 'Call for tender' (range).

**Comment by makxdekkers** [comment]
This is indeed incorrect. The definition is erroneously copied from 'corresponds to'. The relationship 'responds to' should be defined as something like "this relationship links a Tender to a Call for Tender in response to which it is submitted".

**Comment by makxdekkers** [comment]
In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017), a Tender 'responds to' a Call For Tender, with 'responds to' defined as "A Call For Tender in response to which a Tender is submitted".

**Comment by JachymHercher** [comment]
I'm not sure the definition is syntactically correct. I would say "responds to" (a relationship) should not have a definition which is a class - "A Call For Tender [...]"?

**Comment by muricna** [comment]
I would tend to agree
