### ISSUE TITLE
eSubmission requirements: cac::EconomicOperatorRole 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#500]
Taken from the notes on the Working Group meeting on 16/01/2024:
At the UBL term:cac::EconomicOperatorRole taken from ESPD Response Technical Overview (https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html),

Comment reads:  "this can be inferred from epo:OrganisationGroup epo:hasMember (epo:leadBy) org:Organization; 
ePO team to check all values from codelist at-voc:eo-role-type and see if they map to ePO roles. "

**Comment by andreea-pasare** [comment]
The 5 values of the code list [eo-role-type](https://publications.europa.eu/resource/authority/eo-role-type) can be mapped to ePO v4.0.0 as follows:

- **group-lead (Group leader)** by using the predicate **epo:OrganisationGroup epo:leadBy org:Organization**
- **group-mem (Group member)** by using the predicate **epo:OrganisationGroup epo:hasMember org:Organization**

![image](https://github.com/OP-TED/ePO/assets/88081600/c7e08433-c8d5-4e4a-b296-6f3048996f06)

- **oeron (Other entity (relied upon))** by using the **epo:OtherEntity** concept
- **subcont (Subcontractor)** by using **epo:Subcontractor** concept
![image](https://github.com/OP-TED/ePO/assets/88081600/7b8b409c-a4ee-44a5-92b6-55891eda7b5b)

- **sole-tenderer (Sole tenderer)** can be inferred using the following logic: _epo:Tenderer **epo:playedBy** org:Organization_ that is not linked to any **epo:OrganisationGroup**.
