### ISSUE TITLE
eSubmission requirements: cac::QualifyingParty 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#501]
Taken from the notes on the Working Group meeting on 16/01/2024:
At the UBL term:cac::QualifyingParty  taken from https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html

Comment reads: "from technical handbook: is used to place data about the economic operator that is available from an official list, tenderer register or (pre)qualification system, such as official classification schemes, certificates, the number of employees, references used for the classification, etc.; 
ePO needs to model a Pre-QualificationSystemData that includes the properties from ESPD-EDM model for cac::QualifyingParty."

**Comment by andreea-pasare** [comment]
As of [ePO v4.1.0-rc.2](https://github.com/OP-TED/ePO/releases/tag/4.1.0-rc.2) all concepts related to the cac:QualifyingParty are modeled as NatioPreQualificationData that concerns an Organization:
![image](https://github.com/OP-TED/ePO/assets/88081600/429e80f4-9838-442c-a77b-f1e84c11c11a)
