### ISSUE TITLE
eSubmission requirements: cac::PowerOfAttorney 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#502]
Taken from the notes on the Working Group meeting on 16/01/2024:
At the UBL term: cac::PowerOfAttorney, taken from https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html,

Comment reads: "in ESPD-EDM is a specialisation of cac::Person 
in ePO this can be modelled as an epo:AgentInRole epo:playedBy a person:Person".

**Comment by AchillesDougalis** [comment]
Taken from the notes on the Working Group meeting on 23/01/2024: "How should the ePO implement the power of attorney? 

Should it be implemented as a document, with a Person connected with the power of attorney as well as the organization?"

**Comment by andreea-pasare** [comment]
As of [ePO v4.1.0-rc.2](https://github.com/OP-TED/ePO/releases/tag/4.1.0-rc.2) the Power of Attorney (as well as the Mandate) is modeled as a Document that are linked to a Legal Representative. The implementation is depicted below:
![submission eo roles](https://github.com/OP-TED/ePO/assets/88081600/daeed9d7-9998-4937-ac6c-e200804945d6)
