### ISSUE TITLE
GLOSSARY - Abnormally low tenders

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#51]
#### Current Definition:

There are one or several bids with unexpected cheap prices.

#### New Definition:

A tender that is judged by the contracting authority as abnormally low based on technically, economically or legally unsound assumptions or practices.

#### Reason:

The motives why a a tender can be considered low are not always economic, they can also be technical and/or legal (see Directive 24, Recital 103 and other).

**Comment by muricna** [comment]
A tender that is judged abnormally low based on technically, economically or legally unsound assumptions or practices.

DECISION WG 18/04/2018
Discussion that Contracting authority was not directly present in the concept

**Comment by muricna** [comment]
Also title to be changed and put in the singular to be conform with ISO

Abnormally low tender
