### ISSUE TITLE
GLOSSARY - Access Tool

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#52]
#### Current Definition:

The website where access to devices is possible.

#### New Definition:

Software solutions and electronic devices for communication and exchange of information between contracting authorities and economic operators for the life-cyle of the procurement procedure.

#### Reason:

The current definition restricts the access to a website. The tools and devices can be multiple and heterogenous, and for multiple purposes and in different moments of the procedures.

**Comment by muricna** [comment]
Look into reusing channel:  Core public services vocabulary as generic term and make specialisations
Link to digital single gateway
CG: Need change request to define Channel
To be discussed further in issues and decision in meeting of 27/04/2014

Meeting: 18/04/2014

**Comment by ocorcho** [comment]
Change term to Access Tool, to correct typo

**Comment by sembu-rpam** [comment]
The point is that the entry currently present in the spread-shet contains this typo, and the method  explained in the wiki stated that the title of the Issue needs to capture the entry as it is. 

Fortunately this doesn't happen frequently.

**Comment by muricna** [comment]
to be discussed in meeting of 4/5/2018

**Comment by muricna** [comment]
Please update spreadsheet

**Comment by muricna** [comment]
This was extensively discussed at the face to face meeting on 19/02/2019  see electronic means of Communication.  See also comments of things to be retrieved from previous diagrams.

**Comment by jseguraf** [comment]
The predicates from previous versions have been retrieved.
