### ISSUE TITLE
Methodology used for GitHub issues and discussions

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#526]
Create a one-pager describing how we manipulate GitHub issues and discussions.

**Comment by AchillesDougalis** [comment]
Created a link to discussions from the [readme](https://github.com/OP-TED/ePO/blob/master/README.md) file, and also created and pinned a [discussion](https://github.com/OP-TED/ePO/discussions/532),  explaining how someone should use issues and discussions.
