### ISSUE TITLE
GLOSSARY - Buyer

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#53]
#### Current Definition:

The buyer is the entity whose budget will be used to purchase the goods. This may be different from the procuring entity who may be specified in the tender data.

#### New Definition:

Body that manages the budget allocated for the procedure and pays for the items being procured. It may be different from the procuring entity.

#### Reason:

Misuse of the term "tender". The term "Tender" is reserved to the offer submitted by the economic operator or a service provider on its behalf. Using "tender" to replace "procurement procedure" is a non-allowed synechdoque.

**Comment by muricna** [comment]
Concept: Buyer
Definition: Organisation that manages the budget allocated for the procedure and pays for the items being procured.
Notes : The buyer  may be different from the procuring entity.
NM see if possible in VocBench
Meeting 18/04/2018 Check& discuss  27/04/2018

**Comment by andreea-pasare** [comment]
At the moment, in ePO version 3.0.1, the Buyer concept is defined as follows:

_A role of an agent that awards a contract and/or purchases items._

_Additional information:
In public procurement the role of buyer is carried out by the following types of organisation contracting authority, contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority.
In pre-award, the buyer generally awards the contract, however future purchasers may be foreseen.
In post-award the buyer generally refers to the purchaser of items._
