### ISSUE TITLE
Problem with semantics of `epo:hasPrimaryContactPoint`

### ISSUE THREAD

**Issue by schivmeister** [OP-TED/ePO#531]
# Issue

An `epo:Organization` currently has one association to `cpov:ContactPoint` via the `epo:hasPrimaryContactPoint` relationship (object property), with unrestricted cardinality. This means there can be multiple such associations. This, however, is incompatible both with its name and practical usage requirements.

![image](https://github.com/OP-TED/ePO/assets/1151152/fcb2a717-6b74-4126-a3c9-39c929d82032)

By definition, there can only ever be one "primary" instance of a thing. In this context, an organization can have multiple contact points, but only one of them can be the default, main or primary. A data [example](https://github.com/OP-TED/eForms-SDK/blob/1d6408b7fb153d578fbf80863323121d37f047e3/examples/notices/cn_24_maximal.xml#L67) can be seen in the eForms specification, where the following structure is typical:

```xml
<Organization>
    <Company>
        <Contact>
    <TouchPoint1>
        <Contact>
    <TouchPoint2>
       <Contact>
    ...
```

In this example, the company that represents the organization has a single, default contact point, but the organization has multiple contact points that can be reached.

# Recommendation

Based on the semantics of a relationship between an organization and its contact points, one of the following solutions can be considered for the ePO model:

1. The relationship `epo:hasPrimaryContactPoint` shall be supplemented with a sibling `epo:hasSecondaryContactPoint`, with cardinality restricted to 1 in the former relationship.
2. The relationship `epo:hasPrimaryContactPoint` shall be renamed to `epo:hasContactPoint` with cardinality intact (unrestricted).

The second solution leaves the issue of identifying a primary contact point open, but is the least invasive approach.

Additionally, the `cpov:ContactPoint` class should facilitate providing both an internal identifier and a name, as contact points are expected to also be cross-referenced, and they should be user-identifiable by name (that is different from the contact person's name represented by `epo:hasContactName`).

**Comment by andreea-pasare** [comment]
Thank you for your comment. We agree that the cardinality for `epo:hasPrimaryContactPoint` should be 0..1. The change should be implemented in ePO v4.1.0.

The `epo:hasPrimaryContactPoint` predicate represents the contact point of the Legal Entity. The other contact points used in eForms should be represented via the `epo:AgentInRole epo:hasContactPointInRole epo:ContactPoint`:

![image](https://github.com/OP-TED/ePO/assets/88081600/049fd90d-8cfa-4244-8a7c-c98341f8aa7c)
