### ISSUE TITLE
GLOSSARY - Buyer Role

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#54]
#### Current Definition:

It identifies the function of the buyer in this procurement process.

#### New Definition:

Identifies the function of the buyer in the procurement procedure.

#### Reason:

Style: definitions should not start with a pronoun "It".

**Comment by muricna** [comment]
To be discussed later depending on design and modelling.  Rather than at a conceptual level more categorisation of roles in a process

Meeting 18/04/2018

**Comment by paulakeen** [comment]
We should remove this entry....it's a property of Buyer. It should be considered an additional information to explain in the context of Buyer.

The Ontology needs to take it into account though as a relevant data element.

**Comment by muricna** [comment]
Meeting of 27/4/2018 decided to cover properties and concepts putting in the issues whether concepts or issues

**Comment by muricna** [comment]
WG 4/5/2018
The disussion is unresolved and needs to be further discussed

Term Buyer role:  The word role should be replaced as the roles belong to organisations
 suggested terms: Buyer function, Buyer Type, Buyer mode
Definition
Nature and function of the buyer
Natue and activity of the buyer

The idea is that this concept should cover CPB, outsourced buyer and private or public bodies
The WG feels the need to reflect on whether the fact that a CPB is a buyer or not is relevant.  Is the relvance not to be more related to the procuring entity.

**Comment by muricna** [comment]
WG Decsion 14/03/2019: The organisation role does not exist in the ontology, it is drawn up via the predicates to organistion.
