### ISSUE TITLE
GLOSSARY - Calculation Method Value

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#55]
#### Current:

* Current Term: Calculation Method Value

* Definition: The technique used for determining the estimated cost of the concession.

#### New:

* Term: Value Calculation Method

* Definition: The technique used for determining the estimated cost of a concession.

#### Reason:
It makes more sense.

**Comment by muricna** [comment]
WG meeting 25/05/2018
It was decided to separate Calculation Method and Value giving:

Term: Calculation Method
Definition: Formula for obtaining values

This allows the reuse of calculation method in other parts of the ontology as well as the reuse of value

**Comment by eprocurementontology** [comment]
WG approval 01/06/2018

Term: Calculation Method 
Definition: Formula for obtaining values.
Additional information/WG discussion points: The possible values are monetary values, ranking scores,  criterion weighting.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
