### ISSUE TITLE
GLOSSARY - Performance Staff Qualification

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#56]
#### Current:

* Term: Performance Staff Qualification

* Definition: The professional capacity required   to the staff that will perform the contract.

#### New:

* Definition: Indicates whether the the names and professional qualifications of the staff assigned to perform the contract have to be provided or not.

#### Reason:

It is a requirement issued by the Procuring Entity at tendering time.

If true, this is to be taken into account in the ESPD to require this specific requirement as part of the Selection Criteria.

**Note for the future**: If this is already specified as a selection criterion in the ESPD this indicator would then be unnecessary in the Contract Notice.

**Comment by schmice** [comment]
Hello

New definition has a repetition :

"Definition: Indicates whether the the names and professional qualifications of the staff assigned to perform the contract have to be provided or not"

Thanks for correcting
Best regards


Claude SCHMIT
C.2.002 • TED Dissemination

[logo signature mail]

Publications Office of the European Union

2, rue Mercier • L-2985 Luxembourg
FISR 01/113
Tel. +352 2929-42326
claude.schmit@publications.europa.eu<mailto:claude.schmit@publications.europa.eu>
http://publications.europa.eu
<http://publications.europa.eu/>

**Comment by muricna** [comment]
The definition should be a description of the concept.  An idicator shows whether the concept is taken into consideration or not for example in the eForms

**Comment by muricna** [comment]
Covered by aggregation of the ESPD.
