### ISSUE TITLE
Possible redundancy between epo:LeadBuyer and epo:OrganisationGroup  epo:leadBy org:Organization

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#562]
### Discussed in https://github.com/OP-TED/ePO/discussions/561

<div type='discussions-op-text'>

<sup>Originally posted by **muricna** February 12, 2024</sup>
</div>

**Comment by AchillesDougalis** [comment]
Added the clarification in the predicate **epo:leadBy**: "The epo:OrganisationGroup **epo:leadBy** org:Organization :was implemented to be used in case of an Economic Operator Group.
