### ISSUE TITLE
Create instance diagrams for eAccess module

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#566]
Create an instance diagram for:

-   Exclusion ground "Payment of Taxes"
-  Selection criteria for yearly turnover. 
-  professional risk insurance.

**Comment by andreea-pasare** [comment]
The instance diagrams for Selection Criteria "General Yearly Turnover" and "Professional Risk Insurance" were created and presented in [WG meeting](https://docs.ted.europa.eu/epo-wgm/notes/2024-02-01-wgm.html).
The instance diagram for Exclusion Ground "Payment of Taxes" was created and presented in [WG meeting](https://docs.ted.europa.eu/epo-wgm/notes/2024-02-15-wgm.html).
