### ISSUE TITLE
GLOSSARY - Subcontracting Part

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#57]
#### Current:

* Term: Subcontracting Part

* Definition: It indicates the  part or parts of the contract the successful tenderer intends to subcontract beyond the required percentage

#### New:

* Term: Subcontracting Percentage

* Definition: The   minimum percentage of the contract value that the contractor will   subcontract.

#### Reason:

The Procuring Entity is only interested about whether the EO is in the boundaries allowed by the law concerning relative quantity of works subcontracted. This is always expressed as a percentage. 

**Note for the future**: This is already taken into account by the ESPD, and makes more sense in the ESPD as it is about the response of the Economic Operator (in the ESPD Response) to an ESPD Request issued by the Procuring Entity.

**Comment by jseguraf** [comment]
The "Subcontracting Percentage" was renamed by "Estimated Share" and it can be found within the "Subcontract" class in the eAward diagram
