### ISSUE TITLE
GLOSSARY - Follow Up Contract

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#58]
#### Current definition:

* Definition: A service contract following the   contest will be awarded to the winner or one of the winners of the contest.

#### New definition proposed:

* Definition: Indicates whether subsequent service contracts will be awarded to the winner or one of the winners of a design contest by a negotiated procedure without publication.

#### Reasons:

1. More complete definition;
2. Respect for the structure of the definitions used for indicators.

**Comment by muricna** [comment]
What is the term?

**Comment by paulakeen** [comment]
Follow up contract (see title). OK, I added also to the body of the issue.

**Comment by andreea-pasare** [comment]
The latest version of ePO, 3.0.1, contains a Contract concept with the following definition:

_A voluntary, deliberate, and legally binding agreement between two or more competent parties._

_Additional information:
This includes concession contracts.
(WG approval 01/06/2018)_
