### ISSUE TITLE
GLOSSARY - Invitations Dispatch Date

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#59]
#### New definition proposed:

* Definition: Estimated date for the Buyer to send invitations to candidates in two-phase procurement procedures.

#### Reason:

Definition accuracy.

**Comment by muricna** [comment]
What is the term?

**Comment by paulakeen** [comment]
The term HAS TO BE always in the title, as specified in the [Glossary management](https://github.com/eprocurementontology/eprocurementontology/wiki/Glossary-Management). But yes, we'll also add it to the template so the Term can be reminded to the Issue reader.

**Comment by jseguraf** [comment]
The "Invitations Dispatch Date" was renamed by "Estimated Interest Invitation Date" and it can be found within the "Procedure Terms" class.
