### ISSUE TITLE
Need to indicate if a LotGroup is suitable for SMEs see eforms BT726

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#593]
The indicator is in the ProcurementObject LotGroup, is not a ProcurementObject in the ePO

**Comment by andreea-pasare** [comment]
During WGM 09/07/2024, the boolean `epo:isSMESuitable` was added at the level of `epo:LotGroup`:
![image](https://github.com/OP-TED/ePO/assets/88081600/5b46a823-3bcc-4513-8dd2-8b165eb48b0e)
