### ISSUE TITLE
Remove epo-con:ContractModificationInformation from core module

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#596]
`epo-con:ContractModificationInformation` should be in [eContract](https://github.com/OP-TED/ePO/tree/master/implementation/eContract) instead of [ePO_core](https://github.com/OP-TED/ePO/tree/master/implementation/ePO_core). To be moved in 4.1.0 release. 
![image](https://github.com/OP-TED/ePO/assets/143995053/39ede0f5-6c96-45ee-8f23-c9d7f1a30668)

**Comment by andreea-pasare** [comment]
epo-con:ContractModificationInformation is a concept that belongs to eContract module and should not be present in any diagram of ePO core module, thus it was removed from the ePO core module diagram (for 4.1.0-rc.3 version) as depicted below:
![image](https://github.com/OP-TED/ePO/assets/88081600/66f8c905-6aa1-42fb-84fd-5cc1621df574)

**Comment by andreea-pasare** [comment]
Closing this issue and a new one will be created in 4.2.0 milestone since we need to implement this in ePO 4.2.0 as well.
