### ISSUE TITLE
ESPD Request is a Procurement Document it is only represented in ePO as a document

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#598]

**Comment by andreea-pasare** [comment]
Fixed and will be visible in ePO 4.1.0-rc.3 version:
![image](https://github.com/OP-TED/ePO/assets/88081600/6491a32c-4116-465e-a8a6-983a3db45c76)

**Comment by andreea-pasare** [comment]
Closing this since it was implemented in ePO 4.1.0:
![image](https://github.com/user-attachments/assets/b88a3727-6335-4754-92af-594b762c9d8a)
