### ISSUE TITLE
GLOSSARY - Process

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#60]
#### Current:

* Term: Process

* Definition: A class to describe a   justification for the choice of tendering process.

#### New: 

* Term: Procedure Choice Justification

* Definition: The reason why the procuring entity has followed a particular tendering procedure for the procurement procedure.

#### Reason:

The term "process" is too broad and this refers to a very particular data element that has its own semantics.(which should be a code, by the way, as the reasons need to be limited to machine-interpretable semantics, especially for transparency and monitoring).

**Comment by muricna** [comment]
I am not sure that the term and definition match.  Is there a mistake?

**Comment by muricna** [comment]
The word tendering should be removed from the definition this adds nothing to the definition and creates a further concept.

**Comment by muricna** [comment]
The concept term has been defined as "A governing condition or stipulation"
