### ISSUE TITLE
ESPD Response should be renamed ESPD

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#607]
The ESPD Response is actually the ESPD so the response in the term is redundant.  We make think of this in terms of Forms and Notices, the ESPD Request is the "form" and the ESPD the "Notice".

**Comment by andreea-pasare** [comment]
Fixed and will be visible in ePO 4.1.0-rc.3 version:
![image](https://github.com/OP-TED/ePO/assets/88081600/d3108d89-e5ea-4d35-ab0a-40648bb07842)

**Comment by andreea-pasare** [comment]
During the WGM of 09/07/2024 it was agreed that the predicate `epo-sub:refersToOtherESPDResponse` should be removed and `epo:refersToPrevious` at the epo:Document level to be used instead:
![image](https://github.com/OP-TED/ePO/assets/88081600/b1f25408-fd8b-4aaf-8b5a-885bdbc182ce)

**Comment by andreea-pasare** [comment]
The predicate `epo-sub:refersToOtherESPDResponse` should be also removed in version 4.2.0-rc.2.

**Comment by andreea-pasare** [comment]
Closing this issue since a new issue was created for ePO 4.2.0: #688.
