### ISSUE TITLE
GLOSSARY - Decision Binding Contracting

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#61]
#### Current:

* Term: Decision Binding Contracting

* Definition: The statement of the jury is   mandatory on the buyer.

#### New:

* Term: Jury   Decision Binding

* Definition: Indicates   whether the procuring entity is bound to apply the decision of the jury in a   contest design procedure.

#### Reason:

It only applies in the case of design contest. See  Annex V   PART E Information to be included in design contest notices.

**Comment by muricna** [comment]
Definition: The conclusion of the jury is final.

**Comment by paulakeen** [comment]
In the document about how to write definitions we're recommending to keep constant structures when defining the same type of data element.

In the case of indicators we should agree on such a "regular" structure, which should somehow clarify that the concept is about an indicator.

**Comment by muricna** [comment]
The definition should be a description of the concept. An idicator shows whether the concept is taken into consideration or not for example in the eForms

**Comment by eprocurementontology** [comment]
WG approval 13/07/2018

Term: Jury Decision Binding
Definition: The procuring entity is bound to apply the decision of the jury in a contest design procedure.

The glossary and the conceptual model have been updated accordingly on 19/07/2018.

**Comment by JachymHercher** [comment]
I suggest removing "in a contest design procedure" - this doesn't need to be in the concept (and makes it more widely usable, if ever needed.)

(It should be noted that this issue is the same as #67.)

**Comment by muricna** [comment]
I agree this could be used in a usage note as an example.

**Comment by jseguraf** [comment]
The model and the concept have been updated accordingly.
