### ISSUE TITLE
List all "at-voc-new:" codelists

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#612]
List all "at-voc-new:" codelists indicating which module it is found in.

**Comment by cristianvasquez** [comment]
Hi, this is a diagram of some `at-voc-new` elements, perhaps useful


![](http://www.plantuml.com/plantuml/img/dLXBRzim3BxxLmGv3d3GN7KOchbT5o1DizJTfUX1bLdNW6rbafoX6_RV9ybE8kjX9xl554cHd_ZuskYQ2yn4KvKHAJ7daodiA5fJKH2OJlv4audwPl06ZATqmoY1h64mGLf--dwUlrYwhOzEiVjulfhDZehlc2lnMq6mA6YTq5f0BTAFdJB28jvJ4jVm2zM6KhoJLi1ZqYh7GchpWzk_KGHrKqscXl5U_fQca5FseVBnAb6M0SEl9SHDNOY3ce77CSyJ93AE5UIut49UL5R4fJg8MNkYWlla3qumN7DCT68oewnGlxXxlye09LZWakODh8hw58S-uZiW4YBWIm5LYxYMwy_ZosYH3FlXaEsJJBOVU1-8tdCThDDJpCanv8Hc5WJ-rBmUD-nO9rhKVZ_FDMmzpKU1wmophE2GgU03bbUkPVAEMGxB-esoIXUIOUMUdPxCUWC5Q1zwwLi94wLthD8-54tDT-GKLKRQh6NNEK_bYVp78asw-dLHDglRY-qDbCKUfEb0V5cd4nSo1jrHNbSBGe1pUP6toCpi2hw5NOa9VFau9yF7jdg9_IwowRA6YFwnzt5fjIkXalC0ZqHd67t3lsKbqKO_tzFwviv5DyDr3aogn3cb6O_BWXizeJ9byBCfc9n0_WjzFM_EXhQKoY9_5vr4-GLUv7KxuRYG0jvLlTVTw71ixzYi5klrSdqtsopNyZDvkD_Sfijq-R3sI19RyFrH2cuMczcFsqKgVsvl7vzMwInPj8hhTBj8vEUzfsDqIpejewNkfDyfSQy2VGxTgd3ytr3ILDvbadKdzYqEi6vN1DU7hqw2ocecxWln8Lyf2xlKCsDi4NnbE5UvEEalkZlSakxT7WOv0NOggnL-XTAvGqjTV8bf6PTAQHJga4qeVtjUEx6r6eUnQGMepuofENyPChwdcTgipEkaEXmE9TU_B_ZYbikWtgb7mlLerdYdrQDrSVnvCfrF7Mw3_6GlilQVDbSJRkghMJIy6psHAF2cVUA9F5Go2b4XCnqZJEJdHqFPs0wCNHtPO0LGwCztvE6AOGGkc-jeX4M74hLkwZDaDC0zXX_0zMpJQXHaePTw3X5dT1PJZOP6QU16QsoZqBWTAT9-cNNB4JchSHIFCIzUfdncGVWs7nedbPVqLOXMNjgR1jCynzJF7L2GZFvdIWuVFHTuBuz0ewprKjGEhFMYAlDiNJJu5rOqP7eSsKER4eNNyhXp5rvdmwBnjHyDKgBGHK4-WxmCAh9REU3NNFt8IwUZaL8F5LwVCA0GbOwkeSxKluh-0G00)

**Comment by AchillesDougalis** [comment]
Found these from the glossary files:

- epo-core:  
  - at-voc-new:certification-label-type

- eCatalogue: 
  - at-voc-new:activity-code
  - at-voc-new:delivery-item-type
  -  at-voc-new:document-type
  - at-voc-new:dangerous-goods-list
  - at-voc-new:item-classification
  - at-voc-new:orderable-unit
  - at-voc-new:price-type
  - at-voc-new:tax-category
  - at-voc-new:tax-scheme
  - at-voc-new:transaction-conditions
  - at-voc-new:ResponseStatus (external)
  - at-voc-new:document-status (external)
  
 - eOrdering
   - at-voc-new:tax-category (external) 
   - at-voc-new:tax-scheme (external)
   - at-voc-new:allowance-charge-reason (external)
   - at-voc-new:ResponseStatus
 
 - eFulfilment

   - at-voc-new:allowance-charge-reason (external)
   -  at-voc-new:despatch-advice-type
   - at-voc-new:handling-instruction 
   - at-voc-new:packaging-type
   - at-voc-new:reject-reason
   - at-voc-new:action-code
   -  at-voc-new:size-type
   - at-voc-new:transport-equipment-type
   - at-voc-new:transport-means-type 
   -  at-voc-new:transport-mode
   - at-voc-new:document-status
