### ISSUE TITLE
ePO: subcontractor has no relation with ePO: Contractor

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#617]
There is no relationship in the ontology between the Contractor and the Subcontractor, however the Subcontractor can only exist if there is a Contractor

**Comment by andreea-pasare** [comment]
During WGM 09/07/2024, the predicates `epo:foreseesSubcontractor` and `epo:hasSubcontractor` were added as in the diagram below:
![image](https://github.com/OP-TED/ePO/assets/88081600/7c05c7e2-55fe-4123-8643-b14b44bb5c4f)
