### ISSUE TITLE
GLOSSARY - Free Access

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#62]
#### Current:

* Term: Free Access

* Definition: Non-payment required for   unrestricted and full availability of tendering documents.

#### New:

* Term: Free e-Acess

* Definition: Indicates whether the procurement documents are electronically available for unrestricted and full direct access, free of charge.

#### Reasons:

1. more complete and accurate term and definition;
2. Respect for the structure when defining indicators.

**Comment by muricna** [comment]
Should the term not be moved to documents in general and the term procurement be removed from the definition to allow later reuse of the concept.

**Comment by JachymHercher** [comment]
Shouldn't "free" and "direct" be attributes of _something_? 

Proposal: "direct" should be an attribute of a "URL" (e.g. the URL for the procurement documents); "free" should be an attribute of the procurement documents themselves? (Or perhaps some further intermediary, as I guess that "electronic procurement documents" might sometimes be free, while "paper procurement documents" would not.)

**Comment by andreea-pasare** [comment]
In ePO 3.0.1, the Access Term concept involves a Procurement Document. 
At the Access Term concept level we have the attribute epo:hasPublicAccessURL with the definition: "Web page where the procurement documents can be downloaded.". 
Below there is a diagram showing how the concept Access Term is modeled in ePO 3.0.1:

![image](https://user-images.githubusercontent.com/88081600/194824702-76d331ac-5ee7-4591-b76e-f91f95850cdf.png)
