### ISSUE TITLE
eforms BT-730 Subcontracting Value Known.  There does not seem to be a mapping in ePO to this

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#624]

**Comment by andreea-pasare** [comment]
The `epo:isSubcontractingValueKnown` attribute was added as a `xsd:boolean` data type at the level of the `epo:SubcontractingEstimate` concept:
![image](https://github.com/user-attachments/assets/e85de483-8d32-4ce8-a3ae-30801ac3ffea)

**Comment by andreea-pasare** [comment]
The `epo:isSubcontractingPercentageKnown` attribute was added as a `xsd:boolean` data type at the level of the `epo:SubcontractingEstimate` concept:
![image](https://github.com/user-attachments/assets/dcb1461e-d8af-4d7e-9f35-82120bd6275b)

BT-730-Tender ("Subcontracting Value Known") and BT-731-Tender ("Subcontracting Percentage Known") are forbidden unless BT-773-Tender ("Subcontracting") is "yes".

**Comment by cristianvasquez** [comment]
This might be a detail about naming.

With `epo:isSubcontractingValueKnown` one will expect a boolean, and it is
with `epo:isSubcontractingPercentageKnown` one would also expect a boolean but is a PlainLiteral, 

wouldn't it be better-named `epo:knownSubcontractingPercentage` or something like that?

**Comment by muricna** [comment]
BT-731 requires indeed  a boolean and not plain text.  And there should also be a hasEstimatedValue with data type value (BT-730)

**Comment by andreea-pasare** [comment]
![image](https://github.com/user-attachments/assets/2f837d32-ba7b-4072-b38c-041a1a577976)

**Comment by AchillesDougalis** [comment]
This has been implemented for ePO 4.2.0.
