### ISSUE TITLE
Missing cardinality for epo-cat:hasExternalSpecification property

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#628]
Provide cardinality for **epo-cat:hasExternalSpecification**:
![image](https://github.com/OP-TED/ePO/assets/88081600/f924be22-15c2-4e1d-b634-32b52ab44b60)

**Comment by idolum** [comment]
@andreea-pasare Why was epo-cat:hasExternalSpecification added? It wasn't present in v3.

In CEN/WS BII3, there was such a association. Back then it had the cardinality `0..n`. But with the `epo-cat:ProductSpecification` have already something similar.

**Comment by idolum** [comment]
Having more than one was also a requirement in CEN/TC 440/WG 5: https://github.com/CEN-TC-440/WG5/issues/45

**Comment by andreea-pasare** [comment]
@idolum, indeed it seems that `epo-cat:hasExternalSpecification` is redundant and it was agreed in WGM 09/07/2024 that the `epo-cat:Item epo:hasSpecification epo-cat:ProductSpecification` mapping to be used instead in all post-award modules. We added a temporary cardinality for `epo-cat:hasExternalSpecification` predicate as `[0..*]` with a proposal to remove it in a next major release (ePO 5.0.0). (https://github.com/OP-TED/ePO/issues/654)
![image](https://github.com/OP-TED/ePO/assets/88081600/c6fb6deb-15a4-43e7-a76f-fa793f83263e)
