### ISSUE TITLE
eForms touchpoints

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#629]
In eforms the touchpoint may have a full address this is not foreseen for the agent in role contact point.

**Comment by andreea-pasare** [comment]
The ePO implementation of Contact Point and Address is based on Core Vocabularies. The following should be the proper way of mapping a full address to an Agent in Role:
![image](https://github.com/user-attachments/assets/3173e390-b100-405c-ae2c-a6d7cfbce19d)
