### ISSUE TITLE
BT-543-LotsGroup : Award Criteria Complicated cannot be mapped since there is no association between LotsGroup and AwardEvaluationTerm

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#633]

**Comment by KazikAnhalt** [comment]
Dear Natalie,
I know this is unrelated to the theme but I look for contact person responsible for PPDS strategy on European Commission side to ask for its participation in event dedicated to public procurement that tackle an issue of ESFRI.
I will appreciate you help.
Kazik

**Comment by muricna** [comment]
Dear Kazik,
Please contact ec-ppds@ec.europa.eu..
Kind regards,
Natalie

**Comment by andreea-pasare** [comment]
![image](https://github.com/user-attachments/assets/7279a2ad-ff07-4a7e-9335-beccfef2049b)
