### ISSUE TITLE
StrategicProcurement should be linked to LotAwardOutcome

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#634]

**Comment by muricna** [comment]
We need to see if it indeed needs to be on LotAwardOutcome or AwardOutcome so that it can be specialised for LotAwardOutcome and MiniCompetitionOutCome.  The same for the StatisticalInformation

**Comment by andreea-pasare** [comment]
Added predicate `epo:fulfillsStrategicProcurement` between `epo:LotAwardOutcome` and `epo:StrategicProcurement`:
![image](https://github.com/user-attachments/assets/f7e2459d-8ac3-47e1-aad3-ad7a49111c42)
