### ISSUE TITLE
predicates epo:answersExclusionGround and epo:answersSelectionCriteria may not be needed

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#637]
Predicate epo:answersExclusionGround on module eSubmission added in epo 4.1.0-rc2   may not be needed as it does not appear on any diagram or WG meeting, and it does not have a definition.  If kept, it should use the prefix: epo-sub 
![2024-06-17_18-39](https://github.com/OP-TED/ePO/assets/143995053/30f1c1c2-8171-4b3a-9045-e464860ad0ac)

The same applies for  predicate epo:answersSelectionCriteria on module eSubmission
![2024-06-17_18-41](https://github.com/OP-TED/ePO/assets/143995053/a2f19fb6-7cac-4f26-946f-6e8c38a9bf3e)

**Comment by andreea-pasare** [comment]
During the WGM of 09/07/2024 it was agreed that the two predicates `epo:answersExclusionGround` and `epo:answersSelectionCriteria` should be removed.
