### ISSUE TITLE
predicate epo:hasRejectedQuantity should change prefix to epo-ful

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#638]
predicate epo:hasRejectedQuantity  (added in epo 4.1.0 -rc2 should change prefix to epo-ful as it only appears on that module.
![2024-06-17_18-45](https://github.com/OP-TED/ePO/assets/143995053/b1811cf4-5262-40da-ab9c-7d53cf1b6a5d)

**Comment by andreea-pasare** [comment]
During WGM of 09/07/2024, the prefix modification was done according to the next diagram:
![image](https://github.com/OP-TED/ePO/assets/88081600/f4f0c463-cac6-4d48-90a9-3980a03c279f)
