### ISSUE TITLE
Investigate attributes on epo-cat:ItemProperty

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#642]
It was decided on the WG meeting of 20/6/2024 to Investigate whether the attributes epo-cat:hasAttributType, epo-cat:hasClassificationScheme and dct:title of class epo-cat:ItemProperty  should be mandatorty or not. 
![GetImage (2)](https://github.com/OP-TED/ePO/assets/143995053/cc99ec0c-2486-4206-aa6b-010962b686ad)

**Comment by andreea-pasare** [comment]
In WGM of 26/06/2024 it was agreed to put all [0..1] cardinality to all attributes from epo-cat:ItemProperty concept in order to accommodate for both catalogue and invoicing data models:
![image](https://github.com/OP-TED/ePO/assets/88081600/2461eb39-b425-4670-98f3-8febf85c2bab)
