### ISSUE TITLE
BT-1561 in eForms is not mappable to the ontology, the ontology is missing a relation.

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#644]
BT-1561 is not mappable as the ontology is missing the predicate epo:hasApproximateFrameworkAgreementValue between epo:LotGroupAwardInformation and epo:MonetaryValue.

**Comment by andreea-pasare** [comment]
Since the BT-1561 is in the context of LotGroup, the predicate `epo:hasApproximateGroupFrameworkAgreementValue` was added accordingly:
![image](https://github.com/user-attachments/assets/4ec807f2-9368-48e4-a001-42354ec84f34)
