### ISSUE TITLE
GLOSSARY - Dynamic Purchasing System (DPS)

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#65]
#### Current:

* Term: Dynamic Purchasing System (DPS)

* Definition: Estimated limit time of a Dynamic Purchasing System (DPS), which is a completely electronic process for making commonly used purchases.

#### New Definition:

An electronic system that can be established to purchase goods and services which are:

1. Commonly used by one Procuring Entity, and
2. Readily available on the market

Source: Procurement Journey (https://www.procurementjourney.scot/dynamic-purchasing-systems-dps)

Additional information: A Dynamic Purchasing System (DPS) is similar to an electronic framework agreement, with two exceptions, new suppliers can join at any time and it is to be run as a completely electronic process (source: https://www.procurementforall.co.uk/performance_measurement/what_is_a_dynamic_pu/).

#### Reason for this proposal for improvement:

The definition provided up to now is not applicable to the concept, and in any cases did not define at all the concept.

**Comment by eprocurementontology** [comment]
WG approval 13/07/2018

Term: Dynamic Purchasing System (DPS)
Definition: An electronic system that is set up by a procuring entity which lists the economic operators that satisy the selection and exclusion criteria. This technique then allows the purchase via consulation of the listed tenderers using award criteria.

The glossary and the conceptual model have been updated accordingly on 20/07/2018.
