### ISSUE TITLE
Typo in epo-inv:hasTotalAccountingCurrencyTaxAMount

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#652]
predicate `epo-inv:hasTotalAccountingCurrencyTaxAMount` should be renamed to   `epo-inv:hasTotalAccountingCurrencyTaxAmount` 
![image](https://github.com/OP-TED/ePO/assets/143995053/a04f878e-c789-44b7-b94d-c0dc6883a24d)

**Comment by andreea-pasare** [comment]
Fixed and will be published in ePO 4.2.0-rc.1:
![image](https://github.com/OP-TED/ePO/assets/88081600/5215829d-e35e-463b-adfa-9118c166bda9)
