### ISSUE TITLE
Change the cardinality of predicates epo-inv:refersToInvoice and epo-inv:isSubmittedForInvoiceLine

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#653]
In [the biannual ePO Working group meeting in July 2024
](https://docs.ted.europa.eu/docs-staging/epo-wgm/_attachments/work_group_meetings_reports/2024_WGM_July/eProcurementOntology-July2024.pptx)it was noted that a `epo-inv:CreditNote` may not always refer to a specific `epo-inv:Invoice`. Thus, the cardinality of the predicate `epo-inv:refersToInvoice: epo-inv:CreditNote → epo-inv:Invoice [1]` should change to  `[0..1]`. 

The same applies to predicate  `epo-inv:isSubmittedForInvoiceLine: epo-inv:CreditNoteLine → epo-inv:InvoiceLine [1]`, it should change to `[0..1]`.

![image](https://github.com/OP-TED/ePO/assets/143995053/02338a0c-23b4-49f6-b62b-08d1e7f9dc10)

**Comment by andreea-pasare** [comment]
Fixed and will be published in ePO 4.2.0-rc.1:
![image](https://github.com/OP-TED/ePO/assets/88081600/ae179f69-153b-4cfe-b960-aed44c74cf1f)
