### ISSUE TITLE
Delete predicate epo-inv:hasTaxCategoryTaxableAmount

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#657]
On WGM 11/7/24 it was decided that the Predicate  `epo-inv:hasTaxCategoryTaxableAmount: epo-inv:TaxBreakdownInformation → epo:MonetaryValue [1]` is unnecessary due to the fact that the classes `epo-inv:TaxBreakdownInformation` and `epo:MonetaryValue` are connected through class `epo-ord:TaxInformation` as seen on the image below. To be deleted. 

![image](https://github.com/user-attachments/assets/57fa9e59-ba70-4771-b19f-20a03918efec)

**Comment by andreea-pasare** [comment]
The predicate was removed:
![image](https://github.com/user-attachments/assets/3a316286-8968-4ebe-9da2-b51910267ce7)
