### ISSUE TITLE
Investigate whether predicates epo:hasNoticeType and epo:hasFormType should be deleted

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#663]
Further Investigate whether we should remove the  `epo:hasNoticeType: epo:Notice → at-voc:notice-type`  and `epo:hasFormType: epo:Notice → at-voc:form-type` since the values of the codelists are represented as concepts in ePO.

![image (2)](https://github.com/user-attachments/assets/82e0e7bd-55c6-44a4-94f2-9afb6bcf5834)

**Comment by andreea-pasare** [comment]
In the ontology, the notice is considered to be a form that has been filled in.

It was agreed that the predicates `epo:hasNoticeType` and `epo:hasFormType` will remain in the ontology, since the instance objects (blue boxes) are not exported by model2owl in the RDF output.
