### ISSUE TITLE
GLOSSARY - Decision Binding Contracting

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#67]
#### Current:

* Term:  Decision Binding Contracting

* Definition: Indication whether the jury 's decision is binding on the contracting authority

#### New:

**WE SHOULD NOT HAVE THIS ENTRY IN THE GLOSSARY**. However we should, perhaps, propose a new entry "Design Contest Jury".

#### Reason:
The e-Forms introduces this indicator because they want to control whether the decision of the Juri is binding or not for the Procuring Entity when awarding winners of a prize. 

The concepts behind to defined should be instead: "

1. Evaluation Board;

2. Jury (a specialisation of Evaluation Board, and add further information like (1) Jurys are only formed when the procurement procedure is a design contest, and whether the decisions of the Jury are binding or not; other); and

3. Prize

**Comment by muricna** [comment]
Maybe jury decision binding is enough

**Comment by eprocurementontology** [comment]
WG approval 13/07/2018

Term: Jury Decision Binding
Definition: The procuring entity is bound to apply the decision of the jury in a contest design procedure.

The glossary and the conceptual model have been updated accordingly on 19/07/2018.
