### ISSUE TITLE
Techniques and usage

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#677]
To fulfil eforms BT-766 The technique DPS has to be instantiated to access the code indicating that there is no dps something similar happens with the usage code list and technique.

Also see BT-765 Framework agreement code you need to instantiate Framework Agreement to say there is no Framework Agreement.

**Comment by andreea-pasare** [comment]
For BT-766 Dynamic Purchasing System, if the code value is `none` in eForms, then the epo:DynamicPurchaseSystemTechnique should not be instantiated.

For BT-765 Framework agreement, the enumeration is associated with the epo:FrameworkAgreementTerm, therefore is no problem in that case.
