### ISSUE TITLE
Possible missing link between LotAwardOutcome and GreenProcurement/VehicleInformation

### ISSUE THREAD

**Issue by schivmeister** [OP-TED/ePO#684]
In [trying to map information related to eForms node **ND-StrategicProcurementInformationLotResult**](https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/51), it was discovered that ePO did not foresee a connection to either `epo:GreenProcurement` or `epo:VehicleInformation` (an association of the latter which itself is a specialization of `epo:StrategicProcurement`) from the `epo:LotAwardOutcome`.

<img width="685" alt="image" src="https://github.com/user-attachments/assets/5c46fc61-e2c1-4889-a589-09a5652c03d2">

The `epo:StrategicProcurement` is connected to an `epo:ProcurementObject`, and `epo:LotAwardOutcome` is only an indirect association (through the specialization `epo:Lot`), which is problematic for the data.

<img width="740" alt="image" src="https://github.com/user-attachments/assets/dae563e9-7668-4138-9fb3-d2bafb1397c4">

The `epo:LotAwardOutcome` is represented in the data by the notion of a _LotResult_, with the following absolute XPath:

```
/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotResult/efac:StrategicProcurement/efac:StrategicProcurementInformation
```

**Comment by andreea-pasare** [comment]
Duplicated issue. See fix in #634.
