### ISSUE TITLE
Remove epo-con:ContractModificationInformation from core module diagram in ePO 4.2.0

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#689]
This was already implemented in ePO 4.1.0 and it needs to be replicated in ePO 4.2.0.

See description in #596.

**Comment by andreea-pasare** [comment]
![image](https://github.com/user-attachments/assets/01230063-4216-4ff8-9233-63af89cc9092)

**Comment by AchillesDougalis** [comment]
To Implement, and to add a diagram showing the epo-con:ContractModificationInformation Class in the Contract Module.
