### ISSUE TITLE
GLOSSARY - Delivery Terms

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#69]
#### Definition:

Conditions that an economic economic must comply with when executing the works, performing the services or supplying the goods specified in the contract.

(Additional details and examples should follow, too, in order to clarify/extend the definition)

#### Reason:

Data elements related to the conditions relating to the delivery would be conceptually grouped in a class instead of being dispersed as different properties of the procurement procedure (and therefore in the Ontology).

**Comment by jseguraf** [comment]
This concept is not currently used in the ontology.
