### ISSUE TITLE
GLOSSARY - Dispatch Date

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#70]
#### Current:

* Term: Dispatch Date

* Definition: Time of transmission of the notice by the buyer.

#### Reason:

It is not a concept in itself, but a property of a Document of type Notice.

Nonetheless, this data element should be taken into account by the Ontology as it is a relevant information requirement of any document exchanged between stakeholders.

**Comment by muricna** [comment]
Meeting of 27/4/2018 decided to cover both properies and concepts

**Comment by eprocurementontology** [comment]
WG approval 13/07/2018

Term: Dispatch Date
Definition: Date of transmission of a record to an organisation.

The glossary and the conceptual model have been updated accordingly on 20/07/2018.

The update in the CM consisted in:

- The class Document has now a new property named "Dispatch Date", as all documents are dispatched.

- The new property "Dispatch Date" is a placeholder for xsd:dateTime, but only dates are expected in this particular case. This is a design decision that is proposed to the WG: all dates and/or times are to be expressed as xsd:dateTime. If you do not agree to this decision please "raise your hand" and supply alternatives and reasons.

**Comment by muricna** [comment]
To be discussed when reviewing the documents conceptual model
