### ISSUE TITLE
Catalogue Response

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ePO#702]
### Discussed in https://github.com/OP-TED/ePO/discussions/524

<div type='discussions-op-text'>

<sup>Originally posted by **idolum** July  3, 2023</sup>
As part of the catalogue choreographies defined in prEN 17015-1 by CEN/TC 440/WG 5, a reponse document to a sent catalogue is needed.

## User Stories

A catalogue provider sends a catalogue to the catalogue receiver. The catalogue is validated by the catalogue receiver and accepted. The catalogue receiver sends a response to indicated to the catalogue provider that the catalogue was accepted and in operation in the ordering system on the buying side.

Another catalogue provider sends a catalogue to the catalogue receiver. The catalogue is validated by the catalogue receiver and was rejected. To reaons why the catalogue was rejected is sent in the response. The reasons for the rejection

1. are provided for the whole catalgue
2. are provided for some of the catalogue lines

## Examples

* https://test-docs.peppol.eu/poacc/upgrade-3/syntax/CatalogueResponse/tree/

## Proposal

Based on the current draft and Peppol:

![image](https://github.com/OP-TED/ePO/assets/1178743/3a0481a5-3ba8-467a-9329-7b01662fcac2)

* Peppol uses a code list UN/Cefact 4343 Response type code (AP= Accepted, RE = Rejected) for the response
  - https://service.unece.org/trade/uncefact/vocabulary/uncl4343/</div>

**Comment by AchillesDougalis** [comment]
check comments 
https://github.com/OP-TED/ePO/issues/453#issuecomment-1729703937
https://github.com/OP-TED/ePO/issues/453#issuecomment-1752134028

To update descriptions of the epo-cat concepts accordingly.

related to https://github.com/OP-TED/ePO/discussions/496

**Comment by andreea-pasare** [comment]
Closing issue since the definition alignment for `epo-ord:hasResponseDescription` is tracked under a different issue: https://github.com/OP-TED/ePO/issues/730
