### ISSUE TITLE
GLOSSARY - Document

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#71]
#### Current:

* Term: Document

* Definition: (No definition is provided in the current glossary)

#### Reason:

It is too generic. In purity this is not a business-related concept. 

However:

1- The Ontology needs to reflect that there are business entities like Notices, Call for Tenders, Technical Specifications, etc. that are works that can be manifested as documents (cfr. IFLA LRM vocabulary). 

2- Some of the concepts behind these types of documents are not currently defined in the glossary, and should be:

Procurement Documents, and subclasses:
- Contract Notice
- Technical Specifications
- Call for Competition, and subclasses of it: Calll for Tenders, Call for Proposals
- Invitation to Tender (is an e-mail a document? Answer: ABSOLUTELY YES!, even more, should be considered a RECORD).
- Other....

Before creating new entries for these concepts please check the current proposal for Procurement Documents in the Conceptual Data model of the ePO v.2.0.0.

**Comment by andreea-pasare** [comment]
The Document concept in ePO 3.0.1 is defined as: "A set of interrelated Business Information representing the business facts and associated metadata. The information may be conveyed in any language, medium or form, including textual, numerical, graphic, cartographic, audio-visual forms, etc."
Below is a diagram of Document hierarchy in ePO 3.0.1:

![image](https://user-images.githubusercontent.com/88081600/194825264-74465148-da2f-4525-8c39-51df2751a08a.png)
