### ISSUE TITLE
GLOSSARY - Duration Or Date Start Date End

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#72]
#### Current:

* Term: Duration Or Date Start Date End

* Definition: Interval between the award of the contract or closing of the framework agreement and its ending, including options and renewals. This duration may be expressed using two dates (start date and end date).

#### Reason:

Refers very explicitely either to the duraton of a Contract, and more specifically is mandatory when a technique like Framework Agreement is used in the procurement procedure.

**Comment by eprocurementontology** [comment]
WG approval 13/07/2018

Term: Agreement Duration
Definition: Period during which an agreement is valid.

Additional information/WG discussion points: Can be expressed as a time period or with a start and end date
An agreement could be for example a contract, a framework agreement or a dps.

The glossary has been updated accordingly on 20/07/2018.

The CM has a class named Period that is used by several classes, e.g. Framework Agreement. Please review whether this class can be used also for the purposes of "Agreement Duration".

**Comment by jseguraf** [comment]
This concept is not currently used in the ontology. The "Period" class is being used for the purposes of the "Agreement Duration" class.
