### ISSUE TITLE
GLOSSARY - Framework Agreement

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#73]
#### Current:

* Term: Framework Agreement

* Definition: No definition is currently available.

#### PROPOSAL: 

* New Definition: An arrangement between one or more contracting authorities and one or more economic operators, the purpose of which is to establish the terms governing contracts to be awarded during a given period, in particular with regard to price and, where appropriate, the quantity
envisaged.

Additional information: The term of a framework agreement does not exceed four years, save in exceptional cases duly justified, in particular by the subject of the framework agreement.

Source: Directive 2014/24/EU, Article 33

https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014L0024&from=EN

**Comment by muricna** [comment]
The terms governing contracts, reached between one more buyers and one or more economic operators during a given period.

WG approval 05/12/2019
