### ISSUE TITLE
GLOSSARY - Contract

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#74]
#### Definition:

Agreement for pecuniary interest concluded in writing between one or more economic operators and one or more contracting authorities and having as their object the execution of works, the supply of products or the provision of services;

Source: based on the 2014/24/EU Directive, Article 2. Definitions.

Additional Information: See also definitions in the Directive about "public works contracts", "public supply contracts" and "public service contracts".

#### Reason:

Not defined in the current glossary

**Comment by muricna** [comment]
Term: Contract
Definition: A voluntary, deliberate, and legally binding agreement between two or more competent parties.

WG approval 01/06/2018

**Comment by eprocurementontology** [comment]
WG approval 01/06/2018

Term: Contract
Definition: A voluntary, deliberate, and legally binding agreement between two or more competent parties.

Additional information/WG discussion points: The contract results in the public procurement domain from a public procurement procedure and is signed between a procuring entity(ies) and economic operator(s)

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
