### ISSUE TITLE
GLOSSARY - Accelerated procedure justification  -- GLOSSARY - Justification

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#75]
#### Current: Accelerated Procedure Justification

* Term: 

* Definition: Explanation why the choice of an accelerated procedure is lawful.

#### Reason:

It is a property of Accelerated Procedure, which has already been defined. See decision in [Issue #50 ](https://github.com/eprocurementontology/eprocurementontology/issues/50).

**Comment by muricna** [comment]
I don't understand the reason.  I would suggest having a general term justification that can be used else where such as C-096

**Comment by muricna** [comment]
Glossary meeting.

Property 

Term: Justification
Definition: Acceptable reason or explanation supporting the lawful usage

Usage: Can be used by different concepts and properties to explan the reason for using them ie Accelerated proced.......(list to be extended)

Needs more discussion whether this is about changing terms of the procedure or contract

**Comment by muricna** [comment]
WG 25/05/2018

Agreed to list the places where this term can be used in the additional information.

Definition may need revising.

**Comment by muricna** [comment]
WG 25/05/2018

Delete change description code and add in additional information of justificaiton #104

**Comment by muricna** [comment]
This is a code list the definition of which was agreed on 28/05/2018 as "A procurement procedure where the limit for receipt of tenders can be reduced due to a state of urgency.
