### ISSUE TITLE
GLOSSARY - Buyer Coverage In Framework Agreement Terms

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#76]
#### Current:

* Term: Added Category Buyer In Framework Agreement

* Definition: Any additonal categories of purchasing agents participating in the framework agreement.

#### Reason:

The main concepts related to this is Framework Agreement and Buyer. This looks like a data element that intervenes in an n-ary relationship between Procurement Procedure, Technique=Framework Agreement and Buyer roles. 

We should check with e-Forms when and why this is necessary and decide whether it is a data element that the Ontology should take into account or not.

**Comment by muricna** [comment]
JH: All buyers concluding a framework agreement must be clearly identified. This indication can either be done for each of the other buyers in the buyer section of the notice, or, on a more general basis, in this field by indicating the category of buyer, e.g. "all municipalities of the Tuscany region". For more information, see 2014/24/EU Art. 33(2) second subparagraph.

**Comment by jseguraf** [comment]
Added Category Buyer In Framework Agreement has been replaced by "Buyer Coergare" in the "Framework Agreement Terms" class.

Term: Buyer Coverage
Definition: Buyers that can use the Framework Agreement not mentioned by name.

Additional Information: e.g. "all hospitals in the Tuscany region

WG Approval 2019-05-06
