### ISSUE TITLE
GLOSSARY - Award Criterion Type

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#79]
#### Current:

* Term: Award Criterion Type

* Definition: The category of the criterion whether it be concerned with the quality of the offer or the  financial offer.

#### Reason:

The concept is Award Criterion. From the Ontology point of view, the type is a property of Award Criterion, a data element (probably a code).

**Comment by guascce** [comment]
Agree to remove from the glossary if the glossary is for concepts
The term offer is used here while in other entries the word tender is used

**Comment by paulakeen** [comment]
Agree to replace the first occurrence of offer with tender....but why not keeping the second occurrence of "offer"....provided we state somewhere else, i.e. in the definition of Tender, that they're synonyms?

**Comment by muricna** [comment]
How many types are theire in this category

**Comment by muricna** [comment]
The model has been developped differently the individual award criterion follow the procurement criterion which is based on espd for the exclusion grounds and the selection criterion.  The final  and  overall award crierion ponderation is based on the evaluation dimensions.

WG 29/01/2019
