### ISSUE TITLE
GLOSSARY - Award Date Scheduled

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#80]
#### Current: 

* Term: Award Date Scheduled  

* Definition: Estimated time of the decision on   the winner of the contract.

#### Reason:

This is a property of the concept "Awarded Contract" (see [Issue #81](https://github.com/eprocurementontology/eprocurementontology/issues/81)).

**Comment by muricna** [comment]
wg 27/04/2018
Not foreseen in eNotification or eAcess to be added later if necssary in another phase of the procurement lifecycle;

Enric please remove if you agree and close
