### ISSUE TITLE
GLOSSARY - Awarded Contract

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#81]
#### Current:

* Term: Awarded Contract

* Definition: The decision on the winner of the procurement procedure has been taken.

#### Reason:

1. The definition provided for "Awarded Contract" presumes that one Procurement Procedure aims always at one Contract, and this is not necessarily true.

2. "Awarded Contracts" are "Contracts", which has been proposed as new entry of the Glossary. Hence, what would be the need of an "Awarded Contract"?

3. In e-Notification, the need is to have the information about all the awarding decisions about all the winners in a Procurement Procedure. Thus we propose to add a new entry "Awarding Result" wich would contain the one or multiple awarding(s) made by the procuring entity for one Procurement Procedure.

**Comment by muricna** [comment]
#We should maybe create award decision see issue #78 and issue #80

Not all procedures end in a contract.
