### ISSUE TITLE
GLOSSARY - Awarding Result

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#82]
### New concept

* Term: Awarding Result

* Definition: The specification and motivation of the decisions made by the Procuring Entity about the resolution of a Procurement Procedure.

Additional information: The Awarding Results specify who has/have been the winner Economic Operator(s), which contracts have they won, the amounts of the awarding, etc. In the cases when there are no winners a justification is provided explaining why no contract has been awarded.

Source: standard practices, e.g. CODICE, UBL, CEN/BII.

**Comment by guascce** [comment]
"which contracts have  they  won" --> "which contracts they have won"
"amonts of awarding, etc.."--> is etc... relevant information

**Comment by muricna** [comment]
##We should perhaps create Award decision See issues #[78](url) and #81
µ
