### ISSUE TITLE
GLOSSARY - Awarded To Group

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#83]
#### Current:

* Term: Awarded To Group

* Definition: The winner of the contract is Consortium, a Joint Venture or another type of group.

#### Reason:

1. Not a concept, it's an indicator. The concept would be "Contract" or "Awarding Result"
2. Ontology: Data element, property of Awarding Resutl. The information can be inferred

**Comment by muricna** [comment]
WG 4/05/2018
Remove

**Comment by eprocurementontology** [comment]
WG approval 04/05/2018

This term has been removed from the glossary.
