### ISSUE TITLE
GLOSSARY - Awarded To SME

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#84]
#### Current:

* Term: Awarded To SME

* Definition: The winner of the contract is a SME (small or medium enterprise).

#### PROPOSAL: WE SHOULD REMOVE THIS ENTRY FROM THE GLOSSARY

Consider defining SME (see [Issue #85](https://github.com/eprocurementontology/eprocurementontology/issues/85)).

#### Reason:
1. Not a concept. The concept would be "Contract" or "Awarding Result"
2. Ontology: Data element which value can be inferred.

**Comment by guascce** [comment]
Did we decide that the glossary should contain only concepts and not concepts'properties? 
Won't we need to define formulas on the basis of which these properties are built? If not in the glossary where will they be managed?
In this case the relationship to zero, one or more winner(s) is not reflected and the definition lacks precision: at least one winner of the procedure is a SME as defined ... or all winners of the procedure.

**Comment by paulakeen** [comment]
I. Precisions on the definitions should in the glossary as additional information (cfr. ISO/IEC 11179-4:2004). This is why I insisited during the last Glossary Meeting taht we should think of a "layout" for the Glossary so we can have:

- Term
- Definition
- Additional Information
- Examples
- Synomyms
- Antonyms

II. For the Ontology development we are using a Data Element Dictonary (DED, UBL-2-2-based) where we collect all the properties, cardinalities, axioms, definitions, examples. CEN/BII, e-Sens, other use DEDs to produce automatically human-readable tables with "Information Requirements" (e.g. HTML, PDF, etc.). In time we could do the same.

Our DED is [shared](https://github.com/eprocurementontology/eprocurementontology/blob/master/v2.0.0/02_IR_DED/eProcurement_glossary_and%20DED.xlsx) in the public repository. It's status is "in progress", hence we consider it an internal artefact used for the Ontology analysis and design purposes.

**Comment by muricna** [comment]
It was decided in the working group meeting of 27/04/2018 that both concepts and properties would be listed in the glossary and in the github we would mention whether terms were concepts or properties

**Comment by muricna** [comment]
WG 4/5/2018

Term: Awarded to small or medium enterprise (SME).

Definition: The award decision is attributed to an organisation that is an SME (small or medium enterprise) at the time of submitting a tender.

Working group discussion was on the need to put a point in time to this
