### ISSUE TITLE
GLOSSARY - Small and Medium Enterprise (SME)

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#85]
#### Definition:

Enterprises which employ fewer than 250 persons and which have an annual turnover not exceeding EUR 50 million, and/or an annual balance sheet total not exceeding EUR 43 million.

Source: [EU recommendation 2003/361](http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32003H0361&from=EN)

**_Additional information_**: 

Three categories of SMEs are distinguished: 

- **micro**: an enterprise which employs fewer than 10 persons and
whose annual turnover and/or annual balance sheet total does not exceed EUR 2 million
- **small**:  an enterprise which employs fewer than 50 persons and whose annual turnover and/or annual balance sheet total does not exceed EUR 10 million.
- **medium sized**: the rest of enterprises from 50 to 250 persons and from 10 to 43 million.

*Beware that* this definition provided by the European Commission is currently under [public consultation](https://ec.europa.eu/info/consultations/public-consultation-review-sme-definition_en), until the 6th of May 2018.

#### Reason:

Relevant for the Use Cases 1 and 4 about transparency and monitoring.

**Comment by muricna** [comment]
WG 4/05/2018
Use definition above but pay attention to changes in legislation
Keep additional information 
Medium sized: Keep text from micro and small ie an enterprise which......remove the work rest

**Comment by muricna** [comment]
I have removed the plural from the SME definition to align with the other terms here and in the ontology

**Comment by eprocurementontology** [comment]
WG approval 4/05/2018

Term: Small and Medium Sized Enterprise (SME)
Definition: An enterprise which employs fewer than 250 persons and whose annual turnover not exceeding EUR 50 million, and/or an annual balance sheet total not exceeding EUR 43 million.

Additional information/WG discussion points: Becareful if recommendation or legislation changes
This is a refined granularity of SME.

The glossary has been updated accordingly on 29/06/2018.
The CM already took into account this concept as a code. SME is a code identifier from the codelist "EO Industry Classification Type", which is used by the class Economic Operator: 
![economic_operator](https://user-images.githubusercontent.com/26460487/43513034-08a981c0-957d-11e8-9a63-97cff9e92a3f.jpg)
