### ISSUE TITLE
GLOSSARY - Language

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#89]
#### Current:

* Term: Language
 
* Definition: Idioms in which tenders or requests to participate may be submitted.

#### New:

* Term: Submission Language

* Definition:

* The language that must be used by the Economic Operator to draft its documents or the information communicated to the Procuring Entity.

Examples; The language of the Tender, requests to participate, questions and requests for clarification, etc.

#### Reason:
In the current glossary the concept "language" is to broad, however the definition is referring only to the documents and information submitted by the Economic Operator.

**Comment by muricna** [comment]
Language is an EU vocabularies code list the definition should be taken from EU vocabularies.
