### ISSUE TITLE
Glossary - Candidate

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#92]
Term: Candidate 
Definition: an economic operator that has sought an invitation or has been invited to take part in a restricted procedure, in a competitive procedure with negotiation, in a negotiated procedure without prior publication, in a competitive dialogue or in an innovation partnership

WG decsision 14/05/2018
Concept

**Comment by eprocurementontology** [comment]
WG approval 14/05/2018

Term: Candidate
Definition: An economic operator that has sought an invitation or has been invited to take part in a restricted procedure, in a competitive procedure with negotiation, in a negotiated procedure without prior publication, in a competitive dialogue or in an innovation partnership

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
