### ISSUE TITLE
Glossary - Contracting entity

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#94]
Term:  Contracting entity
Definition: Contracting authority or public undertaking which pursues one of the following activities:  Gas and heat, electricity, water, transport services, ports and airports, postal services and 
extraction of oil and gas and exploration for, or extraction of, coal or other solid fuels.
When the contracting entity is not a contracting authority or public undertaking, it has as one of its activities any of the activities mentioned above or any combination thereof and operate on the basis of special or exclusive rights granted by a competent authority of a Member State.

WG Approval 14/05/2018 - may need improving

Discussion on whether contracting entity, contracting authority, procuring entity.
In ESPD contracting authority is used as the espd is only mentioned in Directive 24
Contracting entity could not globalise both terms as definition says contracting authorities in specific terms.

**Comment by eprocurementontology** [comment]
WG approval 14/05/2018

Term: Contracting Entity
Definition: Contracting authority or public undertaking which pursues one of the following activities: Gas and heat, electricity, water, transport services, ports and airports, postal services and
extraction of oil and gas and exploration for, or extraction of, coal or other solid fuels.
When the contracting entity is not a contracting authority or public undertaking, it has as one of its activities any of the activities mentioned above or any combination thereof and operate on the basis of special or exclusive rights granted by a competent authority of a Member State.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.

**Comment by JachymHercher** [comment]
As mentioned in https://github.com/eprocurementontology/eprocurementontology/issues/95, this definition omits two types of organisations that may run procurement procedures / publish notices. I suggest adding the other two to the definition.
