### ISSUE TITLE
GLOSSARY - GPA Usage

### ISSUE THREAD

**Issue by sembu-eproc** [OP-TED/ePO#96]
#### Current:

* Term: GPA Usage

* Definition: The procurement procedure is covered by the Government Procurement Agreement (GPA), which has the aim to establish a multilateral framework of balanced rights and obligations relating to public contracts with a view to achieving the liberalisation and expansion of world trade.

#### New:

* Definition: Specifies whether the GPA applies.
Additional information: the GPA aims to establish a multilateral framework of balanced rights and obligations relating to public contracts with a view to achieving the liberalisation and expansion of world trade.
For more information see [Agreement on Government Procurement](https://www.wto.org/english/tratop_e/gproc_e/gp_gpa_e.htm)

**Comment by JachymHercher** [comment]
Makes sense. We should avoid acronyms though, so the definition should rather be "Specifies whether the Agreement on Government Procurement (GPA) applies." 

I would mention "GPA", even though we don't use it later, as some people may know it only as GPA.

**Comment by muricna** [comment]
Check alignment with https://github.com/eForms/eForms/issues/140

**Comment by jseguraf** [comment]
The model and the term have been updated accordingly.
