### ISSUE TITLE
GLOSSARY - Options

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#99]
#### Current:

* Term:Options

* Definition: The possibility to make adjustment of the contract during its term (price revision clauses, changes in the duration of the contract, additional works, services or supplies, etc.), which must be specified and described by the buyer.

#### New:

* Term: Options

* Definition: Statement by the Procuring Entity about whether it may apply modifications to the procurement procedure that would alter the overall nature of the contract or the framework agreement.

#### Reason:

Stated in Directive 2014/24/EU, Article 72, 1(a) (last sentence of the paragraph).

**Comment by JachymHercher** [comment]
I don't understand the Reason - the quoted article is somewhat linked to the topic of options, but I don't see how it leads to the proposed definition. 

In my opinion, these are the two main problems with the definition:
- It talks about modifications to the procedure, while the procedure is already finished at a time that one would use an option. I don't think an option modifies a procedure at all (and potentially not even a contract, see below.)
- It links the definition of options with "altering the overall nature of the contract". I think that's a secondary legal question not really relevant for the definition. (There can be options that allow altering the overall nature of the contract - and their use would require a new procedure; there can be options that don't - and those you can use without a new procedure.)

I would suggest using the eForms definition: "Whether the Procuring Entity reserves the right (not an obligation) for additional purchases from the contractor (while the contract is valid)." This definition is based on https://en.wikipedia.org/wiki/Option_(finance) definition of "[...] an option is a contract which gives the buyer (the owner or holder of the option) the right, but not the obligation, to buy [...]". Pointers to yet another defnition could probably be found at https://en.wikipedia.org/wiki/Option_contract.

**Comment by andreea-pasare** [comment]
In ePO 3.0.1 the concept epo:ContractTerm has the attribute epo:hasOptions with the definition "The buyer reserves the right (not an obligation) for additional purchases from the contractor (while the contract is valid)."
